### ISSUE TITLE
add regression test framework

### ISSUE THREAD

**Issue by garlick** [openpmix/openpmix#103]
It would be nice if tests could be run more frequently and conveniently, and if there was a framework for adding new tests.  For a start it would be good to build the existing tests by default, without requiring `configure --disable-visibility` and wire some of them to "make check".

We have successfully used [test anything protocol](https://testanything.org/) on some projects.  Some useful bits:
- [Automake](https://www.gnu.org/software/automake/manual/html_node/Use-TAP-with-the-Automake-test-harness.html) can run TAP tests via `make check` and interpret results
- [libtap](https://github.com/zorgnax/libtap) is a tiny embeddable library for TAP tests written in C
- Git's [sharness](https://github.com/mlafeldt/sharness) is an embeddable TAP library for shell driven tests

**Comment by igor-ivanov** [comment]
I see that Mellanox/jenkins is launched on every PR and report issues on existing tests but final result is OK. I think it could be fixed to get correct result.

**Comment by rhc54** [comment]
We are running regression tests every night, both standalone and as part of OMPI, so I think this can be considered done (though the methods may differ from those suggested).
