### ISSUE TITLE
Multi-job/multi-user PMIx 

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#108]
@rhc54 @garlick @dsolt @karasevb

We were working on fixing "Permission denied" problem with PMIx **dstor** implementation and I realized that it has something to do with multi-job/multi-user problem we already discussed.

**dstor** creates a set of files that supposed to be accessed by application processes in order to get the key-values. And as it was with usock I'm hitting access problems. Right now we will fix it in the way we do this with usock - set owner of the file to the app user and the group will belong to PMIx server user. However this is not a way to go in future with the multi-job/multi-user cases.

When I started thinking about this more generic case I came up with the following solution that I'd like to discuss with the community.
- Currently we pass the JOB user id to the PMIx_server_init wich doesn't sound right in mult-job case. 
- I suggest to provide user ID on per-namespace basis and create a separate usock/dstor instances for each job/namespace during PMIx_namespace_register (I'm considering the namespace to be an entity holding job's key-values). If I recall correctly recent changes we verify new connections on pmix usock against expected user ID. If we create new usock with proper UID for each namespace it should solve the problem for multi-job/multi-user case.

This is not to be implemented tomorrow, but to discuss as a future plan.

**Comment by garlick** [comment]
I don't think I have the enough context to be of much user here, but I did want to point out this from NOTES section of unix(7) on Linux:

> In  the Linux implementation, sockets which are visible in the filesys‐
       tem honor the permissions of the directory they are in.   Their  owner,
       group,  and  permissions can be changed.  Creation of a new socket will
       fail if the process does not have write and search (execute) permission
       on  the  directory  the socket is created in.  Connecting to the socket
       object requires read/write permission.  This behavior differs from many
       BSD-derived  systems  which ignore permissions for UNIX domain sockets.
       Portable programs should not rely on this feature for security.

So apparently it's not safe to depend on owner/mode of socket file to limit access, at least if you want to be portable to BSDs. The SO_PEERCRED (or platform equivalent) check is better.  There's no reason that check couldn't be made against a list of users rather than just the one.

**Comment by jjhursey** [comment]
Any update on this issue?

**Comment by artpol84** [comment]
I guess we can close this one.
Feel free to close all dstor-related issues. I don't think any of them worth the effort.
