### ISSUE TITLE
PMIx Fence optimizations

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1127]
PMIx libraries may choose to implement an optimization for the case where only the calling process is involved in the fence operation by immediately returning PMIX_OPERATION_SUCCEEDED from the client's call in lieu of passing the fence operation to a PMIx server. Fence operations involving more than just the calling process must be communicated to the PMIx server for proper execution of the included barrier behavior.

Similarly, fence operations that involve only processes that are clients of the same PMIx server may be resolved by that server without referral to its host environment as no inter-node coordination is required.

However, in some cases the host environment needs to _always_ be called for a fence operation. For example, the host environment may provide an optional debugging capability that tracks the number of times fence was executed. We therefore need an attribute (to be passed at PMI_Init) that tells fence to bypass these optimizations and always call the host.

**Comment by rhc54** [comment]
The client-side optimization would be executed in src/client/pmix_client_fence.c

The server-side optimization would be executed in src/server/pmix_server_ops.c, in the pmix_server_fence function

**Comment by hjafari-could** [comment]
Ok

**Comment by jjhursey** [comment]
Ref: https://github.com/openpmix/openpmix/pull/1824

```
    (void) pmix_mca_base_var_register ("pmix", "pmix", "server", "fence_localonly_opt",
                                       "Optimize local-only fence opteration by eliminating the upcall to the RM (default: true)",
```

This MCA parameter controls behavior on the server-side of the OpenPMIx library. Further optimizations could be made here on the client side.

**Comment by rhc54** [comment]
Safe to say this won't happen after this long.
