### ISSUE TITLE
Question about use of pmix_value_t

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#1133]
Thank you for taking the time to submit an issue!

## Background information

Question about use of pmix_value_t

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

github master @ 13baa77fe2ac3a1cd70f05729875a4a6e1e85de4

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

This is actually a question.  In e.g. `examples/client.c`, there is code like this

```C
     95 int main(int argc, char **argv)
     96 {
     97     int rc;
     98     pmix_value_t value;
     99     pmix_value_t *val = &value;
```

Is line 99 pointing to value in line 98 necessary, or could I just use an uninitialized pointer in line 99?  A few tests have worked, but this could easily "just appear to work" accidentally.

**Comment by rhc54** [comment]
😆 no, it isn't necessary at all - in fact, it is rather a useless assignment as PMIx_Get allocates an address and inserts it into val anyway, thereby overwriting that assignment. I'll update the example to get rid of it.

Thanks for pointing it out!
