### ISSUE TITLE
Test HASH gds component in Mellanox CI

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#1223]
See https://github.com/pmix/pmix/pull/1207#issuecomment-485582679

**Comment by jjhursey** [comment]
@amaslenn do you know if the new Mellanox CI includes testing of the `hash` GDS component?

**Comment by amaslenn** [comment]
> @amaslenn do you know if the new Mellanox CI includes testing of the `hash` GDS component?

@karasevb could you please help?

**Comment by artpol84** [comment]
https://github.com/openpmix/openpmix/blob/master/.github/actions/mlnx/entrypoint.sh#L400

It should be tested
