### ISSUE TITLE
Preemption Unique Identifier - Application Level Information

### ISSUE THREAD

**Issue by ericpershey** [openpmix/openpmix#1315]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
3.1.2

-----------------------------

## Details of the problem
https://pmix.org/support/faq/what-are-rms-required-to-provide/
Application Level Information

It would be useful to have a preemption identifier, like JobID that would give you a way to uniquely identify the exact job and what preemption run occurred.

If you were to have a job that was preempted 3 times and the 2nd instance had an issue, it would allow you to reference that 2nd instance in the data.  This assume that we are able to get the job, the start and end of each preemption.

job#123(pre#0) -> preemption -> job#123(pre#1) -> preemption -> job#123(pre#2) -> preemption -> job#123(pre#3)

Then you could refer to job#123(pre#1), the second run, and get related information such as start, end and where for that specific run.

**Comment by jjhursey** [comment]
(Note to self) We should add `PMIX_REINCARNATION` to the v4.x standard doc. We should probably also sweep up any others that we might have missed.

**Comment by rhc54** [comment]
I'm doing that now as I returned to working on the doc.
