### ISSUE TITLE
Multi-namespace support in dstore

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#1414]
Ref: #1158 (maybe related to #1404)

The goal of this issue is to ensure that we are taking optimal code paths and use the dstore everywhere it is possible.

Action Items:
* @dsolt, @rhc54 : advice on the test suite that should be exercised to ensure that everything is working OK (we should probably think of adding this to the test suite)
* @artpol84, @karasevb: analyze the use-cases and fix if needed.

**Comment by artpol84** [comment]
AI:

**Comment by rhc54** [comment]
No longer relevant
