### ISSUE TITLE
Potentially harmless errors about /tmp/spmix_appdir_* in slurm logs

### ISSUE THREAD

**Issue by jschwartz-cray** [openpmix/openpmix#1444]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

PMIx v3.1.3

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From an RPM I built from the github 3.1.3 src RPM:

```
rpmbuild \
    --define 'install_in_opt 1' \
    --define 'build_all_in_one_rpm 0' \
    --define 'install_modulefile 1' \
    --rebuild pmix-3.1.3-1.src.rpm
```

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: Various x86_64, 8-20 cores each, 32GB-64GB memory each
* Network type: IB

-----------------------------

## Details of the problem

Noticed the following (potentially harmless) errors in `journalctl -xe | grep slurm` consistently on every job across all my systems:

```
Sep 13 11:02:20 xxxxxxxx slurmstepd[16961]: error: xxxxxxxx [8] pmixp_utils.c:476 [_is_dir] mpi/pmix: ERROR: Cannot stat() path="/tmp/spmix_appdir_607.0": No such file or directory (2)
Sep 13 11:02:20 xxxxxxxx slurmstepd[16961]: error: xxxxxxxx [8] pmixp_utils.c:496 [pmixp_rmdir_recursively] mpi/pmix: ERROR: path="/tmp/spmix_appdir_607.0" is not a directory
Sep 13 11:02:20 xxxxxxxx slurmstepd[16961]: error: xxxxxxxx [8] pmixp_client.c:493 [pmixp_libpmix_finalize] mpi/pmix: ERROR: Failed to remove /tmp/spmix_appdir_607.0
```

I have not yet been able to correlate these to any problem so it may be harmless and a minor issue, but I wanted to make you aware of it.

**Comment by rhc54** [comment]
@artpol84 This is in the Slurm plugin - can you please take a look?

**Comment by jjhursey** [comment]
Ping @artpol84

**Comment by artpol84** [comment]
Sorry, @jschwartz-cray, @rhc54, @jjhursey 
I missed this one.
@karasevb FYI.
Please add to the TODO list to investigate!

**Comment by rhc54** [comment]
@karasevb Have you had a chance to look at this yet?

**Comment by jjhursey** [comment]
@artpol84 @karasevb Any update on this issue?
