### ISSUE TITLE
Debugging output in latest git HEAD

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#1477]
Thank you for taking the time to submit an issue!

## Background information

Unexpected text output (only in PBS/Torque as far as I can see)

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master  8ee56d5a008926564c6a9a9460fe59b07d212010

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

Debugging output appears during "normal" execution, e.g.

```shell
[cn077:60819] ADDING NODE/APP INFO
[cn077:60819] ADDING NODE/APP INFO
cn076: Hello from PE    0 of    4
cn076: Hello from PE    1 of    4
cn077: Hello from PE    2 of    4
cn077: Hello from PE    3 of    4
```

```C
src/server/pmix_server.c:3390:            pmix_output(0, "ADDING NODE/APP INFO");
```

**Comment by rhc54** [comment]
Crud - sorry about that. Will remove immediately
