### ISSUE TITLE
Startup rank error under SLURM

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#1484]
Thank you for taking the time to submit an issue!

## Background information

Latest PMIx generating errors under SLURM

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

via SLURM pmix plugin in package

```
slurm-ohpc-17.11.10-6.2.ohpc.1.3.6.aarch64
```

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

git master @ 7d92a4d9835e6f949e904c3d9da2d6c382361862

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

```shell
$ srun -n 4 --ntasks-per-node=2 ./a.out
slurmstepd: error: st05 [0] pmixp_dmdx.c:320 [_dmdx_req] mpi/pmix: ERROR: Bad request from st06: nspace "slurm.pmix.801.0" has only 4 ranks, asked for -1
slurmstepd: error: st05 [0] pmixp_dmdx.c:320 [_dmdx_req] mpi/pmix: ERROR: Bad request from st05: nspace "slurm.pmix.801.0" has only 4 ranks, asked for -1
^Csrun: interrupt (one more within 1 sec to abort)
```

**Comment by rhc54** [comment]
Hi @tonycurtis - I'm on leave thru the end of the year and so my response time isn't going to be as good as it used to be. I gather this cmd line works with other versions of PMIx? Just wondering if the ntasks-per-node option is confusing the PMIx plugin.

**Comment by tonycurtis** [comment]
> On Oct 16, 2019, at 1:33 PM, Ralph Castain <notifications@github.com> wrote:
> 
> Hi @tonycurtis <https://github.com/tonycurtis> - I'm on leave thru the end of the year and so my response time isn't going to be as good as it used to be. I gather this cmd line works with other versions of PMIx? Just wondering if the ntasks-per-node option is confusing the PMIx plugin.
> 

Tried without —ntasks but same problem.  It’s all been working perfectly until the last day or so.

Haven’t tried this setup with other PMIx versions, but will do.

Tony

**Comment by rhc54** [comment]
No need - if it has been working, then it is an introduced bug in master. I'll poke at it.

**Comment by rhc54** [comment]
Just one last point of clarification: is Slurm using the same version of PMIx (i.e., master)? Or is it using some other version?

**Comment by tonycurtis** [comment]
> On Oct 16, 2019, at 2:00 PM, Ralph Castain <notifications@github.com> wrote:
> 
> Just one last point of clarification: is Slurm using the same version of PMIx (i.e., master)? Or is it using some other version?
> 

Assuming I’m looking in the right place:

/* define PMIx version */
#define PMIX_VERSION_MAJOR 2L
#define PMIX_VERSION_MINOR 1L
#define PMIX_VERSION_RELEASE 4L

#define PMIX_NUMERIC_VERSION 0x00020103


Tony

**Comment by rhc54** [comment]
Okay, that's the problem. Still working on a cross-version issue on master and v3.1.5.

**Comment by rhc54** [comment]
@tonycurtis I believe this is fixed now - at least, it passes my cross-version tests. Could you give it a try and close this if it is now okay?

**Comment by tonycurtis** [comment]
> On Oct 21, 2019, at 8:42 AM, Ralph Castain <notifications@github.com> wrote:
> 
> @tonycurtis <https://github.com/tonycurtis> I believe this is fixed now - at least, it passes my cross-version tests. Could you give it a try and close this if it is now okay?
> 

Looks good
thanks
Tony

**Comment by rhc54** [comment]
Thanks!
