### ISSUE TITLE
Issues with legacy support for PMI calls

### ISSUE THREAD

**Issue by karthik-vm** [openpmix/openpmix#1536]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
PMIx 2.2.3

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Source/distribution tarball
### Please describe the system on which you are running

* Operating system/version: Linux/ 4.14.0-115.8.1.el7a.ppc64le
* Computer hardware: POWER9 CPU + 6 Volta GPUs (Summit supercomputer)
* Network type:Infiniband EDR

-----------------------------

## Details of the problem

To enable Job Step Manager (JSM) support in MVAPICH2,  pmi4pmix a wrapper library for PMIx calls is used.  pmi4pmix is built using the latest PMIx 2.2.3 library and MVAPICH2 is built with JSM support using this pmi4pmix build. When OSU micro-benchmarks built using this MVAPICH2 library is launched using jsrun we see the benchmark hangs.

To debug the issue a small program [pmitest.txt](https://github.com/openpmix/openpmix/files/3817501/pmitest.txt) that exercises PMI calls is used. The program can be compiled and run as below:
```
$ mv pmitest.txt pmitest.c
$ gcc -o pmitest -I <pmix_install>/include -L<pmix_install>/lib -lpmi pmitest.c
$ ./pmitest
PMI_Init returned spawned = 0
size = 1, rank = 0
PMI_KVS_Get_name_length_max got 255
PMI_KVS_Get_my_name got 1234
PMI_Get_id_length_max got 255
PMI_Get_id got 1234
PMI_Get_kvs_domain_id got 1234
PMI_Get_key_maxlen got 511
PMI_Get_val_maxlen got 4096
[warn] event_active: event has no event_base set.
<hangs>
```
The program hangs in PMI_KVS_Get() function at line number 155 in pmitest.c file. 

When pmitest executable is run using mpirun we get failure in PMI_KVS_Iter_first which is not yet implemented. We would like to request the implementation of the API. Please find the output of the pmitest built using PMIx 3.1.4 launched using mpirun on OpenMPI 4.0.x below:
```
$ mpirun -np 1 ./osu_pmitest 
PMI_Init returned spawned = 0
size = 1, rank = 0
PMI_KVS_Get_name_length_max got 255
PMI_KVS_Get_my_name got 2688352257
PMI_Get_id_length_max got 255
PMI_Get_id got 2688352257
PMI_Get_kvs_domain_id got 2688352257
PMI_Get_key_maxlen got 511
PMI_Get_val_maxlen got 4096
PMI_KVS_Get(test_key_0) returned test_value_0
PMI_KVS_Get(foo) returned foo=bar baz=bif name="Buzz Bee" clink=~!@#$%^&*()_+`{}[]|\;':<>,. clank=a b c
PMI_KVS_Iter_first failed with rc = PMI_FAIL
$ echo $?
0
```
If both these issues are fixed we believe the JSM support would work fine enabling MVAPICH2 to work with jsrun.

**Comment by rhc54** [comment]
I can take a look at the problems. I don't offhand see a problem with implementing PMI_KVS_Iter_first but will let you know if I hit one.

**Comment by karthik-vm** [comment]
Thanks Ralph. We really appreciate your help.

**Comment by jjhursey** [comment]
Do you have a link to the `pmi4pmix` project? I'm assuming that is different than the pmi.h included in OpenPMIx, is that correct?

**Comment by rhc54** [comment]
I fixed the singleton operation at #1537. However, I didn't implement the Iter_first function just yet as I'm not sure you really want to use it. The only way to make that function work would be for the process to download _all_ information posted by procs in the job, create a list of it, and then step down that list. This would scale rather poorly both in terms of memory footprint and time.

Are you sure you want to use that function? It was dropped from PMI-2 due to the scalability issues, I believe.

**Comment by karthik-vm** [comment]
@jjhursey Please find the pmi4pmix library tarball here: [pmi4pmix.zip](https://github.com/openpmix/openpmix/files/3821521/pmi4pmix.zip). I also found that pmi.h present in pmi4pmix and in OpenPMIx are similar.
 
@rhc54 Thanks for fixing the singleton operation. I double checked the MVAPICH2 source and I do not see the PMI_KVS_Iter_first() function. But somehow it got included in the sample reproducer program. So I do not think we need it. I will create the pmi4pmix library with the PMIx library containing this fix to see if we can overcome the jsrun issues. Thanks once again for the quick fix.

**Comment by jjhursey** [comment]
Thanks @rhc54 for the quick fix!
 * PR #1537 was merged into `master`
 * PR #1538 was merged into the `v3.1` branch - you may want to use this branch for verification testing.

**Comment by karthik-vm** [comment]
@jjhursey I realized that Summit administrators have to install this fixed version of PMIx on Summit inorder for me to test there. Will send a request to them.

**Comment by jjhursey** [comment]
@karthik-vm It looks like this issue was resolved with the PRs above, but you are waiting to verify once it is on Summit. Is that correct? If so, then can we close this issue and you can re-open if there are further issues?

**Comment by rhc54** [comment]
PMIx v3.1.5 has been released - please reopen if the problem persists.

**Comment by karthik-vm** [comment]
> @karthik-vm It looks like this issue was resolved with the PRs above, but you are waiting to verify once it is on Summit. Is that correct? If so, then can we close this issue and you can re-open if there are further issues?

@jjhursey Sorry I totally missed your message. Sounds good. Thanks.
