### ISSUE TITLE
Dstore leaking 8MB of memory when a namespace exits while another namespace is running

### ISSUE THREAD

**Issue by dsolt** [openpmix/openpmix#1548]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

3.1.3 (e6837057034e7f22910d66ebdc590389b874f4f2)

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone, built both debug or non-debug

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

If we submit a job that registers a namespace:

jsrun --np 1 /hello_world_sleep.x 10 (an MPI Hello_world program that sleeps for 10 seconds before calling MPI_Finalize())
sleep 5
jsrun --np 1 /hello_world_sleep.x 10 

Wait for both job steps to exit.
Notice the total resident memory used by the PMIx server will have increased by 8MB.
This can be repeated with continual memory use increase.

THe problem appears to be coming from here:

```
-    /* A lot of nspaces may be using same session info
-     * session record can only be deleted once all references are gone */
-    if (!in_use) {
```

in src/mca/common/dstore/dstore_base.c

This checks to see if other nspaces are running:

```
for (map_idx = 0; map_idx < size; map_idx++){
       if (ns_map[map_idx].in_use &&
                       (ns_map[map_idx].data.tbl_idx == ns_map_data->tbl_idx)) {
           if (0 == strcmp(ns_map[map_idx].data.name, nspace)) {
            _esh_session_map_clean(ds_ctx, &ns_map[map_idx]);
               continue;
          }
          in_use++;
     }
}
````

I don't believe we can do this.  Once a namespace is deregistered, I think we have to deregister it.  It would be great of other namespaces could query information about namespaces that have exited, but its just not practical to keep the storage of every namespace, possibly indefinitely since you can have a job step queue with thousands of jobs that will prevent memory from being cleaned up.   Even if we fixed it so that once all namespaces were gone, we cleaned up all the namespaces at that point, that would not be sufficient.  A queue of thousands of jobs steps would eat of GB of memory since it would not reach the point where no namespaces are running until the queue was empty.

**Comment by jjhursey** [comment]
I believe this was resolved by the PRs below (please reopen if there is more work to do)
 - `master` PR #1549 
 - `v3.1` PR #1554
