### ISSUE TITLE
Problem with multiple PMIx_Init / Finalize call sequence

### ISSUE THREAD

**Issue by angainor** [openpmix/openpmix#1558]
I observe what seems to be a bug in a program, which uses OpenMPI and explicit PMIx calls. I use OpenMPI 4.0.2 with external PMIx 3.1.4. Consider the following pseudo-code:

```
PMIx_Init(...)

[...]

PMIx_Finalize(...)

MPI_Init(...)
```
The above sequence results in OpenMPI failure with the following message:
```
OPAL ERROR: Error in file ext3x_client.c at line 112
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
The problem disappears if I move the `PMIx_Finalize` after the `MPI_Init` call. 

From the standard I understood that multiple `PMIx_Init` calls are allowed, as long as followed by `PMIx_Finalize`, so it would seem the above is a bug.

Could you please comment? Thanks!

**Comment by rhc54** [comment]
From doing a light scan of the code, it likely is a bug but I'm not sure where. The difference in your two scenarios is that the first one causes PMIx in the client application to fully tear down, so I expect the problem is either that the server doesn't like seeing the client "reappear" or that the tear down isn't quite clean enough. I'll have to take a look

**Comment by angainor** [comment]
Thanks. I can work around it of course, but since the code I'm working with is C++, I'd like to put the Init / Finalize into constructor / destructor of my PMIx interface object. I could also create it after `MPI_Init`, but it doesn't work due to #1427.

**Comment by FaDee1** [comment]
> ขอบคุณ แน่นอนว่าฉันสามารถหลีกเลี่ยงได้ แต่เนื่องจากรหัสที่ฉันทำงานด้วยคือ C ++ ฉันจึงต้องการให้ Init / Finalize เป็น Constructor / destructor ของ PMIx interface object ของฉัน ฉันยังสามารถสร้างมันขึ้นมาหลังจากที่`MPI_Init`แต่มันไม่ทำงานเนื่องจาก#[ 1427](https://github.com/openpmix/openpmix/issues/1427)

**Comment by rhc54** [comment]
I'm sorry - can you please translate this into English and re-post?

**Comment by rhc54** [comment]
@angainor I'm pretty sure we fixed this now - can you please verify?

**Comment by angainor** [comment]
@rhc54 Thanks! I'll have a look sometime this week and let you know.
