### ISSUE TITLE
Add support for job/node/app/session info array keys in dstore

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#1567]
Per discussion [here](https://github.com/openpmix/openpmix/pull/1476#issuecomment-564723354) in PR #1476 dstore is missing support for job/node/app/session info array keys. On `master` this means that when these keys are requested we are going through the `hash` component instead of `dstore`.

@rhc54 Is this true of the `v3.1` branch as well or just on `master`?

**Comment by rhc54** [comment]
True everywhere, I'm afraid. Remember that those keys were defined in v2 of the Standard. However, I wouldn't worry about backporting to anything other than the v3.1 series.

**Comment by jjhursey** [comment]
I'm going to hold off on a 3.1.5 until I can assess the performance impact on SMPI. I'll take that action item.
@artpol84 @karasevb You can use this ticket to track your investigation.

**Comment by FaDee1** [comment]
> ต่อการสนทนา[ที่นี่](https://github.com/openpmix/openpmix/pull/1476#issuecomment-564723354)ใน PR [# 1476](https://github.com/openpmix/openpmix/pull/1476) dstore ไม่มีการสนับสนุนคีย์อาร์เรย์ของข้อมูลงาน / โหนด / แอป / เซสชัน เมื่อวันที่`master`นี้หมายถึงว่าเมื่อคีย์เหล่านี้ได้รับการร้องขอเราจะผ่านองค์ประกอบแทน`hash``dstore`
> 
> @ rhc54นี่เป็นความจริงของ`v3.1`สาขาด้วยหรือ`master`เปล่า?

**Comment by rhc54** [comment]
I need you to post in English so we can understand you - thanks

**Comment by jjhursey** [comment]
Performance assessment of modex `PMIx_Get` overhead with Open MPI v4.0.x

PMIx v3.1.5 assessment at 91b7c8b106e73c8b4630ed7f117a2651f20268bf
```
mpirun -np 160 --host nodeA:160 --bind-to hwthread --map-by hwthread -x PMIX_MCA_gds=ARGS ./a.out
1 node |    3.1.4 |    3.1.5 (HEAD)
-------+----------+----------
  hash | 0.000043 | 0.000043
  ds12 | 0.000180 | 0.000188
  ds21 | 0.000009 | 0.000009

mpirun -np 320 --host nodeA:160,nodeB:160 --bind-to hwthread --map-by hwthread -x PMIX_MCA_gds=ARGS ./a.out
2 node |    3.1.4 |    3.1.5 (HEAD)
-------+----------+----------
  hash | 0.000044 | 0.000044
  ds12 | 0.000199 | 0.000207
  ds21 | 0.000009 | 0.000010
```

No significant performance difference in this regard between the two levels. This is expected since we are not stressing the job/node/app/session data. it may be useful to do such an experiment with just job level data.

**Comment by jjhursey** [comment]
See Issue #1836 for a related issue

**Comment by rhc54** [comment]
No longer relevant
