### ISSUE TITLE
dstore v3: Modernization of the dstore component

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#1574]
Currently, there are several outstanding issues described below) related to the dstore. Addressing each of them will require breaking the backward compatibility. So I think those changes should come as a bundle called dstore v3.
Known issues:
1. dstore doesn't support the full set of information types/scopes that PMIx supports these days.
    * There was a set of workarounds to bypass the dstore for app-, session- and node-level information: #1476, #1497, #1519, #1531, #1532
    * The current state of PMIx info is described in https://github.com/openpmix/openpmix/pull/1573#issuecomment-567312338
    * Supporting different "levels" of information would require restructuring the memory layout of the dstor shmem segments and possibly introducing additional segments to have proper isolation.
1. Further locking optimizations:
    * at the EuroMPI'19 a new locking scheme `N(mutex+signal)` was presented ([[link](https://pmix.org/wp-content/uploads/2019/09/2019_EMPI_Polyakov_PMIx_v5.pptx)], see slides 24-28). Compared to the currently used `2N-mutex` scheme, it allows to avoid taking 2 mutexes per client, only one is needed.
    * Given solution to the issue (1) may result in the introduction of the separate segments for session-, job-, node-, and app-level data, it is possible to avoid locking on some of the info that is known to be static.
1. PMIx_Get latency optimizations
    * The previous analysis showed, that the presence of malloc's on the PMIx_Get path hurts the latency and is the next limiting factor https://github.com/openpmix/openpmix/issues/665#issuecomment-381660902.
    * We also discussed the opportunity to avoid packing/unpacking to/from the shmem segment.
    * There was a suggestion (Ref ??) to either introduce a new PMIx_Get-like routine or use the "info" parameter to communicate to PMIx that the user wants to receive a pointer to a read-only memory that he doesn't own, but can use. It would be beneficial to return a direct pointer to the dstore shmem fragment containing the data.

**Comment by FaDee1** [comment]
ผู้รับโอน

**Comment by rhc54** [comment]
No longer relevant
