### ISSUE TITLE
new_tracker always returns a tracker with trk->local set to false

### ISSUE THREAD

**Issue by dsolt** [openpmix/openpmix#1595]
git master, server/pmix_server_ops.c
also seems to be an issue in other branches such as 3.1.xx

**Comment by dsolt** [comment]
the problem is different in 3.1 branch.  trk->local is still not calculated correctly, but for different reasons.  there trk->local can be set to true in one place, but it is only tested on one of the namespaces.  so if there are multiple namespaces, only the last one will be checked.  if it is all local, then the whole tracker is set to true even though only one namespace was local.

**Comment by rhc54** [comment]
@dsolt I am truly puzzled by your title on this issue. The "new_tracker" function is supposed to return a new tracker, and we always initialize trackers to being "non-local" (i.e., trk->local is initialized to false). So is the true issue here that the local flag isn't being correctly computed later on?

If so, could you please change the issue title to correctly reflect the actual problem? This one was confusing.

**Comment by rhc54** [comment]
Hmmm...I think I may see what you meant. The logic in "new_tracker" sets the "local" flag to false if any participating proc isn't local. However, that logic requires that the "local" flag be initialized to true. I can correct that one easily enough.

**Comment by rhc54** [comment]
@dsolt Please see if the referenced PRs fixed what you were observing.

**Comment by jjhursey** [comment]
@dsolt does PR #1620 fix the issue for you on the v3.1 series? I'd like to get this fix in for the upcoming v3.1.5.

**Comment by jjhursey** [comment]
Is this ready to close?

**Comment by jjhursey** [comment]
Per teleconf this issue is ok to close now.
