### ISSUE TITLE
PMI Shim - Separate Project?

### ISSUE THREAD

**Issue by SteVwonder** [openpmix/openpmix#1612]
Is there any interest or objection to making a separate project/repo (under the openpmix or pmix organizations) out of the pmi1 and pmi2 shims?  Either that or adding a way to only compile and build the shims.

We currently use the shims to get Flux bootstrapping under JSM.  I suspect other PMI1/2 projects would find it useful to get their stuff bootstrapping on a PMIx resource manager/launcher.

**Comment by rhc54** [comment]
No objections - might take a bit of work as you'd have to adapt all the config stuff. I can create the repo for you if you want to pursue it.

**Comment by SteVwonder** [comment]
> might take a bit of work as you'd have to adapt all the config stuff.

We have a little makeshift Makefile for this purpose already.  I'll look into whether its going to be easier to build up from that or pare down the full OpenPMIx configure (probably the latter, as you suggest).

> I can create the repo for you if you want to pursue it.

Awesome! Let me cross my t's and dot my i's with LLNL's IP office and do some leg-work on the actual code before you go through the trouble.  I'll ping you again on this issue when I'm ready for a repo :)

**Comment by SteVwonder** [comment]
Ok.  We got the go ahead from LLNL's IP office.   If someone creates a separate repo under the OpenPMIx organization, I'll post a PR against it with what we have so far. We can iterate on the PR from there.

**Comment by rhc54** [comment]
Kewl - any preference on the name?

**Comment by SteVwonder** [comment]
> any preference on the name?

Not really.  I'm fine with `pmi-shim` or really anything you think sounds good.

**Comment by rhc54** [comment]
Done - https://github.com/openpmix/pmi-shim

**Comment by SteVwonder** [comment]
Thanks @rhc54!
