### ISSUE TITLE
bugfix release 3.1.5rc1 bumps major soname from 2 to 3 

### ISSUE THREAD

**Issue by pkovacs** [openpmix/openpmix#1624]
I note the major soname bump with 3.1.5rc1 from libpmix.so.2 to libpmix.so.3 . You're signalling a significant abi change with that bump -- was that the intent for this bugfix release? It's more work downstream, as an announcement has to be made so that all pmix client packages can be rebuilt.

**Comment by rhc54** [comment]
I filed the correction - thx for the heads-up!

**Comment by pkovacs** [comment]
@rhc54 Thanks Ralph.  Will wait for 3.1.5rc2.

**Comment by jjhursey** [comment]
This was fixed in 3.1.5rc2. We are currently at rc3. Please give it a try
 * https://github.com/openpmix/openpmix/releases/tag/v3.1.5rc3
