### ISSUE TITLE
soname of libmca_common_dstore

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#1633]
I request that the soname of libmca_common_dstore be bumped from so.1 to so.3 to match pmix3

# Background information

This primarily regards Debian/Ubuntu distributions but may happen elsewhere.
We split packages to enable smooth upgrades over versions and applications to continue to use "old" shared libraries.
For pmix, we ship the _library_ packages libpmi1-pmix, libpmi2-pmix, libpmix2, and the 
_development_ packages elibpmi-pmix-dev  libpmix-dev. Its libpmix2 for version 3.1.4 because it has soname so.2. 3.1.5 bumps this to so.3 and so the new package is libpmix3 and libpmix-dev (ignoring pmi packages for the moment).

The basic idea is that the -dev package contains headers, static libs , etc. and libpmix.so files, while the shared library package contains 
libpmix.so.2 -> libpmix.so.2.2.24 symlink
libpmix.so.2.2.24 file

Similarly for libpmix3. 
*libpmix2 and libpmix3 can be co-installed by design*.
After an upgrade (especially a distro upgrade), libpmix2 may no longer exist in Debian, but old copies can remain on a users system if needed by applications. 

Now the problem: pmix breaks this by shipping:
$(LIBDIR)/pmix/*.so submodules
libmca_common_dstore.*

These are currently shipped in the libpmix2 package. Doing so within a libpmix3 package leads to conflicts; moving them into their own package is possible, but undesirable (may be revisited).
Now the subdirectory can be solved by renaming it 'pmix3' (straightforward and tested), but libmca_* remains. While technically it has not been changed, it simplifies matters a great deal if its soversion is bumped and remains identical to libpmix.

### What version of the PMIx Reference Library are you using? 

pmix 3.1.5 rc 1

### Describe how PMIx was installed 

Built from source (I'm the Debian maintainer).

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ prun -np 2 ./hello_world
```

**Comment by amckinstry** [comment]
I've just downloaded 3.1.5rc3 - was the SOVERSION change an error ? its reverted to 2.2.24 ...

**Comment by rhc54** [comment]
The prior SOVERSION change was the error - it should have remained at 2. However, the point you make about the "common" library versioning is interesting as we normally wouldn't move that unless the code in that library itself changed, which it rarely does. I'm curious - how do you folks handle the common libs in OMPI? We mirror their practices, but I'll check with them to ensure we didn't miss something.

**Comment by amckinstry** [comment]
The file list for `libopenmpi3` looks like:
```
/usr/lib/x86_64-linux-gnu/libmca_common_monitoring.so.50.10.0
/usr/lib/x86_64-linux-gnu/libmca_common_ompio.so.41.19.2
/usr/lib/x86_64-linux-gnu/libmca_common_sm.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmca_common_verbs.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi.so.40.20.2
/usr/lib/x86_64-linux-gnu/libmpi_cxx.so.40.20.1
/usr/lib/x86_64-linux-gnu/libmpi_java.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi_mpifh-flang.so.40.20.2
/usr/lib/x86_64-linux-gnu/libmpi_mpifh-flang.so.40.20.2/libmpi_mpifh.so.40.20.2
/usr/lib/x86_64-linux-gnu/libmpi_mpifh-gfortran.so.40.20.2
/usr/lib/x86_64-linux-gnu/libmpi_mpifh-gfortran.so.40.20.2/libmpi_mpifh.so.40.20.2
/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr-flang.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr-flang.so.40.20.0/libmpi_usempi_ignore_tkr.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr-gfortran.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr-gfortran.so.40.20.0/libmpi_usempi_ignore_tkr.so.40.20.0
/usr/lib/x86_64-linux-gnu/libmpi_usempif08-flang.so.40.20.1
/usr/lib/x86_64-linux-gnu/libmpi_usempif08-flang.so.40.20.1/libmpi_usempif08.so.40.20.1
/usr/lib/x86_64-linux-gnu/libmpi_usempif08-gfortran.so.40.20.1
/usr/lib/x86_64-linux-gnu/libmpi_usempif08-gfortran.so.40.20.1/libmpi_usempif08.so.40.20.1
/usr/lib/x86_64-linux-gnu/libompitrace.so.40.20.0
/usr/lib/x86_64-linux-gnu/libopen-pal.so.40.20.2
/usr/lib/x86_64-linux-gnu/libopen-rte.so.40.20.2
/usr/lib/x86_64-linux-gnu/openmpi
/usr/lib/x86_64-linux-gnu/openmpi/lib
/usr/lib/x86_64-linux-gnu/openmpi/lib/ompi_monitoring_prof.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/libompi_dbg_msgq.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_allocator_basic.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_allocator_bucket.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_bml_r2.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_btl_openib.so
/usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_btl_self.so
...
```

so the plugins are in a subdir `openmpi3` which is simple enough to mirror for pmix
(Currently the experimental branch builds with
``` configure ... --sysconfdir=$(LIBDIR)/pmix3/share 
```
and `pmix-mca-params.conf` has 
```
...
mca_base_component_path = /usr/lib/x86_64-linux-gnu/pmix3/lib/pmix
...
```

In Openmpi all the common libs have moved in lock-sync with a new top-level soversion when the soversion of libmpi.* changed; if it was otherwise we'd have a problem there, too.

Ideally, we move to symbol versioning similar to glibc, etc:
https://github.com/open-mpi/ompi/issues/1956
This avoids the whole issue. The current issue (#1956) is closed but I want to update the patch and test on non-gcc compilers and resubmit for  5.x.

**Comment by rhc54** [comment]
I see - our bad, indeed. I'll make a note in our VERSION file to ensure we don't make the same mistake in the future, and we will fix the problem here (i.e., ensure that the SOVERSION of the common lib is 2 to match that of the main lib). I'll track that OMPI issue and we will mirror what they do. Thanks for the heads-up!

PMIx v4 is expected out in second quarter this year.

**Comment by amckinstry** [comment]
Thanks.
It would be good if the soversion of libmca_common_dstore.so was to move in time for 3.1.5.

**Comment by rhc54** [comment]
It will - we will generate another RC with that change. We have another fix that needs to get in anyway, so this is a timely request.

**Comment by rhc54** [comment]
@amckinstry We've been chatting over here with our OMPI compatriots and confess to some confusion about the above. OMPI doesn't change the common library triplet unless that library itself changes. Thus, the common library triplets do _not_ track the main library SOVERSION.

@jsquyres Can you review the above and help us out here? My inclination is that a library's triplet should never change if the library didn't change, so changing libmca_common_dstore just to make the c-a value track that of libpmix seems wrong to me. Have you OMPI folks actually been doing that all these years?

**Comment by jsquyres** [comment]
I can confirm that Open MPI only changes the Libtool CRA values:

* At new release series (e.g., vA.B.C, if A or B changes -- but not automatically when C changes)
* When the library itself changes

**Comment by rhc54** [comment]
okay, a little different than what I understood in the prior conversation. So it sounds like we should have changed the CRA of the common libs when we released a new major series so the C-A tracked.

Question now is: is it better that we correct this mid-series in 3.1.5? Or should we leave it as-is for now and correct it in v4?

**Comment by jsquyres** [comment]
Sorry @rhc54 -- I wasn't fully clear in our Slack conversation (i.e., I neglected to mention the "we do update the CRA numbers are A.B.0 releases" -- we do that so that if there's future A.(B-1).* releases, we have "legroom" in the available CRA values and we don't accidentally overlap.

**Comment by amckinstry** [comment]
Ok, not incrementing C.RA numbers in general unless the library changes makes sense.  Its just a convenience for the package maintainers that there be a bump.

The point being to allow the following:
Package `libpmix2` contains:
```
/usr/lib/MA/libpmix.so.2.2.25
/usr/lib/MA/libpmix.so.2   (symlink to above)
/usr/lib/MA/libmca_common_dstore.so.1.0.2
/usr/lib/MA/libmca_common_dstore.so.1 (symlink)
...
```
while `libpmix3` contains:
```
/usr/lib/MA/libpmix.so.3.2.0
/usr/lib/MA/libpmix.so.3  (symlink to above)
/usr/lib/MA/libmca_common_dstore.so.2.0.2
/usr/lib/MA/libmca_common_dstore.so.2 (symlink)
```
The two packages are co-installable because they contain no conflicts. Then after package/system upgrade libpmix2 (no longer shipped by Debian/Ubuntu) can remain on the system until all applications that use it are gone.
If they have a file in common, then libpmix3 Breaks and Replaces libpmix2 (in Debian terminology), and any applications the user has that require libpmix2 are broken. 

This is undesirable but survivable, if no user apps link libpmix2 directly, only via libopenmpi for example.

**Comment by amckinstry** [comment]
The use case is being able to install the _shared libraries_ from multiple versions of openmpi or pmix simultaneously to enable upgrades. 

Debian/Ubuntu typically makes this possible by putting each shared library in a separate package, and using the SO architecture to do so. This requires special handling of library major version updates.  

In principle this means one shared library file per package (eg `libpmix.so.2.2.25` in `libpmix2`,  `libpmix.so.3.2.0` in `libpmix3`.  In practice this can be relaxed _as long as all the files in `libpmix2` and `libpmix3` are distinct_.  eg. it is extreme for  libraries such as `libmca_common_store.so.1.0.2`, only used by pmix, to be shipped in its own package. If its filename is unique (major version is in lockstep with libpmix.so.X ) then this works. 



Note: this is just for shared libraries, there would only ever be one copy of the development files (include headers, static libs, etc) on a given system; upgrades replace the old `libpmix-dev` with a new one.

**Comment by jsquyres** [comment]
We chatted about this on a Webex today with @amckinstry and @rhc54 and me.  Summary:

* It finally clicked for Jeff: Alastair is trying just to be able to have major generations of PMIx libraries simultaneously installed -- not point releases.  This makes the whole proposal make a lot more sense.
* Yes, please update the .so version for PMIx v4 (@rhc54 will do!).  Not worth it for changing on PMIx v3.x.

**Comment by rhc54** [comment]
@amckinstry Would you please take a look at the VERSION settings in https://github.com/openpmix/openpmix/pull/1951 and see if this meets your requirements?

**Comment by rhc54** [comment]
For comparison purposes:
```text
                 v3.2.0            v4.0.0
libpmix          4:32:2            5:0:3
common_dstore    1:2:0             1:3:0
```

**Comment by amckinstry** [comment]
Yes, this works for us. 
It meets the requirement that major numbers increment in lockstep (or in this case, remain constant in lockstep).
