### ISSUE TITLE
Generating and installing a pmix.pc file for pkg-config

### ISSUE THREAD

**Issue by mdorier** [openpmix/openpmix#1673]
It would be very useful for openpmix to generate and install a pmix.pc file, so that we can get the libraries and cflags using pkg-config when linking programs against pmix.

**Comment by rhc54** [comment]
We would be happy to do so, but I personally at least lack the knowledge on how to do it. Unless someone else can contribute it, this may have to wait.

**Comment by mdorier** [comment]
It's not complicated. I submitted a PR with a work in progress: https://github.com/openpmix/openpmix/pull/1677
You can take a look; for now the dependencies are hard-coded. I'd appreciate your input on the best way to make the hard-coded variables depend on the actual dependencies selected at configure time. I see that the configure script invokes many other scripts from the config folder so I'm not sure yet what's the cleanest way to fill those PC_REQUIRES and PC_PRIVATE_LIBS variables.

**Comment by rhc54** [comment]
Fixed by #1677
