### ISSUE TITLE
Failed to run slurm with openpmix

### ISSUE THREAD

**Issue by hongyi-zhao** [openpmix/openpmix#1689]
Hi,

I try to using openpmix with slurm-20.02.1 and installed the openpmix on Ubuntu 19.10 as follows:

```
$ git clone https://github.com/openpmix/openpmix.git openpmix.git 
$ cd openpmix.git 
$ ./autogen.pl 
$ mkdir build
$ cd build/
$ ../configure  
$ make -j24
$ sudo make install
```

Then I do the test as following:

`$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so srun --mpi=pmix hostname`

But I stuck here, the above freeze there and gives nothing.

OTOH, I can run the following command successfully:

```
$ srun --mpi=pmi2 hostname 
ubuntu-01
```

Any hints for solving the problem?

Regards

**Comment by rhc54** [comment]
Just to ask the obvious - you did configure Slurm against that openpmix installation?

I also don't understand the purpose of adding ```I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so``` to your command line. If the app was an MPI one, including that envar would cause problems as you are indicating that the app is using PMIx by stating `--mpi=pmix`, not PMI-1. OpenMPI will ignore that envar, so I assume your intent is to use Intel MPI?

We can help more when we better understand what you are eventually hoping to do. Meantime, I'll defer to @artpol84 and @karasevb to help with the hang.

**Comment by hongyi-zhao** [comment]
> Just to ask the obvious - you did configure Slurm against that openpmix installation?

I installed the latest stable version of slurm 20.02.1 compiled by myself, which, if openpmix installed, will automatically detects the openpmix when the ./configure step, see the following info for more details: 

```
slurm-20.02.1$ ./configure |& grep pmi
checking for pmix installation... /usr/local
checking for freeipmi installation... 
configure: WARNING: unable to locate freeipmi installation (libipmonitoring/libfreeipmi
config.status: creating contribs/pmi/Makefile
config.status: creating contribs/pmi2/Makefile
config.status: creating src/plugins/acct_gather_energy/ipmi/Makefile
config.status: creating src/plugins/mpi/pmi2/Makefile
config.status: creating src/plugins/mpi/pmix/Makefile
```
> 
> I also don't understand the purpose of adding `I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so` to your command line. If the app was an MPI one, including that envar would cause problems as you are indicating that the app is using PMIx by stating `--mpi=pmix`, not PMI-1. OpenMPI will ignore that envar, 

I know this setting method from the slurm's official site [here](https://slurm.schedmd.com/mpi_guide.html#intel_srun).


> so I assume your intent is to use Intel MPI?

Yes, I'm trying to run slurm for scheduling the job of vasp, which is compiled using the intel parallel studio cluster version. 

> 
> We can help more when we better understand what you are eventually hoping to do. Meantime, I'll defer to @artpol84 and @karasevb to help with the hang.

Thanks again for your help.

Regards

**Comment by rhc54** [comment]
I see - well, Intel MPI doesn't currently support PMIx so far as I know, so installing PMIx will gain you nothing there. Indeed, you specified the use of the PMI-1 library, and so PMIx isn't being used anyway.

I'd suggest removing PMIx if your intent is to use Intel MPI. Just use libpmi.

**Comment by hongyi-zhao** [comment]
> I see - well, Intel MPI doesn't currently support PMIx so far as I know, so installing PMIx will gain you nothing there. Indeed, you specified the use of the PMI-1 library, 

From where do you know about this for my case -- ``you specified the use of the PMI-1 library''?  

> and so PMIx isn't being used anyway.
> 
> I'd suggest removing PMIx if your intent is to use Intel MPI. Just use libpmi.

Then how to configure slurm for compiling and how to invoke the srun comand for slurm?

See the following for my case:

```
$ srun --mpi list
srun: MPI types are...
srun: pmix_v3
srun: pmix
srun: none
srun: pmi2
```

Regards

**Comment by rhc54** [comment]
I gather you are rather new to this, so let me try to explain and apologize in advance if you already know some of these things. Intel MPI uses the `I_MPI_PMI_LIBRARY` environmental variable to determine which PMI library to use. You have set that envar to point at Slurm's PMI-1 library, and so that is what Intel MPI is going to use.

This is fine as Intel MPI only uses PMI-1 functions. Your configure output shows that you built the library:
```
config.status: creating contribs/pmi/Makefile
```
and so that means you have all that you need. You just need to tell `srun` to use the corresponding library. If you look at the Slurm documentation regarding use of Intel MPI (see https://slurm.schedmd.com/mpi_guide.html#intel_mpi), you don't need to specify the MPI type when using PMI-1, so the cmd line is just:
```
$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so srun -n N ./myapp
```

In terms of building Slurm, I would just remove the PMIx installation you included and reconfigure/rebuild Slurm, just to be safe. PMIx has a backward compatibility version of PMI-1 and PMI-2 in it, but those are not recommended for use - mostly there for folks to test and experiment with.

**Comment by karasevb** [comment]
@hongyi-zhao could you provide Slurm configure log file?

**Comment by hongyi-zhao** [comment]
@karasevb You mail? The log is rather large for posting here.
@rhc54 Thanks a lot for explanations.  I really new to this. I will try according to your notes.

**Comment by karasevb** [comment]
@hongyi-zhao karasev.b@gmail.com

**Comment by hongyi-zhao** [comment]
@rhc54 I try the following based on your notes:

  `$ sudo apt-get remove libpmix2 libpmix-dev libpmi-pmix-dev libpmi2-pmix`


See the following for the configure's output this time:

```
$ ./configure |& grep pmi
checking for pmix installation... 
configure: WARNING: unable to locate pmix installation
checking for freeipmi installation... 
configure: WARNING: unable to locate freeipmi installation (libipmonitoring/libfreeipmi
config.status: creating contribs/pmi/Makefile
config.status: creating contribs/pmi2/Makefile
config.status: creating src/plugins/acct_gather_energy/ipmi/Makefile
config.status: creating src/plugins/mpi/pmi2/Makefile
config.status: creating src/plugins/mpi/pmix/Makefile

```
Regards

**Comment by karasevb** [comment]
@hongyi-zhao Thanks for the log file.

You are using PMIx from master branch, it corresponds to v4 that not supported in Slurm yet:
```log
configure:17169: checking for pmix installation
configure:17204: gcc -o conftest -DNUMA_VERSION1_COMPATIBILITY -g -O2 -pthread -I/usr/local/include    conftest.c -L/usr/local/lib -lpmix  -lresolv  >&5
configure:17204: $? = 0
configure:17235: gcc -E -I/usr/local/include  conftest.c
conftest.c:114:18: error: #error "not version 4"
  114 |                 #error "not version 4"
      |                  ^~~~~
```

You may have installed PMIx v3 earlier and Slurm discovers PMIx v3:
```
HAVE_PMIX_V3_FALSE='#'
HAVE_PMIX_V3_TRUE=''
```

**Comment by karasevb** [comment]
@hongyi-zhao, could you install the  PMIx version till v3 or v3 and configure Slurm with it?

**Comment by hongyi-zhao** [comment]
@karasevb I should have installed all of them from the system's repo, now, I removed them by using the following based on the notes of @rhc54 :

`
sudo apt-get remove libpmix2 libpmix-dev libpmi-pmix-dev libpmi1-pmix`

**Comment by hongyi-zhao** [comment]
> I gather you are rather new to this, so let me try to explain and apologize in advance if you already know some of these things. Intel MPI uses the `I_MPI_PMI_LIBRARY` environmental variable to determine which PMI library to use. You have set that envar to point at Slurm's PMI-1 library, and so that is what Intel MPI is going to use.
> 
> This is fine as Intel MPI only uses PMI-1 functions. Your configure output shows that you built the library:
> 
> ```
> config.status: creating contribs/pmi/Makefile
> ```
> 
> and so that means you have all that you need. You just need to tell `srun` to use the corresponding library. If you look at the Slurm documentation regarding use of Intel MPI (see https://slurm.schedmd.com/mpi_guide.html#intel_mpi), you don't need to specify the MPI type when using PMI-1, so the cmd line is just:
> 
> ```
> $ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so srun -n N ./myapp
> ```
> 
> In terms of building Slurm, I would just remove the PMIx installation you included and reconfigure/rebuild Slurm, just to be safe. PMIx has a backward compatibility version of PMI-1 and PMI-2 in it, but those are not recommended for use - mostly there for folks to test and experiment with.

After I remove all of the pmix relative stuff from my box like the following:

`$ sudo apt-get remove libpmix2 libpmix-dev libpmi-pmix-dev libpmi2-pmix libpmi1-pmix`

And also remove the self-compiled/installed openpmix from repo.

Then I cannot find any of libpmi.so file at all:

```
$ sudo updatedb
$ mlocate -ir 'libpmi.so'
$

```

So, in this case, I cannot use the command line like the following:

`$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so srun -n N ./myapp`

OTOH, the following usage is suggested [here](https://hpc-uit.readthedocs.io/en/latest/jobs/running_mpi_jobs.html#intel-mpi):

`$ srun --mpi=pmi2 ./my_application`

And really it can work smoothly for my case.

**Comment by rhc54** [comment]
You have me confused. Your link is to instructions for operating on a specific cluster that has obviously been configured in a particular manner. Are you using that cluster? Or are you doing this on your own cluster?

**Comment by hongyi-zhao** [comment]
> You have me confused. Your link is to instructions for operating on a specific cluster that has obviously been configured in a particular manner. Are you using that cluster? Or are you doing this on your own cluster?

I just use their suggestions for my case on my own cluster.

**Comment by rhc54** [comment]
Using docs from other clusters can get you into trouble unless you know specifically how that cluster was built and configured, so you should be very careful about doing so.

Regardless, it sounds like you have a working system. Until you learn more about how to administer Slurm, I would suggest just using it - and don't change anything in your Slurm setup!

**Comment by hongyi-zhao** [comment]
@rhc54 Some tests for my case:

Just as you told and analyzed,  I tried all of the following usages.

After installed the openpmix from this repo, it will show the following:

```
$ srun --mpi list
srun: MPI types are...
srun: pmix_v3
srun: pmix
srun: none
srun: pmi2
```

So I tried with the following possible usages to submit the job and find that all of these failed to start the job:

```
# This lib file is installed via the system's repo:
$ I_MPI_PMI_LIBRARY=/usr/lib/x86_64-linux-gnu/pmix/lib/libpmi.so srun -n $SLURM_NTASKS vasp_std

$ srun --mpi pmix -n $SLURM_NTASKS  vasp_std
$ srun --mpi pmix_v3 -n $SLURM_NTASKS vasp_std

# The following lib files are installed by the self-compiled openpmix:
$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi.so srun -n $SLURM_NTASKS vasp_std
$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmi2.so srun -n $SLURM_NTASKS vasp_std
$ I_MPI_PMI_LIBRARY=/usr/local/lib/libpmix.so srun -n $SLURM_NTASKS vasp_std
```

And the only one which can do the trick is the following usage:

`$ srun --mpi pmi2 -n $SLURM_NTASKS vasp_std`

Regards

**Comment by rhc54** [comment]
As I said, do _not_ install and try to use PMIx with Intel MPI. You need to use the Slurm-provided PMI libraries. Installing PMIx the way you are doing _overwrites_ the Slurm libraries with experimental PMIx backward compatibility libraries and causes problems. This has been widely documented by the Slurm folks and is why they do _not_ install the PMIx backward compatibility libraries.

I honestly cannot help you if you continue to insist on installing PMIx for use with Intel MPI. It is not a supported configuration.

**Comment by hongyi-zhao** [comment]
@rhc54 Thanks a lot, got it. I'll disable and remove them from now on for my case.
