### ISSUE TITLE
Create a "PMIx acceptance test" for Open MPI.

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1692]
This is a PMIx unit test that exercises the PMIx API/Attributes that Open MPI uses

**Comment by jjhursey** [comment]
This would still be great to do. Even just listing the APIs and Attributes that Open MPI (or another consumer of PMIx) uses would be useful. Then a unit test could be created.

That first step of creating a list is a good first issue for someone looking to understand the dependecies between Open MPI and PMIx.

The second step of creating a unit test is a good first issue for someone that wants to create a small PMIx program.

**Comment by rhc54** [comment]
I don't sense any support for this in the OMPI community, and it certainly would be their responsibility to pursue it.
