### ISSUE TITLE
Complete tool support

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1695]
Need to complete and verify tool support for debuggers

**Comment by rhc54** [comment]
Removing the "blocker" status as the fundamentals appear to be done. There remain some features to complete, but those can come post-v4.0 release

**Comment by jjhursey** [comment]
I agree that we are close. We are iterating on the PRRTE side, and I _think_ OpenPMIx is solid here. However, until we finish things in PRRTE we should probably keep this open. I only expect bug fixes related to the tool support.

Plan for closing this issue:
 * Finish tool examples/support in PRRTE
 * File any outstanding bugs/enhancements related to tools support in OpenPMix
