### ISSUE TITLE
Update and release PMIx v4 Standard

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1696]
Capturing this here so we don't forget!

- [x] Tools chapter

- [x] Verify all new attributes in pmix_common.h are included

- [x] Verify all new APIs are present

**Comment by jjhursey** [comment]
I'll sign up to work on some automation to help check the attributes/APIs are present in the document.
We have this ticket open in the pmix-standard repo for that activity:
 * https://github.com/pmix/pmix-standard/issues/149

**Comment by rhc54** [comment]
Completed
