### ISSUE TITLE
Error from gds_ds12_lock_pthread.c file while running pmi 

### ISSUE THREAD

**Issue by cantaur3099** [openpmix/openpmix#1716]
Thank you for taking the time to submit an issue!

## Background information
I tried running a simple hello world command and this showed up after 2 rounds of execution:
PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
2.0.4

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source

### Please describe the system on which you are running
System: MacBook Air (11-inch, Early 2014)

* Operating system/version:macOS Mojave version 10.14.5
* Computer hardware: 
processor : 1.4 GHz Intel Core i5
Memory:4 GB 1600 MHz DDR3

-----------------------------

## Details of the problem
i tried running a simple helloworld code on my mac. The code was as follows:

#include "mpi.h"
#include <stdio.h>
int main(int argc, char *argv[])
{
MPI_Init(&argc,&argv);
printf("Hello World"); 
MPI_Finalize();
//return 0;
}

This code produced the following output:

[Gautams-MacBook-Air.local:35779] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
Hello WorldHello World[Gautams-MacBook-Air.local:35778] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

This error shows up every time i run mpi programs.

**Comment by karasevb** [comment]
https://github.com/openpmix/openpmix/pull/1584 this fix should helps

**Comment by cantaur3099** [comment]
thanks

**Comment by rhc54** [comment]
This has been fixed in v3.1 and above - v2.2 is no longer being supported, so I doubt we'll do another release just for this. We'll let folks know if that situation changes.
