### ISSUE TITLE
Segfault in dstore init

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1720]
Looks like we are consistently crashing in dstore_init on CentOS 6.10:

https://mtt.open-mpi.org/index.php?do_redir=3215

Not sure what is going on there as it seems we pass some times, but segfault others.

**Comment by karasevb** [comment]
I tried to reproduce with same version of CentOS, but to no avail. 
@rhc54 to get more details, it would be helpful to try the debug version of PMIx on this system.
Do you have any idea how to arrange this? May some contact who can assist to debug on this system.

**Comment by rhc54** [comment]
We aren't seeing this any more on Absoft - chalking it up to some strangeness over there
