### ISSUE TITLE
PMIx_Get of PMIX_RANK doesn't work

### ISSUE THREAD

**Issue by cpshereda** [openpmix/openpmix#1795]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master @ 949bab

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: N/A
* Network type: Single node (test suite)

-----------------------------

## Details of the problem

PMIx_Get of PMIX_RANK does not work (PMIx_Error_string outputs NOT-FOUND). In theory it should be possible to do something like the following:
```    
    job_proc = this_proc;
    job_proc.rank = PMIX_RANK_WILDCARD;
    PMIx_Get(&job_proc, PMIX_RANK, NULL, 0, &val);

```
This could be useful if we're inside some function where rank is not already known.

**Comment by rhc54** [comment]
Minor change - the Standard states that passing a rank of WILDCARD indicates a request for job-level info. It makes no sense to return the rank of a specific process from the job-level info. Instead, let's pass the INVALID rank to indicate that we don't know the rank. If the "get" sees its own nspace, an invalid rank, and a PMIX_RANK key - then we will return the rank of the process itself.
