### ISSUE TITLE
PMIX ERROR: NO-PERMISSIONS in file ../../../../../../src/mca/common/dstore/dstore_base.c at line 234

### ISSUE THREAD

**Issue by racedowling** [openpmix/openpmix#1819]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
bash$ mpiexec -V
mpiexec (OpenRTE) 3.1.3

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
apt-get install mpi4py
pip3 install mpi4py

### Please describe the system on which you are running

* Operating system/version: Raspbian Buster (Debian)
* Computer hardware: Raspberry Pi 4
* Network type: Ethernet

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

bash$ mpiexec /slurmfs/usr/bin/python3 calculate.py
pi is approximately 3.1418009868930938, error is 0.0002083333033007
[clust-1:10216] PMIX ERROR: NO-PERMISSIONS in file ../../../../../../src/mca/common/dstore/dstore_base.c at line 234

This happens every time mpiexec it is run.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ prun -np 2 ./hello_world
```

**Comment by jjhursey** [comment]
Sorry for the delay. We believe that this issue was fixed in [PMIx v2.2.4](https://github.com/openpmix/openpmix/releases/tag/v2.2.4). Open MPI 3.1.3 ships with PMIx 2.1.4.

You can try to update your Open MPI version through the package manager. Alternatively, you could build the latest Open MPI from source - the latest is [Open MPI v4.0.4](https://www.open-mpi.org/software/ompi/v4.0/)

**Comment by rhc54** [comment]
Closed as this looks to have been fixed.

**Comment by Twilight-Shuxin** [comment]
Hi, I am experiencing this same error here
```
PMIX ERROR: NO-PERMISSIONS in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c at line 237
PMIX ERROR: NO-PERMISSIONS in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c at line 237
```
I run this simple program (test.c)
```
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

int     myid, numprocs;

int main(int argc, char* argv[]) {

     int     ierr;
     ierr = MPI_Init(&argc, &argv);
     ierr = MPI_Comm_rank(MPI_COMM_WORLD, &myid);
     ierr = MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
     ierr = MPI_Finalize();

     exit(0);
}
```
through command
`mpicc test.c -o a.out`
`mpirun -np 2 a.out`
and this error occurs.
My mpiexec version is mpiexec (OpenRTE) 4.1.5.
I do not know how to debug this problem. May anyone kindly help me with this issue or has any ideas? Thanks!

**Comment by Twilight-Shuxin** [comment]
> You should report this over in OpenMPI - I don't know what version of PMIx they are using in that release, but I suspect it is old enough to fall outside our support window. You might ask them how to update to something more recent.

I see, I didn't realize this is already a very old version, only that it is higher than the one suggested above.
Thanks for the suggestion! I'll try to upgrade my software.
