### ISSUE TITLE
pkg-config file typo for library name

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#1826]
Thank you for taking the time to submit an issue!

## Background information

pkg-config spec file has a typo

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ 8a03e57f9f67e5343a797f970b9d1fafc0d34383

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### Please describe the system on which you are running

* Operating system/version: Fedora 32
* Computer hardware: x86
* Network type: N/A

-----------------------------

## Details of the problem

The maint/pmix.pc.in file has "-pmix" instead of "-lpmix"

**Comment by rhc54** [comment]
Thanks @tonycurtis ! I really appreciate you reporting these things!
