### ISSUE TITLE
PMIx_Get is broken for reserved keys

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1836]
There is a break in compatibility when testing cross-version that eventually led to a root cause in the master (and now v3.2) branch. In accordance with the Standard, we no longer go to the server when looking for "reserved" keys (i.e., keys that start with "pmix"). Unfortunately, v3.x servers don't store the node array information in the dstore component because that component still doesn't know how to deal with such info. Instead, per the comment in dstore_base in that series, we rely on the hash component to provide node-level information - which can only work if the client goes up to the server to get it.

We need to update the logic in master (and then backport to v3.2) so it knows that it still has to go up to the server to request reserved keys if they aren't found in the dstore. This violates the Standard, but until we can get a shmem component that properly handles node, app, and session-level info, we have no choice.

**Comment by rhc54** [comment]
I have come up with a stop-gap solution until we can create a new shmem implementation. We take the node-info array and store it in the dstore using a key "pmix.narray:\<nodename\>". When someone looks for a piece of node-level info, we create the proper key from the nodename, look it up in the "fastpath", and then scan the returned array for the key they requested. Ditto for app and session-level info.

The negative here is that the key is a fixed-length array, so it is possible (albeit unlikely) that we will overrun it. In this case, we will just truncate the nodename and hope it remains unique. Probably good enough for the moment, and the best we can do under the circumstances. Also requires we be able to pack/unpack node, app, and session info arrays, but that isn't too bad.

I'll try to code this up for v4 - we can debate bringing it back to v3.2 though I'm inclined not to do so.

**Comment by jjhursey** [comment]
Interesting bug. Did the cross-version CI checker get tripped on this or did you find it manually?

I'll make sure that we discuss this on the teleconf this week. It sounds like your stop-gap solution might work for the short term. We should ping folks about https://github.com/openpmix/openpmix/issues/1567 to see if anything is happening there.

**Comment by rhc54** [comment]
Yeah, it initially tripped over it and then I had to dig down for a bit to find it. Sadly, it would have immediately failed if we were actually running on more than one node as "resolve_peers" today can only return info on the current node.
