### ISSUE TITLE
3.2 include/pmix_common.h.in missing FABRIC defs

### ISSUE THREAD

**Issue by pkovacs** [openpmix/openpmix#1891]
If `libpsm2` is installed on the build system, pmix will configure for building the `src/mca/pnet/opa/` units.   The problem is that there are FABRIC references in `pnet_opa.c` that are not defined in `include/pmix_common.h`.  Either `pmix_common.h` is too far behind for this version or `pnet_opa.c` is too far ahead.  I note the FABRIC defs are in master, but not 3.2.0.

Easy to reproduce -- install `libpsm2`, configure pmix 3.2.0 and build: 

```
In file included from pnet_opa.c:34:
pnet_opa.c: In function 'allocate':
pnet_opa.c:176:45: error: 'PMIX_ALLOC_FABRIC' undeclared (first use in this function); did you mean 'PMIX_ALLOC_ID'?
  176 |         } else if (PMIX_CHECK_KEY(&info[n], PMIX_ALLOC_FABRIC)) {
      |                                             ^~~~~~~~~~~~~~~~~
/home/phil/pmix/pmix-3.2.0/include/pmix_common.h:1032:30: note: in definition of macro 'PMIX_CHECK_KEY'
 1032 |     (0 == strncmp((a)->key, (b), PMIX_MAX_KEYLEN))
      |                              ^
pnet_opa.c:176:45: note: each undeclared identifier is reported only once for each function it appears in
  176 |         } else if (PMIX_CHECK_KEY(&info[n], PMIX_ALLOC_FABRIC)) {
      |                                             ^~~~~~~~~~~~~~~~~
/home/phil/pmix/pmix-3.2.0/include/pmix_common.h:1032:30: note: in definition of macro 'PMIX_CHECK_KEY'
 1032 |     (0 == strncmp((a)->key, (b), PMIX_MAX_KEYLEN))
      |                              ^
pnet_opa.c:180:46: error: 'PMIX_ALLOC_FABRIC_SEC_KEY' undeclared (first use in this function); did you mean 'PMIX_ALLOC_NETWORK_SEC_KEY'?
  180 |                 if (PMIX_CHECK_KEY(&iptr[p], PMIX_ALLOC_FABRIC_SEC_KEY)) {
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/phil/pmix/pmix-3.2.0/include/pmix_common.h:1032:30: note: in definition of macro 'PMIX_CHECK_KEY'
 1032 |     (0 == strncmp((a)->key, (b), PMIX_MAX_KEYLEN))
      |                              ^
pnet_opa.c:182:53: error: 'PMIX_ALLOC_FABRIC_ID' undeclared (first use in this function); did you mean 'PMIX_ALLOC_NETWORK_ID'?
  182 |                 } else if (PMIX_CHECK_KEY(&iptr[p], PMIX_ALLOC_FABRIC_ID)) {
      |                                                     ^~~~~~~~~~~~~~~~~~~~
/home/phil/pmix/pmix-3.2.0/include/pmix_common.h:1032:30: note: in definition of macro 'PMIX_CHECK_KEY'
 1032 |     (0 == strncmp((a)->key, (b), PMIX_MAX_KEYLEN))
      |                              ^
make[2]: *** [Makefile:769: pnet_opa.lo] Error 1
```

**Comment by rhc54** [comment]
Sigh - that component shouldn't have been included in the release. I'll do a scrub. I'm afraid 3.2.0 got out without my having time to thoroughly comb it. My apologies.

**Comment by pkovacs** [comment]
@rhc54 No worries!  I'm always happy to help.

**Comment by jjhursey** [comment]
@rhc54 when I sync'ed the v3.2 branch from master I must have picked up these names changes, but since I didn't have the required libraries I must have missed this. Sorry about that. We will fix it in the v3.2.1rc1.

From that sync here is the diff of the pnet/opa changes:
 * https://github.com/openpmix/openpmix/pull/1832/files#diff-c8bafdab1c65bdd7a308434a3cbd915ce3145ac751e8ec4baa306359362121c5

I could revert that patch, but I'm hesitant to do so without access to a system to build against. Do you have access to such a system to try it out?

**Comment by rhc54** [comment]
No need - I simply removed those components as they aren't active in v3.2 anyway.

**Comment by jjhursey** [comment]
These were removed in https://github.com/openpmix/openpmix/pull/1890

**Comment by jjhursey** [comment]
@pkovacs We just rolled a [v3.2.1rc1](https://github.com/openpmix/openpmix/releases/tag/v3.2.1rc1) with this fix. Can you give it a try to confirm that this issue is closed and that it works for you? Thanks!

**Comment by pkovacs** [comment]
@jjhursey it's good on all six Fedora arches -- I've committed it to Fedora rawhide: https://src.fedoraproject.org/rpms/pmix

Thanks to you and @rhc54 for helping out with these two issues.  Sorry I didn't catch them earlier.  The rc's mostly fly under my radar unless I see a compelling reason to use them.

**Comment by jjhursey** [comment]
No problem. Thanks for testing and reporting those issues. Sorry that we missed those when preparing v3.2.0. We probably should have given a better heads up to folks about how we updated that branch and the need for more testing eyes.
