### ISSUE TITLE
pmix.spec missing in 1.2.5 distribution tarballs

### ISSUE THREAD

**Issue by nvonwolf** [openpmix/openpmix#1934]
## Background information
I'm attempting to make an RPM of the 1.2.5 release (latest of the 1.x branch).  I have successfully done this for the 2.x and 3.x latest releases.

### What version of the PMIx Reference Library are you using? 
1.2.5

### Describe how PMIx was installed 
[distribution bz2 tarball](https://github.com/openpmix/openpmix/releases/tag/v1.2.5)

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: Virtual Machine
* Network type: Private Network with NAT for internet

-----------------------------

## Details of the problem

I am trying to produce a RPM file that installs PMIX to '/opt'.  I have done so with newer versions but the 1.x versions seem to be missing the required files even though they exist in the source downloads.  Specifically the 'contrib/pmix.spec' is missing from the distribution tarballs.

```shell
# works
rpmbuild -v --define 'install_in_opt 1' -ta pmix-3.2.1.tar.bz2 | tee build3.out
rpmbuild -v --define 'install_in_opt 1' -ta pmix-2.2.4.tar.bz2 | tee build2.out

# does not work
rpmbuild -v --define 'install_in_opt 1' -ta pmix-1.2.5.tar.bz2 | tee build1.out
```

I also tried building directly from the source files since it has all the required files but I receive a different error.
```shell
wget https://github.com/openpmix/openpmix/archive/v1.2.5.zip
unzip v1.2.5.zip
cd openpmix-1.2.5
rpmbuild --define 'install_in_opt 1' --define '_disable_debug --disable-debug' -bb contrib/pmix.spec | tee build1.out
```
produces "error: line 195: Illegal char '$' in: Version: $VERSION"

**Comment by rhc54** [comment]
You should be able to use the spec file from any of those other tarballs - it hasn't changed in quite a while. Have you tried that?

**Comment by nvonwolf** [comment]
I was able to get a successful build by downloading the source zip and using the spec file from there while placing the distribution tarball (.bz2) in '~/rpmbuilds/SOURCE/'.

If the 1.x branch is still supported it should be worth fixing the distribution tarball (.bz2).

**Comment by rhc54** [comment]
I'm going to close this as we aren't supporting the 1.x branch any more and there is a workaround.
