### ISSUE TITLE
Things to do for v4.0

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1938]
- [ ] Update tool support
     - [x] Complete/debug new attachment APIs
     - [x] Update debugger examples
     - [ ] Update mpir_shim
&nbsp;
&nbsp;

- [ ] Repair/update Python bindings
     - [x] Add missing APIs and datatypes
     - [x] Fix threadshift support
&nbsp;
&nbsp;

- [ ] Implement new shmem model
  - [ ] This has been moved to v4.1 - Ref https://github.com/openpmix/openpmix/issues/1836

**Comment by jjhursey** [comment]
In PR #1944 I added the missing functions that I could find. There might be more, but that is a start.

**Comment by jjhursey** [comment]
Most of these items made it for v4.0.0. A few are being worked on for v4.0.1 - moving the milestone.
