### ISSUE TITLE
pmix4.0.0: no python

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#1996]
This is with pmix 4.0.0

Debian Unstable / Ubuntu latest

The file `config/pmix_check_cython.py` contains:
```
#!/usr/bin/env python
```

As of now, python2 has passed EOL and is not supported in Debian and many other places. python is presumed to be python3, and this code works with python3, but the link python->python3 is not present. (This is distro-specific).

I recommend that python is changed to python3.

**Comment by rhc54** [comment]
Sounds good - I'd caught it everywhere else, but missed this one.

**Comment by jjhursey** [comment]
This was fixed in PR #1998 (for `v4.0`) and PR #1997 (for `master`)
