### ISSUE TITLE
Advice: recommended params for a generic setup

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#2015]
So, this is a request for advice rather than a bug report.

I'm a maintainer of the MPI stack in Debian, so : OpenMPI is the default MPI (we also ship mpich), but also pmix, ucx, etc.

Increasingly it makes sense to build the MPI versions of apps by default, but as a generic distro we cannot assume
Infiniband is present/used on our systems; now with UCX we get:

```
root@debian:/openmpi-4.1.0/debian/tests# mpirun  -n 2 ./hello
[1610465245.269420] [debian:800759:0]      rdmacm_cm.c:638  UCX  ERROR rdma_create_event_channel failed: No such device
[1610465245.349752] [debian:800759:0]     ucp_worker.c:1432 UCX  ERROR failed to open CM on component rdmacm with status Input/output error
[debian:800759] ../../../../../../ompi/mca/pml/ucx/pml_ucx.c:273  Error: Failed to create UCP worker
[1610465245.414575] [debian:800757:0]      rdmacm_cm.c:638  UCX  ERROR rdma_create_event_channel failed: No such device
[1610465245.414624] [debian:800757:0]     ucp_worker.c:1432 UCX  ERROR failed to open CM on component rdmacm with status Input/output error
[debian:800757] ../../../../../../ompi/mca/pml/ucx/pml_ucx.c:273  Error: Failed to create UCP worker
 node           1 : Hello world
 node           0 : Hello world
```

The problem is: OpenIB and UCX warnings are likely to both annoy users and also break test suites when run on plain multicore/ethernet systems.
We can ship with warnings silenced, eg ` /etc/openmpi/openmpi-mca-params.conf' has:
```
## 
btl_base_warn_component_unused=0
# Avoid openib in case applications use fork: see https://github.com/ofiwg/libfabric/issues/6332
# If you wish to use openib and know your application is safe, remove the following:
btl_base_exclude=openib
```
So, should I add another exclude for ucx , and leave it to cluster admins to enable in the conf file ?

**Comment by rhc54** [comment]
This really should go over to the OMPI folks

**Comment by rhc54** [comment]
Afraid I cannot transfer it for you as they are in a different project. Can you reopen it there

**Comment by jjhursey** [comment]
https://github.com/open-mpi/ompi/issues/8367 is the Open MPI version of this issue. I'll close this one and folks can comment over there.
