### ISSUE TITLE
Suggestion: Improved error messages for multiple --map-by directives in command

### ISSUE THREAD

**Issue by drwootton** [openpmix/openpmix#2035]
### What version of the PMIx Reference Library are you using? 

Current PMIx source master branch head.

### Describe how PMIx was installed 

Built from current github source

### Please describe the system on which you are running

* Operating system/version:
RHEL 7.6
* Computer hardware:
Power 9 node with 22 cores/176 threads
* Network type:
localhost

-----------------------------

## Details of the problem

I was working on getting rankfile support working again for prterun and noticed that if I specified multiple **--map-by directives**, for instance **--map-by core:rankfile:rankfile1, --map-by rankfile:rankfile1:core, or --map-by core:hwthread** that is diagnosed as an invalid modifier with the whole --map-by parameter string flagged as the modifier.

The code that handles this is in rmaps_base_frame.c where currently there is some processing for the ppr directive, then check_modifiers is called, which is where the message is issued, and finally there is processing for the modifiers. 

Maybe processing can be re-ordered so a clearer error message, flagging the problem as multiple directives, can be issued.

**Comment by jjhursey** [comment]
This is really a PRRTE not an OpenPMIx issue. Moved to the PRRTE project https://github.com/openpmix/prrte/issues/862
