### ISSUE TITLE
Q: node topology information at startup

### ISSUE THREAD

**Issue by angainor** [openpmix/openpmix#2036]
This question is maybe also related to `hwloc`, not strictly to PMIx. I noticed that on our AMD EPYC 7742 cluster it takes around 3-4 seconds to execute `hwloc_topology_load`. So I was wondering - is it possible to speed up the startup by the "instant on" feature somehow? If so, is it possible for the MPI application to get access to the `hwloc_topology_t` data used by PMIx? Or maybe there is some optimization I could use for `hwloc`?

**Comment by angainor** [comment]
@rhc54 Actually, the time to execute `hwloc_topology_load` grows to ~9s if I start 128 ranks per compute node, and ~22s if I use the hyperthreads and start 256 ranks, and they all do it at the same time. I'm now talking about explicit call to `hwloc_topology_load` in my code, but it seems that it takes OMPI a very similar amount of time to complete `MPI_Init`. I guess for such large systems it starts to show..

**Comment by rhc54** [comment]
What version of OMPI and hwloc are you using? We addressed this a few years ago when we started observing similar behavior on KNL. Starting with OMPI v3.1, if you launch via `mpirun`, the local daemon will do the topology discovery and provide the results to each proc in a shared memory region.

Of course, if you launch via something like `srun`, I'm afraid you are on your own 🤷‍♂️ as Slurm doesn't provide that support.

**Comment by angainor** [comment]
@rhc54 Thanks! I run with OpenMPI 4.0.5, compiled against external hwloc 2.4.0.

I have now tried with `-mca coll_hcoll_enable 0` and the time of `MPI_Init` dropped to 8s (from 20s), so it seems that at least part of the overhead is gone.

It seems that `hwloc_topology_load` (and also `MPI_Init`) take no time if I only start one rank. I guess then that exporting the topology to shared memory would be a solution then. Do you happen to know if some kind of serialization is supported by `hwloc`? Or should I ask in their repo?

**Comment by rhc54** [comment]
> with -mca coll_hcoll_enable 0 and the time of MPI_Init dropped 

Okay, that pinpointed the problem. Afraid you will need to take this up with Mellanox/Nvidia. I've been dealing with this issue with other packages as well - making a little progress, though it is difficult to get the message across about scalable launch.

The problem is that their hcoll package is directly loading the hwloc topology itself instead of first checking via PMIx to see if it is already available in shared memory. This forces every proc to do a `hwloc_topology_load` and is why you are seeing that behavior. I'm afraid the only solution is to get them to (a) first check to see if hwloc is in shmem (a simple call to PMIx answers that one) and then (b) do the load only if it isn't.

**Comment by angainor** [comment]
@rhc54 Many thanks for the hint about shared memory export! This will solve my current issue :) I'll try to complain to Mellanox..

**Comment by jladd-mlnx** [comment]
What version of HCOLL are you using? We removed the HWLOC dependency looooong ago. Our startup time with HCOLL enabled is fast and scalable on the node architecture you describe. HCOLL runs in production in Azure HPC cloud and we are highly sensitive to startup time. You're hitting something else.

**Comment by jladd-mlnx** [comment]
And HCOLL is the default collectives backend for SpectrumMPI on the CORAL systems. We saw and fixed the issue way back on Power9 bring up circa 2017. (P9 has 176 threads per node)

**Comment by angainor** [comment]
@jladd-mlnx I'm running the newest HPCX 2.7, OpenMPI 4.0.5, so ~ up to date. I've done some startup tests with a hello-world application (only `MPI_Init` and `MPI_Finalize`) on this AMD. Here is a table summarizing `time mpirun -np <N> -mca coll_hcoll_enable <B> -map-by hwthread -bind-to hwthread ./mpihello`:

```
ranks   no HCOLL        HCOLL
8        0.404s	        0.653s
16       0.587s         1.007s
32       1.069s         1.866s
64	 1.116s         2.196s
128	 3.551s         7.636s
256	10.114s         22.703s
```
These are reproducible, although some nodes have times slightly different than others. IMO this shows some in-node scalability issues for large number of ranks. OpenMPI also seems to have this problem, and HCOLL is adding another layer on top of that. Granted, I use the HyperThreads in this case, but that is to demonstrate the issue. For example, if I run 128 ranks and bind to cores (`-map-by core -bind-to core`), then the time is 6s with HCOLL (instead of 7.6).

If I go to multiple nodes (with full 256 ranks per node):
```
ranks   no HCOLL        HCOLL
2 nodes  8.430s        23.183s
4 nodes  8.726s        33.243s
8 nodes  9.066s        --- ([LOG_CAT_MCAST] MCAST rank=3: Error in initializing vmc communicator
                            [LOG_CAT_P2P] Failed to create MCAST comm)
```
Here OpenMPI seems to scale well with increasing number of nodes (at least 8), while HCOLL struggles with 4, and refuses to run at 8 (I think OpenMPI falls back to not using HCOLL in that case?). Of course, I can start 1k-node jobs with HCOLL if I run 128 ranks per node (so no hyperthreading, `-bind-to core`).

**Comment by angainor** [comment]
@jladd-mlnx Do you think this might be something with the system setup? From what you said I understand that this should not be the case. Can I do something to debug it?

**Comment by angainor** [comment]
@rhc54 btw. I implemented your suggestion with shared-memory export of hwloc topology in my code, and it works very well. This part of the code now takes a fraction of a second on 256 ranks/node, so that is definitely not a problem.

**Comment by rhc54** [comment]
Kewl! Just to be clear: your code is calling PMIx to get the shmem "hooks" for the topology, and then call `hwloc_shmem_topology_adopt` to attach to it?

FWIW: in PMIx v4 we made it even easier - you can just use PMIx_Get to retrieve a pointer to the root of the topology tree, so you no longer have to do anything extra. We'll check for the shmem hooks and use them if available - if not, then we'll go ahead and call `hwloc_topology_load` under the covers.

**Comment by jladd-mlnx** [comment]
Try adding the following to your cmd line:
`-x HCOLL_ENABLE_MCAST_ALL=0`

**Comment by jladd-mlnx** [comment]
Looks like the multicast group creation isn't playing nice on your setup.

**Comment by angainor** [comment]
> Kewl! Just to be clear: your code is calling PMIx to get the shmem "hooks" for the topology, and then call `hwloc_shmem_topology_adopt` to attach to it?

@rhc54 Well, no - I didn't get so far yet :) I will, but for now a single rank per node gets the topo using `hwloc_topology_load`, saves it using `hwloc_shmem_topology_write`, and then others use `hwloc_shmem_topology_adopt`. But getting it from PMIx would be a natural next step!

> FWIW: in PMIx v4 we made it even easier - you can just use PMIx_Get to retrieve a pointer to the root of the topology tree, so you no longer have to do anything extra. We'll check for the shmem hooks and use them if available - if not, then we'll go ahead and call `hwloc_topology_load` under the covers.

That's even better :) Now I had to implement the entire shmem attachment myself. I was actually looking at the `find_hole` in OpenMPI, but it seemed to be a bit of an overkill. I attached without the memory address on the master rank, then broadcasted that address to all other ranks. If they fail to attach, I do what you said - `hwloc_topology_load`. Most of the time the address is fine though.

**Comment by jladd-mlnx** [comment]
But what is the time to launch?

**Comment by angainor** [comment]
@jladd-mlnx I did not disable the multicast. Now on 8 nodes the startup time with HCOLL is 34s. If I disable multicast the time is the same. I run like this:
```
time mpirun  -x HCOLL_ENABLE_MCAST_ALL=0 -x LD_LIBRARY_PATH -H b3301:256,b3302:256,b3303:256,b3304:256,b3305:256,b3306:256,b3307:256,b3308:256 --oversubscribe -mca coll_hcoll_enable 1 -x UCX_LOG_LEVEL=ERROR -map-by hwthread -bind-to hwthread -np 1024 ./mpihello
```

**Comment by angainor** [comment]
@jladd-mlnx I must be missing something here. I made a mistake in the line above: only 4 nodes were used (I started 1024 ranks). If I start 2048 ranks, the time is 11s with HCOLL, and 9.7s without it. Something here is definitely not right.

**Comment by angainor** [comment]
btw, I do look at htop on one of the nodes - all cores / HT are used.

**Comment by rhc54** [comment]
@angainor I've posted an FAQ entry addressing how to access the HWLOC shmem region - see https://openpmix.github.io/support/faq/avoid-hwloc-dup. Includes new envars for doing it without introducing a direct PMIx dependency for those cases (e.g., a lower-level lib like hcoll) that wish to avoid doing so.

**Comment by vspetrov** [comment]
> Kewl! Just to be clear: your code is calling PMIx to get the shmem "hooks" for the topology, and then call `hwloc_shmem_topology_adopt` to attach to it?
> 
> FWIW: in PMIx v4 we made it even easier - you can just use PMIx_Get to retrieve a pointer to the root of the topology tree, so you no longer have to do anything extra. We'll check for the shmem hooks and use them if available - if not, then we'll go ahead and call `hwloc_topology_load` under the covers.

@rhc54 what is the PMIx_Get call i should use to load topo from shmem, is there an example snippet?

**Comment by jjhursey** [comment]
@vspetrov There is an "Accessing the HWLOC topology tree from clients" snippet on the [FAQ](https://openpmix.github.io/support/faq/avoid-hwloc-dup) entry that Ralph wrote that shows the `PMIx_Get` call to access the shared memory topology segment. Take a look and let us know if any more details need to be added to that entry.

**Comment by rhc54** [comment]
Please reopen if there are any more questions on this topic.
