### ISSUE TITLE
Atomics broken under Clang

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#2050]
Tip of master when brought over to OMPI:

/home/ubuntu/workspace/open-mpi.build.compilers/Compiler/clang38/src/3rd-party/openpmix/src/atomics/sys/atomic_stdc.h:250:5: error: member reference base type 'volatile void' is not a structure or union
    atomic_flag_clear ((volatile void *) lock);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/stdatomic.h:181:63: note: expanded from macro 'atomic_flag_clear'
#define atomic_flag_clear(object) __c11_atomic_store(&(object)->_Value, 0, __ATOMIC_SEQ_CST)

**Comment by awlauria** [comment]
Ugh. I'll Pr a change shortly. Thanks.

**Comment by awlauria** [comment]
Sorry about that, oversight on my part. I tacked on these volatile void * changes and thought it was innocent enough to not need to do a full recompile with clang after I got past the other C11 junk.

This is humming along with Clang version 9.0.1. also recompiling with PGI to double check I didn't break it.

**Comment by rhc54** [comment]
Thanks Austen! Much appreciated.

**Comment by awlauria** [comment]
Thanks for the heads-up. Verified that PGI didn't throw any additional warnings, hopefully this settles it.
