### ISSUE TITLE
Need thorough memory leak scrub of v4.0.x and master branches

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#2092]
Reports of memory leaks from RMs in both server and client sides

**Comment by jjhursey** [comment]
On the weekly teleconf @awlauria said that he might have some cycles to help here.

**Comment by awlauria** [comment]
This fixed three leaks:

https://github.com/openpmix/openpmix/pull/2103

Last I ran, make check didn't show anything that large as leaking. There were a couple that were shrouded by ?? in the stack trace, making them very difficult to track, but even those weren't that large. I'll keep pushing at it though to chase down any large ones.

**Comment by jjhursey** [comment]
Per March 25, 2021:
 * After PR #2103 there are only small leaks left.
 * Will do some more looking to pick up a few more of those. Feeling is that this is much better than when it was filed.
