### ISSUE TITLE
Tons of shadow and GNU extension warnings out of dstore code

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#2116]
Getting a bunch of these from the v4.0 branch. Should be cleaned up prior to release, methinks. I took a first pass at it but must have gotten something not-quite-right as it segfaults. I checkpointed it here: https://github.com/rhc54/openpmix/tree/cmr40/shad if anyone wants to pick it up.

**Comment by jjhursey** [comment]
Notes from March 25, 2021 Teleconf:
 * This really should be cleaned up before release.
 * There might be another way to handle the macros with the `__pmix_attribute_extension__` extension, but the community would like the solution to be simple and clear (whatever it might be) for future maintenance.

**Comment by rhc54** [comment]
Fixed in v4.1
