### ISSUE TITLE
PMIx_tool_init issues epoll error message with PRRTE indirect example

### ISSUE THREAD

**Issue by drwootton** [openpmix/openpmix#2140]
### What version of the PMIx Reference Library are you using? 
Current PMIx master repository head

### Describe how PMIx was installed 
Source build

### Please describe the system on which you are running

* Operating system/version:
RHEL 7.6

* Computer hardware:
Power 9 node, 22 core/188 thread

* Network type:
Single node, localhost

-----------------------------

## Details of the problem

When I run the PRRTE indirect example testcase as **indirect prterun -n 2 hello 10** the daemon that is part of the PRRTE debugger examples source displays a message 
~~~
[warn] Epoll ADD(1) on fd 15 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Bad file descriptor
~~~ 
This message is issued by libevent during the call from PMIx_tool_init.

I see this consistently with the indirect example but with none of the other examples. I looked at how the daemon is launched by PMIx_Spawn in each example and I don't see what is different with indirect.

This occurs with the system libevent version 2.0.21-4 as well as a libevent 2.1 biuilt by @jjhursey 

Other than this message, the indirect example seems to run ok.

**Comment by jjhursey** [comment]
I wonder if this is related to switching the servers with `PMIx_tool_set_server`. Maybe an old file descriptor needs to be cleared.

**Comment by rhc54** [comment]
Could be related, but I couldn't reproduce on the Mac. Will try on the Linux container.
