### ISSUE TITLE
OpenPMIx Tracing/Profiling Extension

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#2166]
In the past, I have been asked if OpenPMIx has a 'profiling' interface as MPI does. Their intention was to use the interface to add a tracing interposition library to see which PMix calls were being made with which attributes/directives. They could use this library to either:
 1. Better understand how a library or set of libraries are using PMIx. Also to confirm that they are using how they expect.
 2. Add some debugging to help diagnose an issue they are seeing in the wild

I think that this would be a useful thing to have in OpenPMIx, and probably won't be too much work since the API is relatively small.

**Comment by rhc54** [comment]
Probably not something that will happen as I don't sense anyone is really interested, at least at this time.
