### ISSUE TITLE
hwloc 2.1.0 bug with OpenPMIx

### ISSUE THREAD

**Issue by RaymondMichael** [openpmix/openpmix#2173]
We weren't able to get OpenPMIx to work on SLES 15sp2. We tracked this down to hwloc 2.0.0 in sp1 and hwloc 2.1.0 in sp2.

The bug manifests in ploc_hwloc.c:pack_topology(). At the start of the function it calls strcasecmp(src->source, "hwloc"). It appears that hwloc 2.1.0 gives us a "hwloc 2.1.0" string instead of a "hwloc" string, so this call fails. Changing to strncasecmp(src->source, "hwloc", 5) makes everything work.

**Comment by rhc54** [comment]
Sigh...I was unaware Brice was making that change. Thanks for the heads-up and the fix!
