### ISSUE TITLE
Gracefully fail if one PMIx peer has libz and the other does not

### ISSUE THREAD

**Issue by jsquyres** [openpmix/openpmix#2176]
Per https://github.com/open-mpi/ompi/issues/8803, it took a while to figure out that the reason a user's `mpirun --host a,b hostname` was failing was because one node's Open MPI v4.x `orted` had libz in its PMIx and the other node's `orted` did *not* have libz.  This caused PMIx to issue an amorphous error and fail to connect.

It would be good if PMIx could detect this kind of situation and at least gracefully fail (e.g., emit an error message saying "one side is libz and the other is not -- I can't handle this, so I'm going to abort.").

It would actually be awesome if both sides could negotiate to not use compression in this case, but I'm guessing that would be a big ask.

**Comment by rhc54** [comment]
Actually, this report isn't correct. OMPI v4 doesn't use PMIx for compression/decompress - it uses ORTE for that purpose. So the problem really is that the backend `orted` lacks OPALs libz support and therefore unpacks the launch msg incorrectly and aborts. It connects to `mpirun` just fine as that doesn't involve compression.

OMPI master, on the other hand, _does_ use PMIx for compress/decompress. The resulting symptom is the same - the `prted` cannot decompress the launch msg and therefore aborts. Again, connection is just fine.

**Comment by rhc54** [comment]
Bottom line is that this is really an OMPI issue for v4.x, and a PRRTE issue for OMPI v5 and master. Nothing to do with PMIx. We can leave it here, though.

**Comment by rhc54** [comment]
Fixes posted for both OMPI v4.1 and PRRTE v2.0.
