### ISSUE TITLE
Compile: gcc11 emits warning message about PMIx_Get

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#2182]
## Background information

Compiling pmix 3.2.3 or github version gives compiler warning

### What version of the PMIx Reference Library are you using? 

3.2.3 or HEAD b1908ff8af675754f020add90bbabe4de89c3c6f

### Describe how PMIx was installed 

tarball or clone

### Please describe the system on which you are running

* Operating system/version: CentOS 8
* Computer hardware: aarch64
* Network type: IBV

-----------------------------

## Details of the problem

```.../src/osss-ucx/build/../bitbucket.org/src/shmemc/ucx/pmix_client.c:359:10: warning: ‘PMIx_Get’ reading 512 bytes from a region of size 14 [-Wstringop-overread]
  359 |     ps = PMIx_Get(&wc_pmix, PMIX_JOB_SIZE, NULL, 0, &vp);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../src/osss-ucx/build/../bitbucket.org/src/shmemc/ucx/pmix_client.c: In function ‘shmemc_pmi_client_init’:
.../src/osss-ucx/build/../bitbucket.org/src/shmemc/ucx/pmix_client.c:359:10: note: referencing argument 2 of type ‘const char *’
```

Looks like a type mismatch between definition of PMIx_Get in src/client and in the include file?  Or is this GCC complaining about something it shouldn't?

**Comment by rhc54** [comment]
Thanks @tonycurtis  - we updated the non-blocking version, but missed this one. Sigh.
