### ISSUE TITLE
Revisit shared memory support

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#2184]
The `dstore` has served us well for years, but changing requirements dictate that we take a second look at how we support a shared memory store. Note that this doesn't mean we abandon the current code - it may well be that some modification of it can take us where we want to go. This issue is simply being filed to track (a) the requirements we need to meet, and (b) discussions on possible solutions.

See https://github.com/openpmix/openpmix/pull/1884 for some preliminary thoughts on this.

First, it's important to remember that this is a "one-writer/many-reader" scenario. Only the PMIx server is allowed to modify the shmem data. However, many local clients can and will access that data. We would like for that access to be "transparent" - i.e., we want the client to be able to reference data via a simple memory lookup as opposed to generating a copy of the data into the client's local memory space.

It is relatively straightforward to achieve the second requirement when referencing simple values (e.g., int or float). However, PMIx routinely shares complex structures that contain pointers to other data fields that themselves could be complex structures. The most common example of this is the sharing of a `pmix_data_array_t` object consisting of an array of complex structures, each containing malloc'd pointers to other structures or data arrays.

There are two primary sources of data that PMIx servers need to share with their local clients:

* job-level data that is generated by the system and given to the procs at startup. The data consists of things like where each proc is located, how many procs are in the job, what resources have been assigned to those procs, etc. This data is pretty much static - it would change, for example, in a fault tolerant scenario where a failed process might be restarted (or replaced) in a different location. In the case of "instant on", this will include endpoint information for each process.

* modex data. In the case where "instant on" is not supported, procs will generate and post their own endpoint information, which is subsequently circulated during the `PMIx_Fence` operation. At the end of that operation, each daemon has a complete collection of the endpoint information for all procs in the job - this data must be made available to the server's local clients via a shmem region.

The timing of data creation and retrieval varies depending on the host RM and the application. The PMIx Standard allows a host to register information in a non-blocking manner, and therefore it is possible (though not generally done) for the host to load job-level data into the system in parallel with spawning the local clients. If someone really did this, it might cause us some difficulty since the PMIx server has to provide several envars to each client at spawn - and I'm not sure all those envars can be generated without the complete job-level data. This is something we could check and might require clarification in the Standard.

Regardless, it would be desirable if the job-level information could be stored prior to spawning local clients. Clients aren't required to call `PMIx_Init` at the beginning of their execution (or at any specific time, really), and so the "lazy init" scenario described by @artpol84 in the discussion (where clients may initialize PMIx at very different times) must be considered in the design.

In contrast, modex information (where used) cannot be pre-loaded as it must be generated by the application itself. Thus, modex information will always become available only after the procs have been spawned and have completed `PMIx_Init`.  We do have the ability to "piggy-back" on the Fence operation by adding info from each process to the exchange for our own purposes. Thus, we could include (for example) data such as where "holes" in virtual address space exist. However, note that information such as this would only be true at the instant the Fence operation was invoked - since the Fence can (and  often does) take place in the background, there is no guarantee at completion of Fence that the application hasn't done something in the interim that would impact that information.

Although it may not seem intuitive, data retrieval must be fast. This isn't as critical for traditional HPC "bulk synchronous" jobs, but we are seeing growing use of workflow methods and hybrid applications (think data analytics with MPI backend) involving thousands of short-lived jobs. In these cases, jobs typically are relatively small (e.g., a few hundred processes) and short-lived (on the order of minutes). Launch/init time, therefore, is increasingly an issue. Prior work by @artpol84 et al have illustrated the impact of these times, and the dstore is very good in this regard. We don't want to lose any of that capability in the revision.

Please add thoughts and further requirements below. This is meant as a place to capture discussion, so nothing is off the table or cast in concrete.

**Comment by artpol84** [comment]
Thank you for the great summary!
I'd like to point @samuelkgutierrez to few informational sources that might be  useful to ramp up:
* Our 2019 EuroMPI paper "A performance analysis and optimization of PMIx-based HPC software stacks" contains some useful insights [[PPTX](https://pmix.github.io/uploads/2019/09/2019_EMPI_Polyakov_PMIx_v5.pptx)], [[Paper](https://dl.acm.org/doi/10.1145/3343211.3343220)] (@samuelkgutierrez let me know if you need me to send you PDF)
* PMIx SC BoF'16 (slides 15-20) [[Slideshare](https://www.slideshare.net/rcastain/sc16-pmix-bof-presentation)]

**Comment by artpol84** [comment]
**dstor limitations**:
* Support for direct pointers in the shmem region:
  * Should be easy to extend it to support trivial data types like int, float, etc.
  * Complex datatypes have following limitations
    * Either require "Access Macro" that would perform needed translations. This would break backward compat & introduce additional overhead on the data path
    * Allocation of the per-process intermediate structures (arrays) with adjusted pointers. This partially defeats the purpose of the shared memory as a way to save storage space.
* Support for multiple "scopes" like Job-level, node-level, app-level user-level information. Currently, dstor only supports job- and user-level information scopes. Newer PMIx versions introduced node- and app-level scopes that are not easy to fit into the dstor architecture.

@rhc54 was there anything else that caused the need for those workarounds?

**Comment by rhc54** [comment]
No, that is a good accurate summary - thx!

**Comment by samuelkgutierrez** [comment]
Thank you @rhc54 and @artpol84 for the nice description of the problem and requirements. 

> It is relatively straightforward to achieve the second requirement when referencing simple values (e.g., int or float). However, PMIx routinely shares complex structures that contain pointers to other data fields that themselves could be complex structures. The most common example of this is the sharing of a `pmix_data_array_t` object consisting of an array of complex structures, each containing malloc'd pointers to other structures or data arrays.

For the arbitrarily complex data structures requiring dynamic memory allocation on the heap of the server, how are those data currently serialized and subsequently placed into the shared-memory segment for client consumption? Maybe they aren't at the moment, but I need a little clarification here.

Thank you.

**Comment by artpol84** [comment]
At the moment, we are using serialized representation that is generated during modex operation. We just delay the unpacking on the server and place data into the shared memory.
Client side is doing unpacking during access time and PMIx key-value structure is allocated to contain the result.

**Comment by samuelkgutierrez** [comment]
Thank you, @artpol84.

I will look around the codebase to better understand the details, but that makes sense.

**Comment by samuelkgutierrez** [comment]
Regarding hwloc's symmetric memory mapping trick: [here](https://github.com/open-mpi/hwloc/blob/ad1777f06d448edfbca90c99364ef12852e73262/tests/hwloc/shmem.c#L93-L127) is the only place that I found use of that methodology. I wonder if this trick is used only for testing?

**Comment by samuelkgutierrez** [comment]
To keep track of what is learned along the way.

When enabled in a particular way, will Linux ASLR render the symmetric virtual address space trick unusable in practice? One approach might include checking for the value of `/proc/sys/kernel/randomize_va_space` at runtime during component selection.

From `man 5 proc`:

```
      /proc/sys/kernel/randomize_va_space (since Linux 2.6.12)
              Select the address space layout randomization (ASLR) policy for the system (on architectures that support ASLR).  Three val‐
              ues are supported for this file:

              0  Turn ASLR off.  This is the default for architectures that don't support ASLR, and when the kernel  is  booted  with  the
                 norandmaps parameter.

              1  Make  the addresses of mmap(2) allocations, the stack, and the VDSO page randomized.  Among other things, this means that
                 shared libraries will be loaded at randomized addresses.  The text segment of PIE-linked binaries will also be loaded  at
                 a randomized address.  This value is the default if the kernel was configured with CONFIG_COMPAT_BRK.

              2  (Since  Linux  2.6.25)  Also support heap randomization.  This value is the default if the kernel was not configured with
                 CONFIG_COMPAT_BRK.
```

From LWM.net: [Optional full ASLR for mmap() and mremap()](https://lwn.net/Articles/833820)

**Comment by rhc54** [comment]
@samuelkgutierrez I don't believe that should impact things, though I'd like to hear what @bgoglin thinks. The "trick" is definitely used in production - OMPI has been using it for several years now. In fact, it is the default mechanism when using OMPI on your systems since it was initially developed to solve a problem on your KNL cluster 😄

**Comment by samuelkgutierrez** [comment]
@rhc54 Interesting. Could you or @bgoglin please point me to that code in hwloc? The only source I could find that attempts this trick is cited above, and it looks like it's strictly used for testing.

**Comment by rhc54** [comment]
I think I understand your confusion here. HWLOC provides the _tools_ for doing it, but it is up to the PMIx server to actually implement the key parts. You should look [here](https://github.com/openpmix/openpmix/blob/master/src/mca/ploc/hwloc/ploc_hwloc.c) for how one sets up the virtual storage and then passes it to the client. You'll also find the client's code where it attaches.

**Comment by samuelkgutierrez** [comment]
> I think I understand your confusion here. HWLOC provides the _tools_ for doing it, but it is up to the PMIx server to actually implement the key parts.

Thank you, @rhc54. I understand that, but I would like to better understand the regime in which this symmetric virtual mapping occurs in hwloc to observe when and how it happens.

> You should look [here](https://github.com/openpmix/openpmix/blob/master/src/mca/ploc/hwloc/ploc_hwloc.c) for how one sets up the virtual storage and then passes it to the client. You'll also find the client's code where it attaches.

Excellent. I'll put this in my back pocket.

**Comment by rhc54** [comment]
It is the PMIx server that finds the virtual address "hole". The server then calls an HWLOC function and tells it to "write the topology you discovered into this address space". The code for doing the transfer (in hwloc/shmem.c) has its own allocator code to properly handle the base location and offset when writing the topology into the new location.

I'm not sure what else you are trying to discover 🤷‍♂️

**Comment by rhc54** [comment]
I see the problem - you are looking in the wrong place. You want to look [here](https://github.com/open-mpi/hwloc/blob/ad1777f06d448edfbca90c99364ef12852e73262/hwloc/shmem.c)

**Comment by samuelkgutierrez** [comment]
Perhaps we are talking about different topics here. I was under the impression that this thread was specific to how to deal with the shared-memory key-value service.

**Comment by samuelkgutierrez** [comment]
> I see the problem - you are looking in the wrong place. You want to look [here](https://github.com/open-mpi/hwloc/blob/ad1777f06d448edfbca90c99364ef12852e73262/hwloc/shmem.c)

**Comment by rhc54** [comment]
> I was under the impression that this thread was specific to how to deal with the shared-memory key-value service.

It is - but you were asking questions about how HWLOC supports the symmetric virtual address space, and if that might be impacted by a kernel setting. As part of that, you asked if it was only used for testing, and how you might observe how and when it is used. I'm pointing you to the code that sets it up and the underlying code that implements it.

You are welcome to see how I started implementing it [here](https://github.com/rhc54/openpmix/tree/topic/shmem/src/mca/gds/shmem). Note that I had to change some of the PMIx classes to add support for the necessary custom memory allocator. You'll see the modified object creation calls in the referenced files.

**Comment by samuelkgutierrez** [comment]
> > I was under the impression that this thread was specific to how to deal with the shared-memory key-value service.
> 
> It is - but you were asking questions about how HWLOC supports the symmetric virtual address space, and if that might be impacted by a kernel setting. As part of that, you asked if it was only used for testing, and how you might observe how and when it is used. I'm pointing you to the code that sets it up and the underlying code that implements it.
> 
> You are welcome to see how I started implementing it [here](https://github.com/rhc54/openpmix/tree/topic/shmem/src/mca/gds/shmem). Note that I had to change some of the PMIx classes to add support for the necessary custom memory allocator. You'll see the modified object creation calls in the referenced files.

Okay, good. For a moment there we were talking passed each other. I'll take a look at the bits you cited.

**Comment by bgoglin** [comment]
I agree with @rhc54, ASLR shouldn't matter here since we are mmap'ping at a specific location.

**Comment by samuelkgutierrez** [comment]
Thank you, @bgoglin and @rhc54.

To summarize:
* We do not expect Linux ASLR to cause issues in practice.
* hwloc and Open MPI have used symmetric memory mapping successfully in
  production for a while now without noticeable issue.
* OpenPMIx has convenience functions for finding appropriate holes in virtual
  memory: [find_hole()](https://github.com/openpmix/openpmix/blob/74327dd61ffa01d7e0a731887118c28aefd78683/src/mca/ploc/hwloc/ploc_hwloc.c#L2019)
* During modex Open MPI can use the shared-memory location information
  determined by OpenPMIx to load an hwloc topology from a specified location
  using hwloc_shmem_topology_adopt(). [Here is an
  example](https://github.com/open-mpi/ompi/blob/ab3a8491e090d820e2c2fec0d96db21e8eacbe5b/opal/mca/hwloc/base/hwloc_base_util.c#L324).

**Comment by rhc54** [comment]
Closing this for now as it looks like we are nearly complete.
