### ISSUE TITLE
How is oversubscription communicated to Open MPI?

### ISSUE THREAD

**Issue by jsquyres** [openpmix/openpmix#2192]
In the ORTE days, Open MPI relied on ORTE setting the MCA param `ompi_mpi_oversubscribe` to tell OMPI if it was running in an oversubscription situation or not.

Now that we have split ORTE off into PRRTE, is there a PMIx attribute or something that lets the Open MPI layer know if it's running in an oversubscribed environment?  Open MPI master/v5.0.x are currently still looking at the `ompi_mpi_oversubscribe` MCA param, but I'm guessing that that is no longer correct.

**Comment by rhc54** [comment]
This is fixed by a combination of https://github.com/openpmix/openpmix/pull/2200, https://github.com/openpmix/prrte/pull/972, and https://github.com/open-mpi/ompi/pull/8998
