### ISSUE TITLE
PMIx_fence doesn't work following second  PMIx initialization

### ISSUE THREAD

**Issue by hppritcha** [openpmix/openpmix#2202]
In developing some tests for the MPI Sessions OMPI prototype, we found that if we create a session, finalize a session, then try to create a session again, OMPI gets stuck in the first call to PMIx_Fence(_nb) following PMIx_Init.

The attached PMIx only test reproduces this behavior.
```
 * Copyright (c) 2020      Triad National Security, LLC.
 *                         All rights reserved.
 *
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

/* Test of rank position identification inside group */

#include "pmix.h"
#include <stdio.h>
#include <stdlib.h>
/*
#include <assert.h>
#include <sys/time.h>
#include <stdarg.h>
#include <unistd.h>
*/

pmix_proc_t this_proc;

int main(int argc, char *argv[]) {

    pmix_value_t *val;
    size_t ninfo = 0;
    pmix_proc_t job_proc;
    int count = 0;

    /* initialization */
try_again:
    fprintf(stderr, "initializing pmix\n");
    PMIx_Init(&this_proc, NULL, ninfo);
    fprintf(stderr, "initialized pmix\n");

    fprintf(stderr, "calling pmix fence\n");
    PMIx_Fence(NULL, 0, NULL, 0);
    fprintf(stderr, "called pmix fence\n");

    /* Handles everything that needs to happen after PMIx_Init() */

    job_proc = this_proc;
    job_proc.rank = PMIX_RANK_WILDCARD; // Note that PMIX_RANK_WILDCARD == -2
    fprintf(stderr, "getting job size\n");
    PMIx_Get(&job_proc, PMIX_JOB_SIZE, NULL, 0, &val);
    /* After using PMIx_Get to get a value, we need to compare it our validation parameters
       we've passed as an argument; this is the main purpose of pmixt_validate_predefined(). */


    fprintf(stderr, "getting universesize\n");
    PMIx_Get(&job_proc, PMIX_UNIV_SIZE, NULL, 0, &val);

    fprintf(stderr, "getting local size\n");
    PMIx_Get(&job_proc, PMIX_LOCAL_SIZE, NULL, 0, &val);
    fprintf(stderr, "getting local rank\n");
    PMIx_Get(&this_proc, PMIX_LOCAL_RANK, NULL, 0, &val);

    fprintf(stderr, "getting local nodid\n");
    PMIx_Get(&this_proc, PMIX_NODEID, NULL, 0, &val);

    fprintf(stderr, "getting local peers\n");
    PMIx_Get(&job_proc, PMIX_LOCAL_PEERS, NULL, 0, &val);

    fprintf(stderr, "getting hostname\n");
    PMIx_Get(&this_proc, PMIX_HOSTNAME, NULL, 0, &val);

    fprintf(stderr, "getting my rank\n");
    PMIx_Get(&job_proc, PMIX_RANK, NULL, 0, &val);


    /* finalize */
    fprintf(stderr, "finalizing pmix\n");
    PMIx_Finalize(NULL, 0);
    fprintf(stderr, "finalized pmix\n");
    count++;
    if (count < 2) {
       goto try_again;
    }

   exit(0);

}
```
This behavior is observed with OpenPMIx master at 97906c9 and prrte master at 0467d37 using 1 or more processes.

**Comment by rhc54** [comment]
@hppritcha I just want to ensure I understand this correctly. I asked on the Slack channel and was told that the MPI standard does not allow one to call `MPI_Init -> MPI_Finalize -> MPI_Init` - in other words, once you actually "finalize" the library, you are not allowed to re-initialize it. Your example appears to be aimed at violating that rule. Is this correct?

My initial look into this indicates that allowing one to re-initialize after finalizing the library isn't a trivial fix. So I'd like to ensure that this is the intended purpose before embarking down that path.

**Comment by hppritcha** [comment]
Sessions world one can do this, per Chapter 11 section 3 of the hopefully soon to be ratified MPI-4 specification:

```
There are a number of limitations with the World Model described in the preceding section.
Among these are the following: MPI cannot be initialized from dierent application components
without a priori knowledge or coordination; MPI cannot be initialized more than
once; and MPI cannot be reinitialized after MPI_FINALIZE has been called. This section
describes an alternative approach to MPI initialization|the Sessions Model. With this approach,
an MPI application, or components of the application, can instantiate MPI resources
for the specic communication needs of this component. MPI_COMM_WORLD is not valid
for use as a communicator. MPI_INFO_ENV is not valid for use as an info object when only
using the Sessions Model. As described in Section 11.2.1, MPI must be initialized using
the World Model to use this info object. Note that an application may employ both the
Sessions Model and World Model concurrently (see Section 11.1).
In the Sessions Model, MPI resources can be allocated and freed multiple times in an
MPI process.
```

**Comment by hppritcha** [comment]
If one removes the fence from the test case, then PMIx can be inited/finalized multiple times, or at least it used too.

**Comment by hppritcha** [comment]
ah yes now I remember.  I used this test case sans pmix_fence and ended up opening a PR #1999 to fix an issue at that point with multiple pmix init/finalize calls.

**Comment by rhc54** [comment]
I found at least one problem point in the current code dealing with the MCA parameters. Turns out that a string variable you give the MCA system gets "NULL'd" upon finalize, which means that you have to ensure it gets re-initialized before registering each time. I suspect there are others we'll hit depending upon what piece of the code base you touch.

I'll dig into this more.

**Comment by hppritcha** [comment]
yep, in the MPI sessions prototype we're careful to do that for ompi/opal mca params.
Actually just in case you didn't know, its perfectly legal for an MPI app to call MPI_T_init/MPI_Tfinalize, then go on to calling MPI_Init/MPI_Finalize.    Related OMPI issue - https://github.com/open-mpi/ompi/issues/8860

**Comment by rhc54** [comment]
Actually, it would have hung when any collective was called. The PR should resolve that problem.
