### ISSUE TITLE
Wrong rpm name for v3.2.3

### ISSUE THREAD

**Issue by wpoely86** [openpmix/openpmix#2232]
Under the github release for v3.2.3 there is a source rpm but with version 3.2.2.
URL: https://github.com/openpmix/openpmix/releases/download/v3.2.3/pmix-3.2.2-1.src.rpm

As far as I can see, it's still version 3.2.2 so it seems the source rpm was forgotten to update to 3.2.3?

**Comment by rhc54** [comment]
Huh - looks like we indeed picked up the wrong rpm file...and to top it off, had the wrong sha1sum's for the tarballs as well 🤷‍♂️ 

Thanks for pointing it out!
