### ISSUE TITLE
shared memory status in PMIx v4

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#2238]
We are doing some memory footprinting of the OMPI master and I noticed that the hash component shows up in the profile and it scales up with the number of processes.

I recall that dstore was going to be deprecated from the v4, are we expecting the alternative?
Also (though it's an OMPI question, but ...) will OMPI support PMIx v3 in OMPIv5 and master?

**Comment by artpol84** [comment]
@rhc54  @sb17v

**Comment by artpol84** [comment]
Ok, I see that PRRTE requires v4, so Slurm is the only option to go with PMIx v3

**Comment by rhc54** [comment]
OMPI v5 and master can be compiled and run with PMIx v3.x if you configure it --without-prte. You would then have to launch your app some other way. PRRTE requires a minimum of PMIx v4.1, which still includes the dstore component. However, you should find that PMIx always has a linear scaling component vs number of processes in the job as we do provide info on a per-process basis. It's a more complex scaling law because we do also provide per-job and per-node info as well - but the proc info will scale linearly.

**Comment by artpol84** [comment]
We are facing an issue trying to configure without PRRTE:

```
*** Configuring PRRTE
with_prrte: no
opal_prrte_mode: disabled
configure: WARNING: Open MPI no longer uses the ORTE environment - it has been
configure: WARNING: replaced by PRRTE. Accordingly, the "--enable-orterun-prefix-by-default"
configure: WARNING: and "--enable-mpirun-prefix-by-default" options have been replaced
configure: WARNING: by "--enable-prte-prefix-by-default". We will do the translation for
configure: WARNING: you now, but these older options are deprecated and will be removed
configure: WARNING: in a later release, so please update your build scripts.
checking if PMIx version is 4.0.0 or greater... no
configure: WARNING: OMPI's internal runtime environment "PRRTE" does not support
configure: WARNING: PMIx versions less than v4.x as they lack adequate tool
configure: WARNING: support. You can, if desired, build OMPI against an earlier
configure: WARNING: version of PMIx for strictly direct-launch purposes - e.g., using
configure: WARNING: Slurm's srun to launch the job - by configuring with the
configure: WARNING: --without-prrte option.
configure: error: Cannot continue
```

Note the 
```
with_prrte: no
```

as we supplied the "--without-prrte" option to the configure script.

**Comment by rhc54** [comment]
Ah, indeed - looks like even without PRRTE, you'll have to use PMIx of at least 4.0. You'll need to see if it requires 4.1 or you can get by with just 4.0. Either way, can't use 3.x.
