### ISSUE TITLE
Python deadlock

### ISSUE THREAD

**Issue by MattBBaker** [openpmix/openpmix#2306]
### What version of the PMIx Reference Library are you using? 
Last tested against master checkout 17fbf151fa5c7aa6beedf06dbf73428037e9b6d5 merging #2295

### Describe how PMIx was installed 
./configure;make; make install;cd bindings/python;make install

### Please describe the system on which you are running

My home desktop and summit both exhibit this behavior
* Operating system/version: Ubuntu 20.04 and RHEL8
* Computer hardware: x86_64 desktop and Power9
* Network type: ethernet and infiniband

-----------------------------

## Details of the problem

It looks like this is an AB/BA mutex problem. Python has its Global Interpreter lock (A) and PMIx has it's lock (B). When I try and run a program where the master Python thread `client.spawn()`s a lot of tasks and there is a callback for task completion that tries to interact with Python, thus requiring the GIL, than a deadlock is possible. When I attach a debugger to the deadlocked program I do see the callback thread waiting on the GIL and the running Python thread blocking on a lock in the OpenPMIx library. So it looks like the Python thread has the GIL and tries to lock PMIx, and the PMIx callback has a PMIx lock and is trying to take the GIL to call the Python function. With this state I have a hard time trying to spawn 2 tasks to run at the same time, while running 3 or more is impossible. Spawning 1 task at a time always works.

I made a hacked version of the build system that isn't a long term fix, it disables the auto generation of the `pmix_constants.pxd` file and modifying it and the `pmix.pyx` file so that in the `spawn()` function it will release the GIL before calling into the PMIx library. With this 'fix' so that the locks in PMIx are always taken before the GIL, I can scale up to more jobs and they all complete fine. I'm working on doing larger scales to see if I can find a limit, but so far I'm feeling good about 20 spawns. The problem is that this "disable autogen and hack the output" isn't a real option to make a PR out of. I'm currently trying to develop a better solution and wanted to document this problem if anyone can help

**Comment by rhc54** [comment]
Would it be possible to use the non-blocking form of the PMIx APIs - e.g., `PMIx_Spawn_nb`? This would mean that you'd have to change `client.spawn` to be non-blocking as well, I guess, so maybe it is more work than it's worth?

The benefit of doing this is that you'd avoid sitting in that PMIx thread during the `PMIx_Spawn` call - you'd return immediately. The PMIx library will still execute the request in its progress thread, but that is done sequentially and means you won't have something calling back into the Python side while you are still inside PMIx.

**Comment by MattBBaker** [comment]
The `PMIx_Spawn_nb` might be an option, I've been meaning to look into it more, thanks

A secondary concern of mine is general GIL hygiene, where if Python is calling into an expensive PMIx call it would be nice to release the GIL to let other Python threads progress. Getting this exactly right will take a lot more work, but I'm thinking that tagging all the PMIx functions as nogil and then solving this deadlock in the short term is for the best.

**Comment by naughtont3** [comment]
We have done a good bit of testing with the Python bindings lately.  They worked for thousands of runs in the tests.  However, we were able to find one scenario that would deadlock in latest test case.  We have reproducer and will work to get it resolved.  Just updating this ticket b/c it would be nice to get that fix into the next pmix-4.2.1 release.

**Comment by naughtont3** [comment]
Note, I'm kind of hijacking this ticket at end b/c the versions we tested were not what was used back in  Sep-2021.  :-)

**Comment by rhc54** [comment]
Hijack away! Look forward to seeing the fix. I might start using the Python bindings myself, so any help there is much appreciated.

**Comment by naughtont3** [comment]
Matt has a fix, that he'll PR shortly.  It would be good to have this in next snapshot if possible.

**Comment by rhc54** [comment]
> Matt has a fix, that he'll PR shortly. It would be good to have this in next snapshot if possible.

Done - and backported to v4.2. Thanks!

Should we leave this issue open? Or close it for now - can reopen if/when you hit something again or open a new one?

**Comment by naughtont3** [comment]
I'll defer to @MattBBaker, but seems like we can close for this round and open new issues as needed going forward w/ more specifics about error/version/context/etc.
