### ISSUE TITLE
ABI change: pmix_ploc_base_destruct_topology removed

### ISSUE THREAD

**Issue by opoplawski** [openpmix/openpmix#2353]
## Background information
Compiled prrte against pmix 4.1.0, then updated pmix to 4.1.0rc2. prterun fails with:
prterun: symbol lookup error: /lib64/libprrte.so.2: undefined symbol: pmix_ploc_base_destruct_topology

I think you're going to need to bump to SONAME version.

**Comment by rhc54** [comment]
Wow, thanks for catching this! I'd rather not break ABI, especially mid-series, so the referenced PR simply replaces the removed symbols. Please confirm this fixes it.
