### ISSUE TITLE
PMIx_Get with PMIX_RANK_UNDEF not working

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2376]
### What version of the PMIx Reference Library are you using?
v4.1.0

### Describe how PMIx was installed
official github source tarball

### Please describe the system on which you are running

* Operating system/version: GNU/Linux (Fedora 32)
* Computer hardware: x64
* Network type: eth

-----------------------------

## Details of the problem

I tried to do what is explained in Chapter 7 on page 112 in Version 4.0 of PMIx Standard:
> Both of the above methods are based on retrieval from a specific process - i.e., the proc argument to
PMIx_Get must include both the namespace and the rank of the process that posted the
information. However, in some cases, non-reserved keys are provided on a globally unique basis
and the retrieving process has no knowledge of the identity of the process posting the key. This is
typically found in legacy applications (where the originating process identifier is often embedded in
the key itself) and in unstructured applications that lack rank-related behavior. In these cases, the
key remains associated with the namespace of the process that posted it, but is retrieved by use of
the PMIX_RANK_UNDEF rank. In addition, the keys must be globally exchanged prior to retrieval
as there is no way for the host to otherwise locate the source for the information.

So as I understand that
1. There has to be a key that is unique over all ranks.
1. After the put and commit, `PMIx_Fence` has to be called with `PMIX_COLLECT_DATA`
1. Now each process in the namespace can `PMIx_Get` the value using source rank `PMIX_RANK_UNDEF`

If I am wrong here, please correct me and ignore the rest.

As far as I can see, this is not working as expected. To test, I have modified the example `client.c`, the relevant part is:
```C
    /* get the number of procs in our job - univ size is the total number of allocated
     * slots, not the number of procs in the job */
    if (PMIX_SUCCESS != (rc = PMIx_Get(&proc, PMIX_JOB_SIZE, NULL, 0, &val))) {
        fprintf(stderr, "Client ns %s rank %d: PMIx_Get job size failed: %d\n", myproc.nspace,
                myproc.rank, rc);
        goto done;
    }
    nprocs = val->data.uint32;
    PMIX_VALUE_RELEASE(val);
    fprintf(stderr, "Client %s:%d num procs %d\n", myproc.nspace, myproc.rank, nprocs);

    if (0 > asprintf(&tmp, "uniq-key")) {
        exit(1);
    }

    if (myproc.rank == 0) {
        /* put a few values */
        value.type = PMIX_UINT64;
        value.data.uint64 = 1234;
        if (PMIX_SUCCESS != (rc = PMIx_Put(PMIX_GLOBAL, tmp, &value))) {
            fprintf(stderr, "Client ns %s rank %d: PMIx_Put internal failed: %d\n", myproc.nspace,
                    myproc.rank, rc);
            goto done;
        }

        /* push the data to our PMIx server */
        if (PMIX_SUCCESS != (rc = PMIx_Commit())) {
            fprintf(stderr, "Client ns %s rank %d: PMIx_Commit failed: %d\n", myproc.nspace,
                    myproc.rank, rc);
            goto done;
        }
    }

    /* call fence to synchronize with our peers - instruct
     * the fence operation to collect and return all "put"
     * data from our peers */
    PMIX_INFO_CREATE(info, 1);
    flag = true;
    PMIX_INFO_LOAD(info, PMIX_COLLECT_DATA, &flag, PMIX_BOOL);
    if (PMIX_SUCCESS != (rc = PMIx_Fence(&proc, 1, info, 1))) {
        fprintf(stderr, "Client ns %s rank %d: PMIx_Fence failed: %d\n", myproc.nspace, myproc.rank,
                rc);
        goto done;
    }
    PMIX_INFO_FREE(info, 1);

    proc.rank = PMIX_RANK_UNDEF;

    rc = PMIx_Get(&proc, tmp, NULL, 0, &val);

    if (rc != PMIX_SUCCESS) {
        fprintf(stderr, "Client ns %s rank %d: PMIx_Get %s failed: %d\n", myproc.nspace,
                myproc.rank, tmp, rc);
        goto done;
    }
    if (PMIX_UINT64 != val->type) {
        fprintf(stderr, "Client ns %s rank %d: PMIx_Get %s returned wrong type: %d\n",
                myproc.nspace, myproc.rank, tmp, val->type);
        PMIX_VALUE_RELEASE(val);
        goto done;
    }
    if (1234 != val->data.uint64) {
        fprintf(stderr, "Client ns %s rank %d: PMIx_Get %s returned wrong value: %d\n",
                myproc.nspace, myproc.rank, tmp, (int) val->data.uint64);
        PMIX_VALUE_RELEASE(val);
        goto done;
    }
    fprintf(stderr, "Client ns %s rank %d: PMIx_Get %s returned correct\n", myproc.nspace,
            myproc.rank, tmp);
    PMIX_VALUE_RELEASE(val);


done:
    free(tmp);
```

The result is, that `PMIx_Get` returns `PMIX_ERR_NOT_FOUND`:
```sh
[krempel@node01 ~]$ Projekte/PMIx/prte-2.0.0/install/bin/prterun --output tag -n 2 ./pmix_get_undefrank |& sort -n
[prterun-node01-11678@1,0]<stderr>:Client 11683: Running
[prterun-node01-11678@1,0]<stderr>:Client ns prterun-node01-11678@1 rank 0 pid 11683: Running
[prterun-node01-11678@1,0]<stderr>:Client ns prterun-node01-11678@1 rank 0: Finalizing
[prterun-node01-11678@1,0]<stderr>:Client ns prterun-node01-11678@1 rank 0: PMIx_Get uniq-key failed: -46
[prterun-node01-11678@1,0]<stderr>:Client ns prterun-node01-11678@1 rank 0:PMIx_Finalize successfully completed
[prterun-node01-11678@1,0]<stderr>:Client prterun-node01-11678@1:0 num procs 2
[prterun-node01-11678@1,0]<stderr>:Client prterun-node01-11678@1:0 topology loaded
[prterun-node01-11678@1,0]<stderr>:Client prterun-node01-11678@1:0 universe size 48
[prterun-node01-11678@1,1]<stderr>:Client 11684: Running
[prterun-node01-11678@1,1]<stderr>:Client ns prterun-node01-11678@1 rank 1 pid 11684: Running
[prterun-node01-11678@1,1]<stderr>:Client ns prterun-node01-11678@1 rank 1: Finalizing
[prterun-node01-11678@1,1]<stderr>:Client ns prterun-node01-11678@1 rank 1: PMIx_Get uniq-key failed: -46
[prterun-node01-11678@1,1]<stderr>:Client ns prterun-node01-11678@1 rank 1:PMIx_Finalize successfully completed
[prterun-node01-11678@1,1]<stderr>:Client prterun-node01-11678@1:1 num procs 2
[prterun-node01-11678@1,1]<stderr>:Client prterun-node01-11678@1:1 topology loaded
[prterun-node01-11678@1,1]<stderr>:Client prterun-node01-11678@1:1 universe size 48
```

Actually, I would say, after reading on page 116 of the standard, `PMIx_Get` should either return the key (in this case as it exists it should of cause do so), or wait and return nothing since there is no `PMIX_TIMEOUT` specified, or it could wait a default timeout and then return `PMIX_ERR_TIMEOUT`. To return `PMIX_ERR_NOT_FOUND` is not intended in the standard as long as `PMIX_IMMEDIATE` is not given:
> If the value still isn’t found and the PMIX_IMMEDIATE attribute was given, then the library
shall return the PMIX_ERR_NOT_FOUND error constant to the requester. Otherwise, the PMIx
server library will take one of the following actions:
> -  If the target process has a rank of PMIX_RANK_UNDEF, then this indicates that the key being
requested is globally unique and not associated with a specific process. In this case, the server
shall hold the request until either the data appears at the server or, if given, the
PMIX_TIMEOUT is reached. In the latter case, the server will return the
PMIX_ERR_TIMEOUT status. Note that the server may, depending on PMIx implementation,
never respond if the caller failed to specify a PMIX_TIMEOUT and the requested key fails to
arrive at the server.

**Comment by rhc54** [comment]
I have been unable to reproduce this with the current head of PMIx/PRRTE master branches. The release branches should be tracking, although the updates have not been released yet.

Could you please retry with the head of the PMIx v4.1 and PRRTE v2.0 branches? I think this has already been fixed.

**Comment by rhc54** [comment]
I've given this more thought, and I think there is some misunderstanding here - might merit clarification in the doc. If you perform a "fence" and collect the data, then there can be no "timeout" as the data has already been exchanged. If you think about it, the fence has circulated and delivered all the data "put" by the processes. Thus, the data is logically either present or "not found".

The issue of a "timeout" only arises in the case where you perform a "fence" that does NOT collect the data. In this case, we fallback to the "direct modex" mode of operation - i.e., we must request the data from the daemon hosting the source process. For globally unique keys, there is no way to perform that request as we don't know who is going to publish the key. Thus, "timeout" for globally unique keys means that something external to the system (not relying on the procs calling "fence") must magically provide the value.

To be honest, "timeout" is really meant for the case where we have keys that are directly associated with their publishing process - i.e., non-globally unique keys. In this case, we can (and do) have use-cases where procs post their keys asynchronously (often without a fence at all), and the keys can also be requested asynchronously. The daemon of the requesting process looks up the daemon of the proc that is supposed to post the requested key, passes a request for that key to that daemon, and then waits until either the data is returned or timeout occurs.

When you have a globally unique key, you cannot perform that exchange - either the data is present, or it is not present. You can try to wait for a timeout, but without a "fence" operation to circulate the data, you can only hope that some 3rd party drops the data into your lap. Given the unlikely nature of that hope, we simply return "not found" if the data isn't present.

Hope that helps - probably too complex to explain in a doc, though someone is welcome to try.

**Comment by krempel-pt** [comment]
Thanks for the thoughts. I buy your argument that timeout makes no sense in case of the unique keys.

For the basic problem of not getting the data as expected, I will try to verify tomorrow that the issue has gone with the current branch heads.

**Comment by krempel-pt** [comment]
Sorry for not keeping my promise, I was ill.

I could verify that with the current master heads of openPMIx and PRRTE the issue is no longer reproducible. So I'm looking forward to the next release.

I think this can be closed, thanks.
