### ISSUE TITLE
4.1.0 not finding hwloc library

### ISSUE THREAD

**Issue by cponder** [openpmix/openpmix#2419]
I'm building PMIx 4.1.0 using these flags
```
--with-hwloc=/usr/local --with-hwloc-libdir=/usr/local/lib
```
or just this
```
--with-hwloc=/usr/local
```
and get the messages
```
checking for hwloc in... /usr/local/lib
configure: looking for header in /usr/local/include
checking hwloc.h usability... yes
checking hwloc.h presence... yes
checking for hwloc.h... yes
checking for library containing hwloc_topology_init... no
configure: WARNING: HWLOC SUPPORT REQUESTED AND NOT FOUND
configure: error: CANNOT CONTINUE
```
I built the latest hwloc (2.6.0) and installed into `/usr/local`.
What else do I have to do here?

**Comment by cponder** [comment]
hwloc 2.7.0rc1 is the latest version, and that doesn't work either.
Are you going backlevel with it??

**Comment by cponder** [comment]
Also PMIx 4.1.1rc5 won't build with either version of hwloc.

**Comment by rhc54** [comment]
Not sure what to say here - I installed hwloc 2.6.0 into `/usr/local` and everything built fine when passing `--with-hwloc=/usr/local` to configure. Tried PMIx v4.1.0, the head of PMIx v4.1.1 branch, PMIx master - all built fine.

There is something a little odd in your output - it should have looked like this when using `--with-hwloc=/usr/local`:
```
--- MCA component ploc:hwloc (m4 configuration macro)
checking for MCA component ploc:hwloc compile mode... dso
checking for hwloc in... /usr/local/include and /usr/local/lib
configure: looking for header in /usr/local/include
checking hwloc.h usability... yes
checking hwloc.h presence... yes
checking for hwloc.h... yes
checking for library containing hwloc_topology_init... -lhwloc
checking if external hwloc version is 1.5 or greater... yes
checking if external hwloc version is 1.8 or greater... yes
checking will hwloc support be built... yes
checking hwloc header... <hwloc.h>
checking if MCA component ploc:hwloc can compile... yes
```
It looks like something has gotten confused and it isn't adding the `-lhwloc` when checking the library. I assume you are building from a tarball? You might want to delete the directory and re-untar it again. If you are building from a Git clone, then do a `git clean -dfx`, rerun `autogen.pl`, and then reconfigure.

**Comment by cponder** [comment]
I'm using the tarball for each case, with a clean directory.
I can build PMIx 4.1.0 with hwloc 2.5.0, just not the newer versions.

Also I'm using the PGI 21.11 compiler, if that makes any difference.
Is there some difference between hwloc 2.5.0 versus later?

**Comment by rhc54** [comment]
I'm sure there are some differences in 2.5.0 versus 2.6/7, but I'm unaware of them. I know there have been bugs in the PGI (now nvcc, I believe?) releases recently, so you might want to try with `gcc` or something else just to see if that's the problem.

**Comment by rhc54** [comment]
We have updated our configure logic, so perhaps this will be fixed there. If this is a PGI-related problem, our CI isn't picking it up - but I honestly don't know what PGI version they are using (and I have no visibility into their CI system).
