### ISSUE TITLE
4.1.1 tarball still has rc6 in VERSION

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#2452]
The version file for 4.1.1.tar.gz needs fixing.

**Comment by rhc54** [comment]
Just checked and the tarball looks fine - there is no greek extension in VERSION. I downloaded and untarred it (in addition to checking the local copies that I posted) just to be sure

**Comment by amckinstry** [comment]
I still see extension in the tarballs tagged here:
https://github.com/openpmix/openpmix/tags
in particular the VERSION file

**Comment by rhc54** [comment]
Those are not the official tarballs - those are artifacts created by GitHub and should never be used. Unfortunately, there is no way to turn them off or get rid of them.

The official tarballs are here:  https://github.com/openpmix/openpmix/releases/tag/v4.1.1

**Comment by rhc54** [comment]
You want one of the "pmix-..." tarballs. Not the ones GitHub calls "Source code".

Sorry for the confusion - there simply is no way to get GitHub not to create the wrong ones, nor is there a way to remove them.

**Comment by rhc54** [comment]
Closing this for now - hopefully, we'll find a way to resolve the GitHub tarballs someday.
