### ISSUE TITLE
Assertion error on obj_magic_id 

### ISSUE THREAD

**Issue by zhngaj** [openpmix/openpmix#2519]
### What version of the PMIx Reference Library are you using? 

Open MPI master 6ea18b79a5ec6188d56f0bf5ceb57d4f47dcd262

 b98b7e83519963f7ba484ea34449668ea6834a0e 3rd-party/openpmix (v1.1.3-3376-gb98b7e83)
 1717de3cf3d1c079d1f55480ca5a14f20d0e723c 3rd-party/prrte (psrvr-v2.0.0rc1-4203-g1717de3cf3)

### Describe how PMIx was installed
I just directly built Open MPI with `./configure --prefix=/fsx/ompi/install --with-ofi=/fsx/libfabric/install --with-hwloc=external --disable-man-pages --enable-debug`

Checking openmpix's config.log, it shows `./configure --disable-option-checking --prefix=/fsx/ompi/install --without-tests-examples --enable-pmix-binaries --disable-pmix-backward-compatibility --disable-visibility --enable-debug --with-ofi=/fsx/libfabric/install --disable-man-pages --enable-debug --cache-file=/dev/null --srcdir=.`

## Details of the problem

I'm getting assertion error in openpmix when running osu_alltoallv with debug enabled Open MPI  ([6ea18b79a5ec6188d56f0bf5ceb57d4f47dcd262](https://github.com/open-mpi/ompi/commit/6ea18b79a5ec6188d56f0bf5ceb57d4f47dcd262))
```
mpirun --prefix /fsx/ompi/install --wdir results/omb/collective/osu_alltoallv -n 576 --map-by ppr:36:node --output tag  --rank-by slot --hostfile /fsx/hosts.file -x PATH -x LD_LIBRARY_PATH /fsx/SubspaceBenchmarks/spack/opt/spack/linux-amzn2-x86_64/gcc-7.3.1/osu-micro-benchmarks-5.6-465dcncsvzqciysioksqv2vkc2whrieg/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoallv

[prterun-ip-172-31-90-154-31553@1,0]<stdout>:
[prterun-ip-172-31-90-154-31553@1,0]<stdout>: # OSU MPI All-to-Allv Personalized Exchange Latency Test v5.6
[prterun-ip-172-31-90-154-31553@1,0]<stdout>: # Size       Avg Latency(us)
[prterun-ip-172-31-90-154-31553@1,544]<stderr>: osu_alltoallv: pmix_globals.c:382: cbdes: Assertion `PMIX_OBJ_MAGIC_ID == ((pmix_object_t *) (&p->data))->obj_magic_id' failed.
[prterun-ip-172-31-90-154-31553@1,544]<stderr>: [compute-dy-c5n18xlarge-8:13406] *** Process received signal ***
[prterun-ip-172-31-90-154-31553@1,544]<stderr>: [compute-dy-c5n18xlarge-8:13406] Signal: Aborted (6)
[prterun-ip-172-31-90-154-31553@1,544]<stderr>: [compute-dy-c5n18xlarge-8:13406] Signal code:  (-6)
```
From the back trace, the `obj_magic_id` has already been set to 0, thus the assertion in PMIX_DESTRUCT failed.  
```
(gdb) bt
#0  0x000014cb53aaeca0 in raise () from /lib64/libc.so.6
#1  0x000014cb53ab0148 in abort () from /lib64/libc.so.6
#2  0x000014cb53aa7a4a in __assert_fail_base () from /lib64/libc.so.6
#3  0x000014cb53aa7ac2 in __assert_fail () from /lib64/libc.so.6
#4  0x000014cb52ad72b3 in cbdes (p=0x2148e70) at pmix_globals.c:382
#5  0x000014cb528e20a6 in pmix_obj_run_destructors (object=0x2148e70)
    at /fsx/ompi/3rd-party/openpmix/src/class/pmix_object.h:546
#6  0x000014cb528e6118 in _getnb_cbfunc (pr=0xbae070, hdr=0x14cb4c000f14, buf=0x14cb50f2c980,
    cbdata=0x2148e70) at client/pmix_client_get.c:528
#7  0x000014cb52ab3726 in pmix_ptl_base_process_msg (fd=-1, flags=4, cbdata=0x14cb4c000df0)
    at base/ptl_base_sendrecv.c:841
#8  0x000014cb5243b3ad in event_base_loop () from /lib64/libevent_core-2.0.so.5
#9  0x000014cb5296e32b in progress_engine (obj=0xb77900) at runtime/pmix_progress_threads.c:228
#10 0x000014cb53e2d40b in start_thread () from /lib64/libpthread.so.0
#11 0x000014cb53b6840f in clone () from /lib64/libc.so.6

(gdb) f 4
#4  0x000014cb52ad72b3 in cbdes (p=0x2148e70) at pmix_globals.c:382
382	    PMIX_DESTRUCT(&p->data);
(gdb) p ((pmix_object_t *)(&p->data))
$1 = (pmix_object_t *) 0x2149088
(gdb) p ((pmix_object_t *)(&p->data))->obj_magic_id
$2 = 0
```

I'm not very familiar with pmix code, is it possible the object's obj_magic_id has already been set to 0 in PMIX_RELEASE, [here](openpmix/src/class/pmix_object.h)? Or do you have any quick idea?

**Comment by rhc54** [comment]
That is awfully old code - have you tried updating your PMIx and PRRTE submodule pointers?

**Comment by zhngaj** [comment]
I actually first tried ompi master with the following commits and submodules, and found this issue. 
```
[ec2-user@ip-172-31-90-154 ompi]$ git log
commit 1b5dc73e3efd1b3f96c01b5eaa96042eddf0bcb1 (HEAD -> master)
Merge: 758c759299 05487572be
Author: Jeff Squyres <jsquyres@cisco.com>
Date:   Tue Mar 15 18:56:06 2022 -0400

    Merge pull request #10114 from jsquyres/pr/trivial-docs-updates

    Continued docs updates

[ec2-user@ip-172-31-90-154 ompi]$ git submodule status
 94169f1725a26a156fd73fca1b61df14ccd581ab 3rd-party/openpmix (v1.1.3-3429-g94169f17)
 6722bd767e0fccbe07193f59f4f13e5610c7dd6a 3rd-party/prrte (psrvr-v2.0.0rc1-4274-g6722bd767e)
```

Then I traced back and found the issue was introduced by this submodule update ([6ea18b79a5ec6188d56f0bf5ceb57d4f47dcd262](https://github.com/open-mpi/ompi/commit/6ea18b79a5ec6188d56f0bf5ceb57d4f47dcd262))
```
 b98b7e83519963f7ba484ea34449668ea6834a0e 3rd-party/openpmix (v1.1.3-3376-gb98b7e83)
 1717de3cf3d1c079d1f55480ca5a14f20d0e723c 3rd-party/prrte (psrvr-v2.0.0rc1-4203-g1717de3cf3)
```

**Comment by rhc54** [comment]
You might try updating the submodules again - I just committed a fix in that area yesterday, and your submodule is pointing to March 4th (two weeks ago).

**Comment by awlauria** [comment]
Having seen this same issue, I think this is the culprit: https://github.com/openpmix/openpmix/pull/2527

**Comment by rhc54** [comment]
Yeah, I think this issue is the object release I fixed in https://github.com/openpmix/openpmix/pull/2523

**Comment by zhngaj** [comment]
I just saw OMPI updated its submodules (OpenPMIX and PRRTE) pointers. I re-built with debug enabled, and ran allgather, allgatherv, alltoall, alltoallv 10 times for each, they ran to completion. I did not see the assertion error. Thank you @rhc54, @awlauria.

```
[ec2-user@ip-172-31-90-154 ompi]$ git log -1
commit 356f21fb033fe7c20540165fa0818e60fc2c7d3e (HEAD -> master, origin/master, origin/HEAD)
Merge: b981e34334 e472291e29
Author: Geoffrey Paulsen <gpaulsen@us.ibm.com>
Date:   Fri Mar 18 09:49:42 2022 -0500

    Merge pull request #10136 from awlauria/update_submodules

    Update OpenPMIx and PRRTE submodule pointers.
[ec2-user@ip-172-31-90-154 ompi]$ git submodule status
 1b86a35db2816ee9c0f3a41988005a2ba7d29adb 3rd-party/openpmix (v1.1.3-3481-g1b86a35d)
 91f791e209ccbdfb4b8647900d292ef51d52f37d 3rd-party/prrte (psrvr-v2.0.0rc1-4319-g91f791e209)
```

**Comment by rhc54** [comment]
Very good - thx!
