### ISSUE TITLE
`MPI_Init` on a set of processes bootstrapped outside of `mpiexec`

### ISSUE THREAD

**Issue by nirandaperera** [openpmix/openpmix#2549]
## Background information

I am trying to initialize MPI without using `mpiexec`. I am wondering if there is a way to call `MPI_Init` in a set of processes that has initiated PMIx Clients? 
I have seen an MPI cluster being spawn in a SLURM `srun` command. Can someone please explain the mechanics behind it?

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

**Comment by rhc54** [comment]
You can do so - in fact, you can do it in a couple of ways, depending upon your desired result. First, you have to setup the environment to support this behavior. The only choice right now is to install the PMIx Reference RTE (PRRTE) as it supports the entire range of PMIx features. You'll find it [here](https://github.com/openpmix/prrte).

You then instantiate the PRRTE Distributed Virtual Machine (DVM) by simply executing `prte`, passing a hostfile if you aren't in a managed environment. Once the DVM is running, you can start your processes using the `prun` command - those procs can then call `MPI_Init` whenever they like. If they call `PMIx_Init` independently of MPI, then they will have access to all the PMIx functions.

If you want all the procs to be part of the same MPI comm world, then start them all at once with a single `prun` command. Note that `MPI_Init` is a blocking operation, and so the procs will block until _all_ of them have called `MPI_Init`.

If you instead want them to be separate (perhaps later to connect/accept into various groupings), then start each proc with its own `prun` command. The procs can use the `PMIx_Query_info` function to get the namespaces of all the procs currently running, as well as other info on them (e.g., where they are running, their cmd line, etc).

**Comment by nirandaperera** [comment]
@rhc54 thanks for the steps (and sorry for the radio silence)

I tried your suggestion on a dummy repo
https://github.com/nirandaperera/pmix_test/blob/main/main.cpp

I started DVM by `./bin/prte`
```
$ ./bin/prte 
Invalid MIT-MAGIC-COOKIE-1 keyDVM ready
```

In a separate terminal tried this, 
```shell
$ ./bin/prun -n 4 /home/niranda/git/pmix_test/build/pmix_test
world 1
world 1
world 1
world 1
```
So, it looks like the `MPI_Init` is not using the DVM. Am I missing something here?

**Comment by rhc54** [comment]
Which MPI did you compile with - OMPI or MPICH? And what version? You would need an MPI that uses PMIx. OMPI has done so for quite some time, but MPICH is more recent (and may require PMIx-specific configure options).

**Comment by rhc54** [comment]
Closing due to lack of response - please feel free to re-open if/when this becomes of renewed interest.
