### ISSUE TITLE
PMIx_Get memory leak

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#2572]
myself and @wfaderhold21 were working on measuring memory overhead of OMPI and we found a memory leak in the PMIx_Get in both PMIx master (409d89fd2) and v4 (e3974c6cd). Note, that we are working on a relatively stale version of OMPI master thus PMIx master is pretty stale too. But given that we see leaks in both v4 and an old PMIx master, I suspect it's worth investigating.

For the v4 branch the fix looks like this:
```patch
$ git diff
diff --git a/src/client/pmix_client_get.c b/src/client/pmix_client_get.c
index f907364f..8d2a5b03 100644
--- a/src/client/pmix_client_get.c
+++ b/src/client/pmix_client_get.c
@@ -149,6 +149,7 @@ PMIX_EXPORT pmix_status_t PMIx_Get_nb(const pmix_proc_t *proc, const char key[],
     pmix_info_t *iptr;
     bool copy = false;
     pmix_value_t *ival = NULL;
+    bool need_free = false;
 
     PMIX_ACQUIRE_THREAD(&pmix_global_lock);
 
@@ -284,6 +285,7 @@ PMIX_EXPORT pmix_status_t PMIx_Get_nb(const pmix_proc_t *proc, const char key[],
                 /* guess not - better do it */
                 nfo = ninfo + 1;
                 PMIX_INFO_CREATE(iptr, nfo);
+                need_free = true;
                 for (n=0; n < ninfo; n++) {
                     PMIX_INFO_XFER(&iptr[n], &info[n]);
                 }
@@ -421,6 +423,9 @@ PMIX_EXPORT pmix_status_t PMIx_Get_nb(const pmix_proc_t *proc, const char key[],
         cb->value = ival;
         cb->cbfunc.valuefn = cbfunc;
         cb->cbdata = cbdata;
+        if (need_free) {
+            free(iptr);
+        }
         PMIX_THREADSHIFT(cb, gcbfn);
         return PMIX_SUCCESS;
     }
```

**Comment by rhc54** [comment]
Thanks Artem! Hope you are doing well.

We are in the process of revamping the storage systems in PMIx master branch, so that branch has diverged a great deal from what is in the v4 series (and will continue to diverge as we progress). I'll take a gander at this - much appreciate the patch for v4!

**Comment by artpol84** [comment]
Thank you, Ralph.

**Comment by artpol84** [comment]
Regarding the master.

Looks like the following RETAIN is redundant:
https://github.com/openpmix/openpmix/blob/master/src/client/pmix_client_get.c#L251

Removing it makes the master behave.

**Comment by rhc54** [comment]
This has been resolved.
