### ISSUE TITLE
make: compile fails looking for -lOpenCL, but why is it looking for that?

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#2624]
### What version of the PMIx Reference Library are you using? 

git master @ 43d3345bfe942ad4943d8b67db12e6a338d8ad9e

### Describe how PMIx was installed 

git clone

### Please describe the system on which you are running

* Operating system/version: Fedora 35
* Computer hardware: x86_64
* Network type: TCP

-----------------------------

## Details of the problem

```--prefix=/home/arcurtis/opt/pmix/git' '--disable-debug' '--disable-python-bindings' '--with-hwloc=/opt/hwloc/2.4.1```

```
$ make
...
...
  CC       common/pmix_security.lo
  CC       common/pmix_iof.lo
  CC       common/pmix_attributes.lo
  CCLD     libpmix.la
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
```

**Comment by rhc54** [comment]
I vaguely recall this issue - it has to do with a hidden HWLOC dependency. IIRC, the only solution was to rebuild HWLOC without CL.

@bgoglin Does that match your recollection?

**Comment by tonycurtis** [comment]
Yeah, that was it.  Thanks.

**Comment by rhc54** [comment]
I wonder if pkg-config would help us resolve this problem? Perhaps we could pick it up in the PMIx configure logic that way?

Would be nice since we have hit this a few times. Does this sound feasible?

@bwbarrett has done some work in this area, so looping him in.
