### ISSUE TITLE
Compile: error: array subscript ‘pmix_object_t[0]’ is partly outside array bounds of ‘pmix_buffer_t[0]’ 

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#2632]
## Background information

Compile failure with array bounds with gcc 12.  Works with gcc 11.

### What version of the PMIx Reference Library are you using? 

git master @ 8352b8600227c8dc4a5fc9c4ce217bb0f6641895

### Describe how PMIx was installed 

clone

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4
* Computer hardware: AMD x86_64
* Network type: IBV

-----------------------------

## Details of the problem

```
make[2]: Entering directory '/home/arcurtis/src/openpmix/pmix/build/src'
  CC       server/pmix_server_get.lo
In file included from /home/arcurtis/src/openpmix/pmix/pmix-git/src/class/pmix_list.h:79,
                 from /home/arcurtis/src/openpmix/pmix/pmix-git/src/class/pmix_hash_table.h:45,
                 from /home/arcurtis/src/openpmix/pmix/pmix-git/src/include/pmix_globals.h:42,
                 from ../../pmix-git/src/server/pmix_server_get.c:25:
In function ‘pmix_obj_run_destructors’,
    inlined from ‘get_job_data’ at ../../pmix-git/src/server/pmix_server_get.c:696:13:
/home/arcurtis/src/openpmix/pmix/pmix-git/src/class/pmix_object.h:667:26: error: array subscript ‘pmix_object_t[0]’ is partly outside array bounds of ‘pmix_buffer_t[0]’ [-Werror=array-bounds]
  667 |     cls_destruct = object->obj_class->cls_destruct_array;
      |                    ~~~~~~^~~~~~~~~~~
../../pmix-git/src/server/pmix_server_get.c: In function ‘get_job_data’:
../../pmix-git/src/server/pmix_server_get.c:668:89: note: object ‘pbkt’ of size 8
  668 | et_job_data(char *nspace, pmix_server_caddy_t *cd, pmix_buffer_t *pbkt)
      |                                                    ~~~~~~~~~~~~~~~^~~~

cc1: all warnings being treated as errors
```

N.B. the output definitely says "et_job_data", this is not a copy-paste error.

**Comment by rhc54** [comment]
This is a byproduct of a configure change I made earlier today - turns on the "picky compiler" flags when building from a Git clone. The primary purpose was to help developers provide better PRs, but I also wanted to expose bugs from a wider range of environments than what we typically see in devel/CI. This is a case in point as it picked up a real error that would cause a segfault if the code path had been executed (it is an error code path, and so we don't hit it - until someday we do).

I hope this won't prove too painful for you and others - it might take us a few iterations to chase out all the bugs, but then it should all quiet down again. Hopefully, it will prove worthwhile in the end 😄

**Comment by tonycurtis** [comment]
OK, no problem :)
