### ISSUE TITLE
Broken info field passed to pmix_server_dmodex_req_fn

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2644]
### What version of the PMIx Reference Library are you using?
openpmix: current master [534cf08](https://github.com/openpmix/openpmix/commit/534cf08dd9f5d174bcbd796c0c0ade39bdb32953)
prrte: current master [5508970](https://github.com/openpmix/prrte/commit/550897001d74fb2831858574263751b55c448f4e)

### Describe how PMIx was installed
openpmix: `../configure --enable-debug --prefix=/home/krempel/PMIx/openpmix/install CFLAGS=-DHAVE_SYSLOG --with-libevent=/usr; make -j8; make install`
prrte: `../configure --enable-debug --with-slurm=no --with-pmix=/home/krempel/PMIx/openpmix/install --prefix=/home/krempel/PMIx/prrte/install/; make -j8; make install`

### Please describe the system on which you are running

* Operating system/version: Rocky Linux release 8.5
* Computer hardware: qemu vm
* Network type: virtual ethernet

-----------------------------

## Details of the problem

In a heavily adjusted version of the client example I do
```c
int ninfo = 1;
pmix_info_t *info;
PMIX_INFO_CREATE(info, ninfo);
int timeout = 3;
PMIX_INFO_LOAD(info, PMIX_TIMEOUT, &timeout, PMIX_INT);

char *key;
pmix_proc_t proc;
PMIX_PROC_CONSTRUCT(&proc);
PMIX_LOAD_PROCID(&proc, myproc.nspace, 1);
if (0 > asprintf(&key, "%s-%d-global", proc.nspace, proc.rank)) exit(1);
fprintf(stderr, "Client ns %s rank %d: Start getting: %s\n", myproc.nspace, myproc.rank, key);
pmix_status_t rc;
if (PMIX_SUCCESS != (rc = PMIx_Get_nb(&proc, key, info, ninfo, get_cb, key))) {
    fprintf(stderr, "Client ns %s rank %d: PMIx_Get_nb %s failed: %s\n", myproc.nspace,
            myproc.rank, key, PMIx_Error_string(rc));
}
PMIX_INFO_FREE(info, ninfo);
```

Then I run that with:
```sh
/home/krempel/PMIx/prrte/install/bin/prterun --host partec001,partec002 tests/get_reqkeys_timeout
```

I attach with `gdb` to the `prted` that handles rank 0 and set a break to `pmix_server_dmodex_req_fn`.
Here is what I see:
```
Thread 2 "prted" hit Breakpoint 1, pmix_server_dmodex_req_fn (proc=0x7fe754041868, info=0x7fe7540425b0, ninfo=2, cbfunc=0x7fe75cde7689 <dmdx_cbfunc>,                    
    cbdata=0x7fe7540417c0) at ../../src/prted/pmix/pmix_server_fence.c:383
383         PRTE_DMX_REQ(proc, info, ninfo, dmodex_req, cbfunc, cbdata);
(gdb) print ninfo
$1 = 2
(gdb) print info[0]
$2 = {key = " \201\001t\324\177", '\000' <repeats 505 times>, flags = 0, value = {type = 0, data = {flag = false, byte = 0 '\000', string = 0x0, size = 0, pid = 0,     
      integer = 0, int8 = 0 '\000', int16 = 0, int32 = 0, int64 = 0, uint = 0, uint8 = 0 '\000', uint16 = 0, uint32 = 0, uint64 = 0, fval = 0, dval = 0, tv = {         
        tv_sec = 0, tv_usec = 0}, time = 0, status = 0, rank = 0, nspace = 0x0, proc = 0x0, bo = {bytes = 0x0, size = 0}, persist = 0 '\000', scope = 0 '\000',         
      range = 0 '\000', state = 0 '\000', pinfo = 0x0, darray = 0x0, ptr = 0x0, adir = 0 '\000', envar = {envar = 0x0, value = 0x0, separator = 0 '\000'}, coord = 0x0, 
      linkstate = 0 '\000', jstate = 0 '\000', topo = 0x0, cpuset = 0x0, locality = 0, geometry = 0x0, devtype = 0, devdist = 0x0, endpoint = 0x0, dbuf = 0x0,          
      pstats = 0x0, dkstats = 0x0, netstats = 0x0, ndstats = 0x0}}}
(gdb) print info[1]
$3 = {key = "pmix.req.key", '\000' <repeats 499 times>, flags = 0, value = {type = 3, data = {flag = 144, byte = 144 '\220',
      string = 0x7fe754027990 "prterun-parteclogin-440217@1-1-global", size = 140631523621264, pid = 1409448336, integer = 1409448336, int8 = -112 '\220',
      int16 = 31120, int32 = 1409448336, int64 = 140631523621264, uint = 1409448336, uint8 = 144 '\220', uint16 = 31120, uint32 = 1409448336, uint64 = 140631523621264,
      fval = 2.24154092e+12, dval = 6.9481204543578317e-310, tv = {tv_sec = 140631523621264, tv_usec = 0}, time = 140631523621264, status = 1409448336,
      rank = 1409448336, nspace = 0x7fe754027990, proc = 0x7fe754027990, bo = {bytes = 0x7fe754027990 "prterun-parteclogin-440217@1-1-global", size = 0},
      persist = 144 '\220', scope = 144 '\220', range = 144 '\220', state = 144 '\220', pinfo = 0x7fe754027990, darray = 0x7fe754027990, ptr = 0x7fe754027990,
      adir = 144 '\220', envar = {envar = 0x7fe754027990 "prterun-parteclogin-440217@1-1-global", value = 0x0, separator = 0 '\000'}, coord = 0x7fe754027990,
      linkstate = 144 '\220', jstate = 144 '\220', topo = 0x7fe754027990, cpuset = 0x7fe754027990, locality = 31120, geometry = 0x7fe754027990,
      devtype = 140631523621264, devdist = 0x7fe754027990, endpoint = 0x7fe754027990, dbuf = 0x7fe754027990, pstats = 0x7fe754027990, dkstats = 0x7fe754027990,
      netstats = 0x7fe754027990, ndstats = 0x7fe754027990}}}
```

I found the problem, that always the first info entry is broken in that case with our own host server implementation and tried to reproduce it with prrte to be sure the memory is not somehow messed up by our-self.

**Comment by rhc54** [comment]
Okay, I misunderstood your earlier statements. I thought you were saying that the required key info was broken, which it clearly isn't as we use it in our tests. Instead, it appears there is an invalid info key in the array for some reason, which PRRTE/PMIx will ignore. I can look into that one as it shouldn't be there.

**Comment by krempel-pt** [comment]
> However, I do see one thing wrong with the program you showed up above. You cannot release the info array until _after_ `PMIx_Get_nb` returns the value - you are required to maintain that array all the way thru execution of that request. I suspect this is why you are seeing the problem. PMIx itself adds the "required key" info struct and we protect it internally.

Shame on me, you are completely right, I missed that point, now this is working as expected, thanks.
