### ISSUE TITLE
configure can't handle the case that $PREFIX/lib64 is a symlink to $PREFIX/lib

### ISSUE THREAD

**Issue by lyu** [openpmix/openpmix#2676]
### What version of the PMIx Reference Library are you using?
`4.2.0rc1`

### Describe how PMIx was installed 
From release tarball

### Please describe the system on which you are running

* Operating system/version: Rocky Linux 8.4 aarch64

-----------------------------

## Details of the problem
As the title says, when `$PREFIX/lib64` is a symlink to `$PREFIX/lib`, configure confuses itself
```
checking for libevent library (event_core) in /lustre/home/user/.local... configure: error: Found library event_core in both /lustre/home/user/.local/lib and
/lustre/home/user/.local/lib64.  This has confused configure.  Please add --with-libevent-libdir=PATH to configure to help disambiguate.
```
This also happens for prrte 3.0.0rc1
Some linux distros also do this symlink (e.g. Arch). Maybe pmix/prrte can check the actual `libdir` field of the `.pc` files?

**Comment by rhc54** [comment]
Yick - that symlink doesn't sound like a good idea! It breaks the convention that `lib` is where you'll find 32-bit libraries, so this is going to cause all kinds of problems for library developers.

I'll have to ponder that one. For now, you should be able to do as the error message indicates and tell configure the actual path you want it to use.

**Comment by lyu** [comment]
Well, if I understand it correctly, Arch is the one who is trying to adhere to https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure, but I get your point. The suggested configure options do work.

**Comment by rhc54** [comment]
Interesting - I hadn't seen that one. Thanks for passing it along! I can see the sense in what they did, although I must admit that I haven't seen it in the wild (or at least we didn't realize it!). The symlink must be something new, though, as we've been building fine until now.

I'll look into the configure logic - we should be able to handle the symlink better than we do, and I'll check into your suggestion as well.

**Comment by rhc54** [comment]
@lyu Could you please try https://github.com/openpmix/openpmix/pull/2677 and let me know if that fixes the symlink issue?

**Comment by lyu** [comment]
@rhc54 Unfortunately it doesn't, configure errors out with the same error message.
I have libevent, hwloc and zlib installed under `$HOME/.local`, do you need other info that I can provide?

**Comment by rhc54** [comment]
I've updated that patch - could you please give it another try? I had fixed one spot but missed that there was another. I have them both fixed now.

**Comment by lyu** [comment]
The other two libs are working now! But libevent still needs `--with-libevent-libdir`, otherwise it fails the `event_getcode4name` check in `config/pmix_setup_libevent.m4`, with error message
```
checking for libevent library (event_core) in /lustre/home/user/.local... checking for event_getcode4name in -levent... no
```

**Comment by rhc54** [comment]
Hooray! Sounds like the new problem is something localized to the libevent configure code - I'll check that out next.

**Comment by rhc54** [comment]
Hmmm...the only reason it would be looking for event_getcode4name is if it failed to find libevent itself. Can you post the complete output about libevent?

**Comment by lyu** [comment]
```
checking for libevent header at /lustre/home/user/.local/include... found
checking for libevent library (event_core) in /lustre/home/user/.local... checking for event_getcode4name in -levent... no
checking will libevent support be built... no
checking for libev pkg-config name... libev
checking if libev pkg-config module exists... no
: Searching for libev in default search paths
checking for libev cppflags...
checking for libev ldflags...
checking for libev libs... -lev
checking for libev static libs... -lev
checking for event.h... yes
checking for ev_async_send... no
checking will libev support be built... no
: WARNING: Either libevent or libev support is required, but neither
: WARNING: was found. Please use the configure options to point us
: WARNING: to where we can find one or the other library
: error: Cannot continue
```

**Comment by rhc54** [comment]
Think I found it - I have updated the patch. Could you please try again? Truly appreciate your patience and help!

**Comment by lyu** [comment]
It builds fine now! Thank you for addressing such an uncommon corner case so fast.
Please @ me when the PR for prrte is ready, I will also test it.

**Comment by rhc54** [comment]
Hooray! Again, thanks for you patience and help! I am waiting for the original author of that code to review it (hopefully tomorrow) - once that is okay, I'll port the changes to PRRTE.

**Comment by rhc54** [comment]
@lyu The changes have been ported and committed to PRRTE if you would like to verify them.

**Comment by lyu** [comment]
@rhc54 prrte also builds fine now, thanks!
