### ISSUE TITLE
Assertion `mutex->__data.__owner == 0' failed in examples/asyncgroup. 

### ISSUE THREAD

**Issue by darbyShaw** [openpmix/openpmix#2683]
### What version of the PMIx Reference Library are you using? 
git master @ 813d8ba6bc938fc87ed5316fa47a02571cf3b03a

### Describe how PMIx was installed 
git clone

### Please describe the system on which you are running

* Operating system/version: Oracle Linux Server release 8.6
* Computer hardware: x86_64
* Network type:

-----------------------------

## Details of the problem

I am trying to run the asyncgroup example using examples/asyncgroup.c.
I run prte as follows:
```shell
shell$ prte --host node086:28,node087:28 --report-pid -
```
I run the asyncgroup example as follows:
```shell
shell$ prun -n 4 --display bind --pid 922846 asyncgroup
[node086:909259] MCW rank 1 is not bound (or bound to all available processors)
[node086:909259] MCW rank 2 is not bound (or bound to all available processors)
[node086:909259] MCW rank 3 is not bound (or bound to all available processors)
[node086:909259] MCW rank 0 is not bound (or bound to all available processors)
[909339] Client ns prte-login1-926103@1 rank 2: Running
[909340] Client ns prte-login1-926103@1 rank 3: Running
[909338] Client ns prte-login1-926103@1 rank 1: Running
[909341] Client ns prte-login1-926103@1 rank 0: Running
Client prte-login1-926103@1:0 universe size 72
Client prte-login1-926103@1:2 universe size 72
Client prte-login1-926103@1:3 universe size 72
Client prte-login1-926103@1:1 universe size 72
prte-login1-926103@1:3 waiting to be invited
prte-login1-926103@1:2 waiting to be invited
0 executing Group_invite
prte-login1-926103@1:0 INVITED, BUT LEADER
Client prte-login1-926103@1:2 INVITED by source prte-login1-926103@1:0
prte-login1-926103@1:2 ACCEPTING INVITE
Client prte-login1-926103@1:3 INVITED by source prte-login1-926103@1:0
prte-login1-926103@1:3 ACCEPTING INVITE
[node086:909341] [prte-login1-926103@1:0] group nmembers = 3 and group accepted = 2
Client prte-login1-926103@1:0 NOTIFIED with status -161
[node086:909341] [prte-login1-926103@1:0] group nmembers = 3 and group accepted = 3
[node086:909341] [prte-login1-926103@1:0] group invite completed
[node086:909341] [prte-login1-926103@1:0] calling group invite callback
lt-asyncgroup: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
```

**Comment by rhc54** [comment]
I'm not hitting that specific error, but I have found a few bugs in that code path. Working on it now.

**Comment by darbyShaw** [comment]
Probably the same pmix_group_tracker_t cb is getting deleted after the first accepted invitation.

**Comment by rhc54** [comment]
Possibly - but the problem I'm seeing is in the event registration code. Somehow, the registration for invite-accepted is being lost. Trying to decipher why.

**Comment by darbyShaw** [comment]
This might not be related to the above error but related to the code path.
In function PMIx_Group_invite_nb, while notifying group invitations (PMIX_GROUP_INVITED) using  PMIx_Notify_event, the callback function op_cbfunc is passed an object of type pmix_cb_t but it expects pmix_group_tracker_t, because of which the the thread waiting for completion never gets signalled.

**Comment by rhc54** [comment]
Yeah, I fixed those problems and the invite/join code path is now complete. I'm working on the subsequent group-wide fence operation - it isn't correctly computing completion. Hopefully have this later today.

**Comment by rhc54** [comment]
Got it working - fixes are in https://github.com/openpmix/openpmix/pull/2685
