### ISSUE TITLE
Official tarball of 4.2.0 does not configure without flex installed

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2701]
### What version of the PMIx Reference Library are you using?
4.2.0 

### Describe how PMIx was installed

official release tarball from https://github.com/openpmix/openpmix/releases/download/v4.2.0/pmix-4.2.0.tar.bz2

### Please describe the system on which you are running

* Operating system/version: Rocky 8

-----------------------------

## Details of the problem

```
$> cd pmix-4.2.0/build
$> ../configure 
[...]
checking for flex... no
checking for lex... no
: WARNING: PMIx requires Flex to build from sources that were not
: WARNING: fully pre-processed (e.g., an official release tarball),
: WARNING: but Flex was not found. Please install Flex into
: WARNING: your path and try again
: error: Cannot continue
```

Is the tarball I used not the official release tarball mentioned in the warning message?

**Comment by moschny** [comment]
This fixes it:
```diff
--- pmix-4.2.0/configure.ac.orig	2022-07-25 16:17:24.000000000 +0200
+++ pmix-4.2.0/configure.ac	2022-08-22 19:34:28.364520338 +0200
@@ -221,7 +221,7 @@
 fi
 # check for Flex
 AC_PROG_LEX(noyywrap)
-if test "x$LEX" != xflex && test ! -e $PMIX_TOP_SRCDIR/util/keyval/keyval_lex.c; then
+if test "x$LEX" != xflex && test ! -e $PMIX_TOP_SRCDIR/src/util/keyval/keyval_lex.c; then
     AC_MSG_WARN([PMIx requires Flex to build from sources that were not])
     AC_MSG_WARN([fully pre-processed (e.g., an official release tarball),])
     AC_MSG_WARN([but Flex was not found. Please install Flex into])

```

**Comment by rhc54** [comment]
Yeah, I just saw that - funny as we have been releasing with that configure check since Day 1, and nobody hit the problem until now. I'll fix it, but will likely hold off on releasing a v4.2.1 for a little longer in case other problems trickle in.
