### ISSUE TITLE
v4.2 GDS issue with singleton spawn

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#2705]
### What version of the PMIx Reference Library are you using? 

 * OpenPMIx `v4.2` branch at 8cb6f58fe074efde0239aa4567854742223ab1a9
 * PRRTE `master` branch at https://github.com/openpmix/prrte/commit/8d735f530d6ad237d95e9e821b6ab22fbc17243a and `v3.0` branch at https://github.com/openpmix/prrte/commit/b29abde61c618de28f6a4c181e8c28f68e332969
 * Open MPI `main` branch at https://github.com/open-mpi/ompi/commit/5575c860048dd92004f111a6bc47b121b9d29046 (with both https://github.com/open-mpi/ompi/pull/10688 and https://github.com/open-mpi/ompi/pull/10695 cherry-picked into the branch since they have not been merged in yet)

Testing note on [this comment](https://github.com/open-mpi/ompi/pull/10688#issuecomment-1222706232)

### Describe how PMIx was installed 

Built with Open MPI `main` and manually adjusted the submodule pointers.

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4
* Computer hardware: ppc64le
* Network type: Single node shared memory

-----------------------------

## Details of the problem

Using PRRTE `master` and OpenPMIx `master` we have been able to get singleton `MPI_Comm_spawn` working. However, if we move to OpenPMix `v4.2` then it fails. See https://github.com/open-mpi/ompi/pull/10688

The MPI tests I'm using are located [here](https://github.com/open-mpi/ompi-tests-public/pull/20)
```shell
shell$ mpirun --np 1 ./simple_spawn ./simple_spawn
Spawning './simple_spawn' ... OK
shell$ ./simple_spawn ./simple_spawn
[f5n18:3788975] PMIX ERROR: PROC-ENTRY-NOT-FOUND in file server/pmix_server.c at line 3588
[f5n18:3788914] pml_ucx.c:191  Error: Failed to receive UCX worker address: Take next option (-46)
[f5n18:3788914] OPAL ERROR: Error in file dpm/dpm.c at line 480
```

I noticed that if I force the `hash` GDS component that it works correctly
```shell
shell$ export PMIX_MCA_gds=hash
shell$ ./simple_spawn ./simple_spawn
Spawning './simple_spawn' ... OK
```

So this seems to only impact the singleton spawn case, and is related to the GDS component (verbose output indicates that it is using `ds21`)

**Comment by rhc54** [comment]
Is it the singleton or the child that is complaining?

**Comment by rhc54** [comment]
Oh, and what key are they looking for?

**Comment by rhc54** [comment]
Just off the top of my head: I'd guess that the error comes from the child and that it is looking for a modex key. The problem looks to be in the dpm code - once you have spawned the `prte` server, you have to `PMIx_Commit` the singleton's modex data to it so the children can look it up.

**Comment by jjhursey** [comment]
It looks like modex information (if I force `OMPI_MCA_pml=ob1` it ends up failing in the modex in the btls instead of UCX). From what I can tell it is the child that is complaining (in addition to the server).

**Comment by jjhursey** [comment]
It looks like we are calling `PMIx_Commit()` just after the server starts:
 * https://github.com/open-mpi/ompi/blob/main/ompi/dpm/dpm.c#L2138-L2139

**Comment by rhc54** [comment]
Okay, here's the easiest solution. Once you detect that you are a singleton, push `PMIX_MCA_gds=hash` into your environment. This will make no difference to the singleton as that is all it can use, but it will cause `prte` to restrict itself to the hash, which will force all child procs to use their hash components.

See if that works.

**Comment by jjhursey** [comment]
Yeah, that works. I'll post a PR to OMPI to make that change.

It bugged me that it worked with OpenPMIx `master` but not the `v4.2` branch. Is that because `dstore` is not in the `main` branch anymore so I'm effectively just using `hash` there?

**Comment by rhc54** [comment]
Correct. The problem with dstore is that it is way behind in how to handle anything other than the original job info. The hash component is far more versatile. Once we get to PMIx v5, dstore will go away and we will have a shmem hash component instead - will solve many problems.
