### ISSUE TITLE
PMIx_Info_string needs PMIx_Init or PMIx_server_init

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2723]
Version: 4.2.0

----

To me it looks like `PMIx_Init` or `PMIx_server_init` needs to be called before `PMIx_Info_string` can be used to pretty print PMIx info. At least I get segfaults if not doing so.

Is this intended and is there a strong technical reason for that?

I mainly use this nice new function to create debugging output and currently it seems not possible to use it to print the info I pass into one of the both init functions before the call or after it failed. So I cannot print the passed info that perhaps lead to the fail, which makes it kind of a chicken and egg thing.

**Comment by rhc54** [comment]
Yeah, that's a good point. I can try to see if there is a way to expose that portion of the library prior to init. No promises, but I'm willing to take a gander at it.

**Comment by krempel-pt** [comment]
Great, many thanks.
