### ISSUE TITLE
Intermittent spawn hang in 4.x series

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#2735]
### What version of the PMIx Reference Library are you using? 

Testing with Ubuntu 22.04

Status   | Open MPI Release | OpenPMIx             | Container              |
-------- | ---------------- | -------------------- | ---------------------- |
:fire:   | Ubuntu v4.1.2    | 4.1.2 (apt external) | Dockerfile-ompi-ubuntu |
pass   | OMPI v4.1.2      | 3.2.3 (internal)     | Dockerfile-ompi-ubuntu-release |
:fire:   | OMPI v4.1.2      | 3.2.3 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.2      | 4.1.0 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.2      | 4.1.2 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.2      | 4.2.0 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.2      | 4.2.1rc1 (external)  | Dockerfile.ompi-ubuntu-blend |
pass   | OMPI v4.1.4      | 3.2.3 (internal)     | Dockerfile-ompi-ubuntu-release |
pass   | OMPI v4.1.4      | 3.2.3 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.4      | 4.1.0 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.4      | 4.1.2 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.4      | 4.2.0 (external)     | Dockerfile.ompi-ubuntu-blend |
:fire:   | OMPI v4.1.4      | 4.2.1rc1 (external)  | Dockerfile.ompi-ubuntu-blend |

Notes:
 * OpenPMIx 4.1.1 not tested because it is not compatible with the system provided hwloc (hwloc 2.7.0)
   - Exclusion added in https://github.com/openpmix/openpmix/pull/2447
   - Exclusion removed with a fix in https://github.com/openpmix/openpmix/pull/2453

### Describe how PMIx was installed 

The test setup is in the repo below:
 * https://github.com/jjhursey/ompi-mpi4py-spawn-test-matrix

### Please describe the system on which you are running

* Operating system/version: MacOS 12.5.1
* Computer hardware: x86_64
* Network type: shared memory

-----------------------------

## Details of the problem

The mpi4py project noticed an occasional hang when testing the version of Open MPI and OpenPMIx shipped with Ubuntu 22.04. I helped them identify this intermittent failure, which seemed to point to OpenPMIx. So I did some further testing and the results are in the test matrix at the top of this ticket. It seems to point to a regression between the v3.x and v4.x series.

The Dockerfiles are noted so you can inspect how everything was built.

Unfortunately, I ran out of time before I could try to define a PMIx-only test case. Maybe something that calls `PMIx_Spawn` with some `PMIx_Connect` calls might do the trick. It may be something in the Open MPI external component in those releases that needs adjusting for v4, but I don't know.

**Comment by rhc54** [comment]
I'll take a look at this - I believe I can create a suitable PMIx-only reproducer. Last I looked into this, the code was hanging in the publish/lookup exchange, which is why I had proposed that OMPI stop using that codepath, replacing it with the PMIx_Group method.

I'll mock up what you currently do to ensure I have a reproducer, and then I might try my proposed replacement. Making publish/lookup work more reliably is desirable, but probably not the optimal long-term solution.

**Comment by rhc54** [comment]
😆 Actually, we already have the PMIx-only reproducer - it is sitting right inside PRRTE in the `test` subdirectory as `loop_spawn.c` and `loop_child.c`. This is what we used in the past for comm_spawn problems, only then using MPI calls instead of PMIx.

I'll test them as-is, but may have to modify a bit as the current code has `loop_spawn` loop over calls to PMIx_Spawn and PMIx_Connect, which isn't quite what you are doing as you restart the parent process on each iteration.

Still, we have something we can use to start with - and I'll add the remaining calls that are in your `dpm.c` so we fully mimic the OMPI lifecycle.

**Comment by dalcinl** [comment]
> which isn't quite what you are doing as you restart the parent process on each iteration.

Please note that each run of mpi4py tests perform many spawn calls, one for each of the 40 individual tests. Perhaps you should try the same with your `loop_{spawn|child}.c` tests, that is, run them within an outer loop in bash as Josh did?.

**Comment by rhc54** [comment]
You wouldn't do that with the `loop_spawn` test as the test itself runs many iterations of spawn/connect. But yes, I'll run a number of tests that do a single spawn/connect.  As I said, I intend to mimic exactly the PMIx calls in the OMPI spawn scenario, which involves more than just spawn/connect. I also want to see if we pass the `loop_spawn` test as that has been an excellent diagnostic for us in the past - we usually run one instance of the parent and let it execute 1000 spawn/connect sequences.

Looking at the code in `dpm.c`, I'm not entirely convinced the problem resides solely in PMIx (there are a couple of other places where hangs have occurred in the past) - but it's a good place to start.

**Comment by rhc54** [comment]
Hmmm...well, I can run 1000 iterations of loop spawn and 100 iterations of simple_spawn without any problems. Both programs involve calling `PMIx_Spawn`, then doing a `PMIx_Connect` between the parent and child jobs, and then doing a `PMIx_Disconnect` between the parent and child jobs before calling `PMIx_Finalize`.

I therefore believe we can rule out those functions as being the source of the problem, which is pretty much what I expected - they get used by a broad audience on a regular basis, so I would have expected to hear complaints elsewhere. This leaves three possibilities:

1. the publish/lookup exchange
2. the `ompi_comm_nextcid` function
3. the `ompi_comm_activate` function

These have all been known to have problems in the past. I'll investigate them next.

**Comment by rhc54** [comment]
I can't speak to the earlier versions of OMPI, but I can say that the head of OMPI main, when running with the heads of the PMIx and PRRTE master branches, performs flawlessly for 1000 iterations of the `simple_spawn` MPI example.

I'm afraid that is all I am able to pursue. I don't support earlier versions of OMPI (or usually _any_ versions of OMPI, really) nor is there any interest in looking at the earlier versions of PMIx as the focus now is on the v4.2 and v5 branches (and the earlier versions don't support head of OMPI main or v5 branches anyway). If I have some free time someday, I might look at finally upgrading the dpm code to be more efficient by using the newer interfaces, but that's for some other day.

If you folks are motivated to pursue it, I suggest doing so over in the OMPI arena. I suspect you'll find it is something in ORTE (supporting publish/lookup) or the `ompi_comm_nextcid` function as both have been flaky in the past.
