### ISSUE TITLE
4.2.1: no man pages

### ISSUE THREAD

**Issue by kloczek** [openpmix/openpmix#2755]
Looks like a7698ed7 commit removed man pages.
Why? 🤔

**Comment by rhc54** [comment]
We no longer provide man pages - they are being replaced by help output in an upcoming sub-release.

**Comment by kloczek** [comment]
Moment so you merged documentation into binaries?

**Comment by rhc54** [comment]
No, we replaced "man foo" with better "foo --help" support. It is more obvious in PRRTE as the transition is more complete there - we still have a ways to go over here.

**Comment by kloczek** [comment]
From where is taken text displayed by that comamnd?
Why you are changing some standards about providing basic documentation? 🤔

**Comment by kloczek** [comment]
https://en.wikipedia.org/wiki/Man_page
"A man page (short for manual page) is a form of [software documentation](https://en.wikipedia.org/wiki/Software_documentation) usually found on a [Unix](https://en.wikipedia.org/wiki/Unix) or [Unix-like](https://en.wikipedia.org/wiki/Unix-like) [operating system](https://en.wikipedia.org/wiki/Operating_system). Topics covered include [computer programs](https://en.wikipedia.org/wiki/Computer_program) (including [library](https://en.wikipedia.org/wiki/Library_(computing)) and [system calls](https://en.wikipedia.org/wiki/System_call)), formal standards and conventions, and even abstract concepts. A [user](https://en.wikipedia.org/wiki/User_(computing)) may invoke a man page by issuing the man [command](https://en.wikipedia.org/wiki/Command_(computing))."

For example:
```console
$ /usr/bin/plookup --help
plookup (PMIx) 4.2.0

Usage: plookup [OPTION]...
PMIx Lookup tool


/*****      General Options      *****/

-h|--help                            This help message
-h|--help <arg0>                     Help for the specified option
-v|--verbose                         Enable typical debug options
-V|--version                         Print version and exit

   --pid <arg0>                      PID of the daemon to which we should connect (int => PID or file:<file>
                                     for file containing the PID
   --tmpdir <arg0>                   Set the root for the session directory tree
   --timeout <arg0>                  Max number of seconds to wait for data to become available
   --wait                            Wait for data to be available

Report bugs to https://github.com/openpmix/openpmix
/usr/bin/plookup: command line error (OPERATION-SUCCEEDED)
```
and what was in man page:
```man
plookup(1)                                                                     Open PMIx                                                                     plookup(1)

NAME
       plookup - Request the value of one or more keys

SYNOPSIS
              plookup [ options ] [ keys ]

DESCRIPTION
       plookup  will  request the value of the specified keys.  This requires that plookup connect to an appropriate server - the tool will automatically attempt to do
       so, but options are provided to assist its search or to direct it to a specific  server.   Reserved  keys  must  be  provided  in  their  string  form  -  e.g.,
       “pmix.job.term.status” as opposed to the key’s name of “PMIX_JOB_TERM_STATUS”.

OPTIONS
       plookup supports the following options:

              -h|--help                This help message
              -p|--pid <arg0>          Specify starter pid
              -t|--timeout             Max number of seconds to wait for data to become
                                       available
              -v|--verbose             Be Verbose
              -w|--wait                Wait for data to be available

AUTHORS
       The OpenPMIx maintainers – see https://github.com/openpmix/openpmix or the file AUTHORS.

2021-08-17                                                                                                                                                   plookup(1)
```
I don't think that level of provided informations is close to "identical".
In man page is shotr explanation FOR WHAT is that command!!

I'll try to ask other way: did you notice any problem with those man pages that they've have been removed? 🤔 
And quote from gawk info pages "Documentaion is like sex. When it is good it is really good. When it is bad it is better than nothing".
Really .. please restore those man pages.

BTW .. what is that `/usr/bin/plookup: command line error (OPERATION-SUCCEEDED)`?

**Comment by rhc54** [comment]
Please - enough. I am not going to restore man pages that I cannot maintain. This subject is closed.

**Comment by kloczek** [comment]
Thank you very much for ignoring my questions.
