### ISSUE TITLE
Can't find address using srun

### ISSUE THREAD

**Issue by BDHU** [openpmix/openpmix#2786]
## Background information

When I try to test pmix installation using the following command

```bash
srun --mpi=pmix -n2 -N2 ./openpmix/build/test/pmix_client -n 2 --job-fence -c
```

 it shows the following error:

```test
slurmstepd: error:  mpi/pmix_v5: _pmix_p2p_send_core: node4 [0]: pmixp_utils.c:408: Can't find address for host node5, check slurm.conf
slurmstepd: error:  mpi/pmix_v5: _pmix_p2p_send_core: node4 [0]: pmixp_utils.c:408: Can't find address for host node5, check slurm.conf
```

My slurm configuration:

```bash
# COMPUTE NODES
NodeName=node4 NodeHostname=node4 NodeAddr=10.0.1.227 CPUs=80 Boards=1 SocketsPerBoard=2 CoresPerSocket=20 ThreadsPerCore=2 Gres=gpu:4 State=UNKNOWN
NodeName=node5 NodeHostname=node5 NodeAddr=10.0.1.224 CPUs=80 Boards=1 SocketsPerBoard=2 CoresPerSocket=20 ThreadsPerCore=2 Gres=gpu:4 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
```

Running `srun --mpi=list` gives:

```text
MPI plugin types are...
	pmix
	pmi2
	cray_shasta
	none
specific pmix plugin versions available: pmix_v5
```

Runing the command `srun -w node4 --pty bash` shows no error.

### What version of the PMIx Reference Library are you using? 

My PMIx version is c685c17e145bba6ad53e7d36d0445339a87cf6ea.

I have no idea how to fix this issue. Any hint would be useful!

**Comment by rhc54** [comment]
I'm afraid I have no idea as the error you are quoting comes from the Slurm pmix_v5 plugin and not from the PMIx library itself. You should ask SchedMD about it.
