### ISSUE TITLE
Question: Get PMIX_UNIV_SIZE is not working in 4.2.1 (but in master)

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2791]
### What version of the PMIx Reference Library are you using?
4.2.1 and current master (https://github.com/openpmix/openpmix/commit/9f297ced5093868a4d3138ece0df1822348531dd)

### Describe how PMIx was installed
4.2.1 from tarball, master as git clone

### Please describe the system on which you are running

* Operating system/version: Fedora 36
* Computer hardware: x86_64
* Network type: local
-----------------------------

## Details of the problem

Hello once again.

With our PMIx host server implementation I stumbled over the problem with 4.2.1 that getting `PMIX_UNIV_SIZE` always returned `NOT_FOUND` while getting `PMIX_JOB_SIZE` works. Both values are set during namespace registration.

With the current master, it is working again, so the problem seems to already be found and fixed, even when I was not able yet to point on the commit fixing it.

Since the effect of the problem that I see is very obvious (many of the tests and examples do this call at the very beginning), I cannot believe that it could be ignored during pre-release testing. This leads me to the assumption, that we are doing something different that other implementations, and that there is a way to initialize the server and register a namespace so this is working with the 4.2.1 release version, too.

It would be great, if someone could give me a hint about how I can make my initialization 4.2.1 compatible, so we do not need to wait for the next release until we can declare 4.2 branch ready for production with our server.

I add a reproducer for the problem in a minute, many thanks in advance.

**Comment by krempel-pt** [comment]
How to reproduce:
1. Compile both, server and client with the same pmix version
1. Start the server binary
1. Set the Environment that it shows in a shell
1. Run the client in that shell

client output with 4.2.1:
```
Client 232483: Running
Client ns pspmix_nspace rank 0 pid 232483: Running
Client ns pspmix_nspace rank 0: PMIx_Get universe size failed: NOT-FOUND
Client pspmix_nspace:0 job size 1
Client ns pspmix_nspace rank 0: Finalizing
Client ns pspmix_nspace rank 0:PMIx_Finalize successfully completed
```

client output with https://github.com/openpmix/openpmix/commit/9f297ced5093868a4d3138ece0df1822348531dd
```
Client 279876: Running
Client ns pspmix_nspace rank 0 pid 279876: Running
Client pspmix_nspace:0 universe size 1
Client pspmix_nspace:0 job size 1
Client ns pspmix_nspace rank 0: Finalizing
Client ns pspmix_nspace rank 0:PMIx_Finalize successfully completed
```

**Comment by krempel-pt** [comment]
I just found an email about 4.2.2rc2 that arrived a five hours ago, but the link in there results in github's 404 page. :see_no_evil:

**Comment by rhc54** [comment]
I don't have an easy way to test v4.2.1 as part of PRRTE any more since PRRTE now requires a minimum of v4.2.2. Looking at PRRTE, I don't see anything special about registering `PMIX_UNIV_SIZE`, and it works just fine with PMIx v4.2.2 and master branches.

I then went and built PMIx v4.2.1 and ran it with the test/simple/simptest.c server using a client that "gets" univ_size:
```shell
$ ./simptest -n 2 -e ../../examples/client
Testing version OpenPMIx 4.2.1rc1, repo rev: v4.2.1 (PMIx Standard: 4.2, Stable ABI: 0.0, Provisional ABI: 0.0)
[Ralphs-iMac-2.local:13646] PMIX ERROR: ERROR in file dstore_base.c at line 1709
[Ralphs-iMac-2.local:13646] PMIX ERROR: ERROR in file dstore_base.c at line 1709
Collecting inventory
Inventory collected: 0
Client 13660: Running
Client 13661: Running
Client ns foobar rank 0 pid 13660: Running
Client ns foobar rank 1 pid 13661: Running
Client foobar:0 topology loaded
Client foobar:0 universe size 2
Client foobar:0 num procs 2
Client foobar:1 topology loaded
Client foobar:1 universe size 2
Client foobar:1 num procs 2
Client ns foobar rank 0: PMIx_Get foobar-0-local returned correct
Client ns foobar rank 0: PMIx_Get foobar-1-local returned correct
Client ns foobar rank 1: PMIx_Get foobar-0-local returned correct
Client ns foobar rank 0: Finalizing
Client ns foobar rank 1: PMIx_Get foobar-1-local returned correct
Client ns foobar rank 1: Finalizing
Client ns foobar rank 0:PMIx_Finalize successfully completed
Client ns foobar rank 1:PMIx_Finalize successfully completed
SIMPTEST: Model event handler called with status -147(PMIX MODEL DECLARED)
	pmix.pgm.model:	PMIX
	pmix.mdl.name:	test
	pmix.evname:	SIMPTEST-MODEL
Test finished OK!
```
Note that the rank used for the call to `PMIx_Get` was `WILDCARD` - you might check to see that your example is doing so. Later versions were smart enough to deal with session info directly, and so the rank wasn't a factor. Not sure about the ERROR_LOG coming from dstore_base, but it is likely a missed debug print statement.

**Comment by krempel-pt** [comment]
As you can see [here](https://github.com/krempel-pt/openpmix/commit/9127ef26d655985efcc2d586878dc697c3b3742f#diff-15ecaa7d003ee1ded516c6e9869989dc14698d334f8f56b76837099d63a2f636R37-R43) the reproducer uses the `WILDCARD` rank in `PMIx_Get`

I just tried the 4.2 branch (b4a55542) and it does not work. Since it does work with the master branch (9f297ce), I guess there is still something in master that should be included into 4.2.

**Comment by rhc54** [comment]
`PMIX_UNIV_SIZE` is session-level info - I don't see it in your session info array being passed by your server.

There is a distinct difference between the v4 branches and the master branch in that v4 has the "dstore" shared memory system. This system is out-of-date and does not support the various info levels - it only treats everything as "job level". This requires special processing to compensate.

I can look at it a bit more, but you probably should pass the universe size correctly and see if that resolves the problem.

**Comment by krempel-pt** [comment]
Ok, that was the hint that I needed, thanks.

Actually I thought that I already had tried that before, but perhaps I just planned to do. However, interesting that this changed at some point.

I'm fine with providing all the information in the session info array, actually this is more consistent, but the standard allows explicitly to pass them in individual info fields, too:
>Session-realm information may be passed as individual `pmix_info_t` entries, or as part of a `pmix_data_array_t` using the `PMIX_SESSION_INFO_ARRAY` attribute.

Perhaps it would have been clearer to require the use of a session info array.

Thanks, Ralph, for taking the time.

**Comment by rhc54** [comment]
I think there actually is something here...getting a feeling of it.  Key is that you are passing the univ size as a separate entry, and then (ordering may be important!) passing the rest of the session info in an array. Need to poke some more at this, but it may take a bit to work around the pain med "fog".
