### ISSUE TITLE
PMIx_server_define_process_set() returns strange status

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2818]
Version: 4.2.2

The function `PMIx_server_define_process_set()` seems to return uninitialized values.

I did create a reproducer calling it with the result:
> failed to create process set: ERROR STRING NOT FOUND (-799030184)

(it's not every time, but very often, so 3-5 tries should show the error at least once)

**Comment by krempel-pt** [comment]
Little side comment: The standard tells us that `PMIx_server_define_process_set()` should
> Returns PMIX_SUCCESS or a negative value indicating the error

So even without the issue described here, the lines 
```c
    if (PMIX_SUCCESS == rc) {
        rc = PMIX_OPERATION_SUCCEEDED;
    }
```
should be removed from `src/server/pmix_server.c:3001`.

**Comment by rhc54** [comment]
It's an uninitialized value, which is easily fixed. We typically do return "operation succeeded" when we don't execute a callback, but this function isn't available as a non-blocking form and so it should just be "success". Same is true of "delete_process_set".

Thanks for pointing it out!
