### ISSUE TITLE
Don't free stuff in destruct that are not allocated in construct.

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2891]
In current master, the function `pmix_hwloc_destruct_cpuset(pmix_cpuset_t *src)` that stands behind `PMIx_Cpuset_destruct()` when using `hwloc` is defined like this:
```
{
    if (NULL == src || NULL == src->source ||
        0 != strncasecmp(src->source, "hwloc", 5)) {
        return;
    }

    if (NULL != src->bitmap) {
        hwloc_bitmap_free(src->bitmap);
        src->bitmap = NULL;
    }
    free(src->source);
    src->source = NULL;
}
```

I do have some problems with that function:

1. It assumes, that the user has set `src->source` to something that can be freed.

I would tend to say, that this is an invalid assumption, most users will probably do something like this:

```
pmix_cpuset_t cpuset;
PMIx_Cpuset_construct(&cpuset);
cpuset.source = "hwloc";
cpuset.bitmap = hwloc_bitmap_alloc();
...
hwloc_bitmap_free(cpuset.bitmap);
PMIx_Cpuset_destruct(&cpuset);
```

2. It assumes, that the user might have allocated the bitmap but not freed it by itself or if he already freed it, that he set the pointer to NULL again. Even if this would be good style in general, the above example does not look to me as if it could break things.

In general me as a API user do never expect that a destruct function frees things that the corresponding construct function did not have allocated and vice versa.

So I think, either the `PMIx_Cpuset_destruct()` function should leave both values alone, lastly making it a noop or maybe better, extend the `PMIx_Cpuset_construct()` function or provide a `PMIx_Cpuset_load()` to load the source string into the struct and then manage the memory for storing it. The management of the bitmap I would push completely to the user, as he is the only one that can do that properly. You can never know, if the user wants to use the bitmap at different places, too, and how long it needs to be valid.

**Comment by rhc54** [comment]
Hmmm...troubling. The macro this function replaces has always free'd the source field and destructed the bitmap, so this would be a significant change in behavior that will likely leave memory leaks in existing code. We can create a "load" function if that helps - though note that the cpuset is intended to be provided via PMIx and not directly by the user. The server would be the exception as it has to pass a pmix_cpuset_t into PMIx, but that is a limited case.

I guess it comes down to the purpose of the pmix_cpuset_t struct. The intended purpose is to provide a mechanism by which PMIx  can communicate cpuset's to the application (e.g., via PMIx_Get). It wasn't intended to serve as a general purpose struct, though I guess someone is free to use it as such.

So maybe the answer is to create a "load" function as you suggest, and better document what the destruct is going to do?

**Comment by krempel-pt** [comment]
I understand the concerns about breaking existing code. Perhaps your solution is a good compromise.

For me this is in fact a slight drawback of moving from macros to functions. Even with macros it feels better to me if a destruct function provided does not touch memory not owned by the library. But it is more relaxed since the API user always has direct access to the macro via the header files and so if anything breaks, he can easily analyse the problem and circumvent is. With functions this is not the same, it should never be needed to look into the source code of a function to use it properly (even if the possibility to do that is of cause one of the biggest advantages of OSS :partying_face:). So yes, good documentation is the least we should do in that case.

My solution for the moment is to set `source` and `bitmap` to `NULL` before calling `PMIx_Cpuset_destruct()`, actually making it a noop for the moment.

**Comment by rhc54** [comment]
> My solution for the moment is to set `source` and `bitmap` to `NULL` before calling `PMIx_Cpuset_destruct()`, actually making it a noop for the moment.

That is the accepted method we employ in our projects - alternative is to just not call "destruct". If you think about it, the name of the function indicates what it will do - it destructs the provided object, releasing all included data. It mirrors what would happen if you called a C++ destructor. If you don't want to destruct the object, then don't call it. If there is a specific field you want to protect, then clear it before calling.

I'll add the load function (probably do the same for other data types) and try to add some words to the header.

**Comment by rhc54** [comment]
Closing this as we have added load function and others to ensure symmetry in handling PMIx structs.
