### ISSUE TITLE
could use runtime detection of problematic hwloc with Intel Ponte Vecchio accelerators

### ISSUE THREAD

**Issue by hppritcha** [openpmix/openpmix#2893]
It appears that hwloc 2.7.x and older don't work right with Intel processors sporting Ponte Vecchio accelerators.  For example, lstopo segfaults.  prte also segfaults in a similar way.

It would be useful to have some runtime check in either prte or pmix to see if the hwloc version it is linked against is too old for such processors.

I do not know a good way to do this runtime check at the moment.

**Comment by rhc54** [comment]
I know how to do it (or at least, I believe I do) - I'll take a crack at it.

**Comment by rhc54** [comment]
I believe we concluded on the OMPI ticket that we won't do this as (per discussion on the PMIx telecon) other subsystems will be segfaulting when using HWLOC, so our trying to provide a "canary" really doesn't help enough to justify the amount of effort it would require.
