### ISSUE TITLE
PMIx_Get returns PMIX_ERR_NOT_FOUND without waiting for PMIx_Put.

### ISSUE THREAD

**Issue by rakhmets** [openpmix/openpmix#2904]
### What version of the PMIx Reference Library are you using? 

I'm using internal PMIx version from Open MPI v4.1.0.

### Describe how PMIx was installed 

PMIx was built and installed from sources.

### Please describe the system on which you are running

The problem was found on different systems with different Linux version, even on a single node run.

* Operating system/version:
* Computer hardware: 
* Network type:

-----------------------------

## Details of the problem

There are PMIx API calls during `MPI_Init` procedure. Different processes exchange data during the initialization. In particular, a process publishes data using `PMIx_Put`, and another process trying to obtain the data using `PMIx_Get`. If I understand correctly `PMIx_Get` is a blocking operation. However, sometimes the function returns `PMIX_ERR_NOT_FOUND`.
There is `PMIx_Fence` in `MPI_Init`, which is used depending on parameters. And if the fence is enabled, there is no issue. Moreover, if I change the code to re-request the data after the timeout, there is no issue too.

Thus, all the symptoms point to a data race. However, I don't understand, how is this possible with blocking operation retrieving the data. Could you please help me to solve the issue.

**Comment by rhc54** [comment]
Afraid there isn't enough info here to provide much help. You'd need to tell us what key is returning "not found", and what timeout you are talking about. I suspect the problem isn't a race condition in PMIx but rather something to do with how OMPI is using it. If you can provide directions on how to reproduce it, that is also helpful.

**Comment by rakhmets** [comment]
The worker address is published here: https://github.com/open-mpi/ompi/blob/4a89f7adbe04a0c6945f12e7873a73a927d28d82/ompi/mca/pml/ucx/pml_ucx.c#L105

The attempt to receive the worker address is here: https://github.com/open-mpi/ompi/blob/4a89f7adbe04a0c6945f12e7873a73a927d28d82/ompi/mca/pml/ucx/pml_ucx.c#L175

The issue began to reproduce frequently after increasing the time of the initialization of UCX component.
This increased the probability of a situation where it is not possible to receive worker address.

**Comment by rhc54** [comment]
I'm afraid I can't follow that code very well - I'm not familiar with the PML in OMPI and don't know the sequence of function calls. I honestly am confused by the "initialization time" as I can't see how that is relevant in the OMPI MPI_Init scheme.

Here is what I can offer, and perhaps you can explain to me how UCX differs from this pattern. What OMPI does is to have all the transports initialize themselves early on in MPI_Init, each transport using `PMIx_Put` to add its endpoint info to a "bucket" being collected within the process. When MPI_Init reaches a certain point in the code flow, it calls `PMIx_Commit` to transmit the contents of that bucket to the local PMIx server, which is usually hosted in the runtime daemon that fork/exec'd the process.

Note that this is a deterministic point in the MPI_Init code - there is no variation in "initialization time" here. All endpoints _must_ be posted prior to reaching this point in the code.

MPI_Init then calls `PMIx_Fence`, which can either collect and return all the buckets from the different processes (the default behavior for OMPI) or can simply act as a dataless barrier. Either way, you know that all the endpoints have been pushed to their local PMIx server and at least by default are locally available.

You then use `PMIx_Get` to retrieve them. If you are getting a "not found" response, then that would indicate that the remote process didn't "put" its contribution prior to the "commit" operation having executed in that process.

What is odd is that your comments imply that somehow UCX isn't following that OMPI paradigm, and that you may be attempting on-the-fly endpoint exchange during the course of execution? Is that what you are attempting to do? If so, that is an entirely different discussion and has nothing to do with "fence" operations.

**Comment by rakhmets** [comment]
`PMIx_Commit` is an asynchronous operation. Does it mean that we always need to call `PMIx_Fence` in `MPI_Init` after `PMIx_Commit`?

If so, then this code doesn't correspond to this statement:
https://github.com/open-mpi/ompi/blob/4a89f7adbe04a0c6945f12e7873a73a927d28d82/ompi/runtime/ompi_mpi_init.c#L678

There are parameters: `opal_pmix_base_async_modex` and `opal_pmix_collect_all_data`. The parameters controls calling the fence operation. Non-blocking fence is called followed by `opal_progress` by default. (Or blocking fence, if there is no non-blocking fence).
`opal_pmix_base_async_modex 1`, `opal_pmix_collect_all_data 0` - fence is not called.
`opal_pmix_base_async_modex 1`, `opal_pmix_collect_all_data 1` - fence is called in background, which means that fence is not followed by `opal_progress`.

I observed the issue in both cases.

**Comment by rhc54** [comment]
> PMIx_Commit is an asynchronous operation.

Yes it is - each process will do independently push their "bucket" to their local server.

> Does it mean that we always need to call PMIx_Fence in MPI_Init after PMIx_Commit?

Yes and no.

> opal_pmix_base_async_modex (default is 0) and opal_pmix_collect_all_data (default is 1).

 If you call "fence" and indicate that you want the data circulated during the fence operation, then you can call `PMIx_Get` _after_ the fence concludes and know that the data is available to be retrieved.

> opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 1 - fence is called in background, which means that fence is not followed by opal_progress.

I believe the intent was to loop on opal_progress at the end of mpi_init until the fence completes. The data will be collected during the fence operation and will be locally available upon completion of the fence. You cannot access the data using `PMIx_Get` until the fence has completed.

> opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 0 - fence is not called.

This is an error in the OMPI code - OMPI is not designed to allow you to completely skip the fence operation. It should be running in the background (i.e., a non-blocking fence), and then you loop on opal_progress at the end of mpi_init until the fence completes.

If you call "fence" and do _not_ circulate the data, then when you call `PMIx_Get` after the fence concludes you enter what is called "direct modex" operation - i.e., your local server has to contact the remote server hosting the process you are asking about to independently retrive that proc's "bucket". This procedure depends on the runtime for its timing and timeout behavior.

If this "direct modex" operation is what you are trying to use, then the next question is precisely how you are launching this application. Are you using OMPI's mpirun? Or Slurm's srun? Or...?

**Comment by rhc54** [comment]
One thing that occurs to me: you are using a fairly old version of PMIx (the embedded one in OMPI v4.x series is the PMIx v3.2 code). We know that the direct modex operation (which you are relying on) has problems in the older versions, but we spent some time on it and believe it is more reliable now in PMIx v4.2. Have you tried your use-case with an updated version of PMIx?

And if you are using mpirun, then you probably should test your use-case with OMPI main or v5 branch as there are problems with direct modex on the older versions of mpirun as well.

**Comment by rakhmets** [comment]
I'm using OMPI's mpirun to launch the test application. And non-default combination of the parameters is causing the issue (`opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 0`, or `opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 1`).

I tried to build OMPI with PMIx from master branch. The issue was still there.
Haven't try OMPI from main or v5 branch yet.

However, the combination  `opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 0` still leads to the case w/o fence (according to the code: https://github.com/open-mpi/ompi/blob/a05e16b6e951034c6c42ab228136914202f24fd5/ompi/runtime/ompi_mpi_init.c#L414)

**Comment by rhc54** [comment]
> However, the combination `opal_pmix_base_async_modex 1, opal_pmix_collect_all_data 0` still leads to the case w/o fence (according to the code:

Understood. What I'm trying to help you assess is where the problem might lie. We know that the `mpirun` and PMIx combination in OMPI main correctly executes the direct modex operation - we test it against every PR into the PMIx and PRRTE master branches. This is something we know did not work correctly in earlier versions. We can't know if it works in larger scale operation, or if there is some race condition just not showing up in our CI - so nothing is guaranteed.

Thus, if your use-case works in OMPI main, we have some confidence that the problem was indeed in one of those two codes and that it has been fixed. If it does not work in OMPI main, then we suspect that the problem lies in the OMPI code - it just cannot handle the async startup you are attempting.

Make sense? Can you please try OMPI main?

**Comment by rhc54** [comment]
Any update here?

**Comment by rakhmets** [comment]
Sorry for the delayed response.

I tried main branch. Unfortunately, I can't confirm or deny that the issue is fixed. Because, I can't reproduce the issue anymore, even with the version of OMPI which stably reproduced the issue.

I will update as soon as I get a stable reproducer again.

**Comment by rhc54** [comment]
Feel free to re-open if/when you are able to reproduce it again.
