### ISSUE TITLE
PMIx dstore issue ......

### ISSUE THREAD

**Issue by ZXRobotum** [openpmix/openpmix#2915]
### What version of the PMIx Reference Library are you using? 

openmpi-5.0.0rc9 from your homepage

### Describe how PMIx was installed 

I´ve got the SOURCE - Code and installed it on my machine with GNU C-Compiler 12.2 and following flags:
./configure --prefix=/usr/local/OpenMPI/Release_5.0.0rc9 --enable-heterogeneous --with-slurm --with-hwloc=/usr/local/hwloc/Release_2.9.0 --localedir=/etc/default --enable-mpi-fortran=yes --enable-mpi-java --with-jdk-dir=/HumanBrain.Projects/xCloud/HumanBrain.Packages/$NPU_ARCH/OpenJDK/jdk-21 --with-libevent-libdir=/usr/lib/x86_64-linux-gnu --with-libevent=/usr --with-pmix=internal --with-curl=/usr/include/x86_64-linux-gnu --with-curl-libdir=/usr/lib/x86_64-linux-gnu

### Please describe the system on which you are running

* Operating system/version:     Debian bookworm - Kernel: Debian 6.1.4-1 (2023-01-07) x86_64 GNU/Linux
* Computer hardware:               x86_64
* Network type:                          Ethernet - TCP/IP

-----------------------------

## Details of the problem

Today I was allowed to install the entire OpenMPI including hwloc & netloc again, because after the update to the new kernel today the SLURM cluster no longer worked.

Now I wanted to test OpenMPI alone and entered the following command:

mpirun -np 2 -v --allow-run-as-root uname -a 

The command was executed, but afterwards there was an error message that I can't do anything with. 

PMIX ERROR: NO-PERMISSIONS in file dstore_base.c at line 238

Could someone help me here?
Best regards from Berlin

Z. Matthias

**Comment by rhc54** [comment]
Could be the "allow-run-as-root" problem - try setting `PMIX_MCA_gds=hash` in your environment.

**Comment by ZXRobotum** [comment]
Perfect, than you very much. 
With this PMIX_MCA_gds=hash it's work.....
