### ISSUE TITLE
even NULL can trigger a “missing sentinel in function call” warning

### ISSUE THREAD

**Issue by afborchert** [openpmix/openpmix#2931]
## Background information
I am trying to compile a cloned version of OpenMPI including OpenPMIx  under Solaris 11.4 where I get compilation errors.
### What version of the PMIx Reference Library are you using? 
Commit 5bd97056ccd994c711fde4ac19aded8e4eac8285
### Describe how PMIx was installed 
OpenMPI cloned from current release, i.e. commit dd6b87590cd767f5ff2047ce117a4f16a216b628, followed by

```sh
export FC=/opt/ulm/dublin/cmd/gfortran
export CC=/opt/ulm/dublin/cmd/gcc
export CXX=/opt/ulm/dublin/cmd/g++
export AUTOMAKE_JOBS=8

cd ompi-master &&
   perl autogen.pl &&
   bash ./configure --prefix=/opt/ulm/dublin \
      --disable-silent-rules \
      --libdir=/opt/ulm/dublin/lib/amd64 \
      --enable-wrapper-rpath &&
   make DESTDIR=/home/pkgdev/dublin/openmpi/proto install
```

### Please describe the system on which you are running

* Operating system/version: Solaris 11.4
* Compiler: gcc 11.2.0
* Computer hardware: 64 bit x86 architecture
* Network type: not relevant here

-----------------------------

## Details of the problem

Compilation ends up with following error:

```
libtool: compile:  /opt/ulm/dublin/cmd/gcc -DHAVE_CONFIG_H -I. -I../../src/include -I../../include -iquote/home/pkgdev/dublin/openmpi/src/ompi-master/3rd-party/openpmix -iquote/home/pkgdev/dublin/openmpi/src/ompi-master/3rd-party/openpmix/src -I/home/pkgdev/dublin/openmpi/src/ompi-master/3rd-party/openpmix/include -I/home/pkgdev/dublin/openmpi/src/ompi-master/3rd-party/hwloc-2.7.1/include -I/home/pkgdev/dublin/openmpi/src/ompi-master/3rd-party/hwloc-2.7.1/include -D_REENTRANT -O3 -DNDEBUG -D_REENTRANT -finline-functions -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -Wextra -Werror -MT pmix_os_dirpath.lo -MD -MP -MF .deps/pmix_os_dirpath.Tpo -c pmix_os_dirpath.c  -fPIC -DPIC -o .libs/pmix_os_dirpath.o
pmix_os_dirpath.c: In function 'pmix_os_dirpath_destroy':
pmix_os_dirpath.c:195:9: error: missing sentinel in function call [-Werror=format=]
  195 |         filenm = pmix_os_path(false, path, ep->d_name, NULL);
      |         ^~~~~~
cc1: all warnings being treated as errors
```

This warning is delivered even if NULL is used if NULL is not of a pointer type. While gcc makes sure that <stddef.h> defines NULL as “(void*)0”, other header files might provide alternative definitions. This is the case for <iso/time_iso.h> under Solaris 11.4 which provides following code:

```c
#ifndef NULL
#if defined(_XPG7) && !defined(__cplusplus)
#define NULL    ((void *)0)
#else /* _XPG7 && !_cplusplus */
#if defined(_LP64)
#define NULL    0L
#else
#define NULL    0
#endif
#endif /* _XPG7 && !_cplusplus */
#endif
```

The symbol `_XPG7` gets defined if `_XOPEN_SOURCE` is defined to be 700. In that case we will get `0L`, otherwise `((void *)0)` which avoids the warning.

**Comment by afborchert** [comment]
I got it accidently wrong in the last sentence: NULL gets properly defined to `((void*)0)` if _XOPEN_SOURCE is defined to be 700. Otherwise we will end up with `0L`.

**Comment by afborchert** [comment]
Well, Solaris tries to conform to the POSIX standard, see https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap02.html. According to the POSIX standard, you need

```c
#define _XOPEN_SOURCE 700 /* Single UNIX Specification, Version 4 */
```

for a application conforming to the current POSIX standard. The problem is that Solaris tries to be upward-compatible to numerous POSIX-variants and earlier Solaris-specific features that are not compatible to POSIX. This should be usually sorted out by the configure script.

The warnings above vanish if `_XOPEN_SOURCE` is defined to 700. Alternatively, you should be able to replace `NULL` by `(void*) NULL` or by `(void*)0`. Please be aware that you have the same problem at base/pinstalldirs_base_expand.c:155.

**Comment by rhc54** [comment]
So let's try something simple - add `--disable-devel-check` to your configure line and let's see if things work.

**Comment by jsquyres** [comment]
@afborchert Another possibility: we could just disable the "sentinel" attribute on this function declaration when we're compiling on in this environment.  I.e., changing https://github.com/openpmix/openpmix/blob/6a7fa98e9aa7adfcd8945011e3b6cada5dfd28e5/src/util/pmix_os_path.h#L74-L75

to something like:

```c
PMIX_EXPORT char *pmix_os_path(int relative, ...)
    __pmix_attribute_malloc__ 
#if NULL_IS_NOT_A_POINTER
    __pmix_attribute_sentinel__ 
#endif
   __pmix_attribute_warn_unused_result__;
```

We need a `configure` test to #define the `NULL_IS_NOT_A_POINTER` value.  Is there an easy test that could be conducted?  (I hesitate to say `#if SOLARIS` because a) it's probably not specific to Solaris, and b) and it may not be universal to all compilers on Solaris)

**Comment by afborchert** [comment]
Such a test would be fragile as the actual definition of NULL depends on the order of header files. If `<stddef.h>` happens to be included first, you will get a proper NULL defined to be of pointer type. If `<iso/time_iso.h>` happens to be included before (this is not a standard header but included indirectly) you will get the `0L` definition. The reason for this is that gcc patches `<stddef.h>` (via fixincludes) but not `<iso/time_iso.h>`.

**Comment by jsquyres** [comment]
Gotcha. So is the proper solution for `pmix_os_path.h` to `#include <stddef.h>`?

Granted, someone could include a "wrong" header file before `pmix_os_path.h`, but directly including the "good" header file in `pmix_os_path.h` might help reduce the possibility of that happening...?

**Comment by afborchert** [comment]
Indeed, if you make sure `<stddef.h>` is included first, the problem is resolved (at least on Solaris using gcc).

The fault is here with Solaris as `<time.h>` includes `<iso/time_iso.h>` which is breaking the ISO C standard (§ 7.19 (3) in ISO 9899:2011): “expands to an implementation-defined null pointer constant”. Others had the very same problem, see, for example, https://bz.apache.org/bugzilla/show_bug.cgi?id=47191.

But my recommendation is to get rid of NULL macros:

- 0 can be safely used instead since c99 whenever the compiler is aware that this has to be converted to a pointer type.
- In case of variable argument lists, it is best to convert the sentinel explicitly to the appropriate type, i.e. `(void*) 0` in this case.

The next C standard will include nullptr of type nullptr_t (like in C++), see https://open-std.org/JTC1/SC22/WG14/www/docs/n3042.htm.

**Comment by rhc54** [comment]
> But my recommendation is to get rid of NULL macros:

Eliminating the use of `NULL` everywhere would be a pretty significant undertaking, I fear - probably beyond the scope of what we can do (at least, anytime soon).

> In case of variable argument lists, it is best to convert the sentinel explicitly to the appropriate type, i.e. (void*) 0 in this case.

Doing this everywhere these things are called could be similarly daunting - especially because others call those functions, and so we are passing that burden along to a wider audience.

> The next C standard will include nullptr of type nullptr_t 

Thankfully, it will be a long time before we wind up having to deal with that one! Hopefully beyond my tenure in these things.

If disabling the picky checks resolves this problem, I think that's the way we will go for now.

**Comment by rhc54** [comment]
Let's see if https://github.com/openpmix/openpmix/pull/2936 is of help here. Can you perhaps give it a try? Or I can commit it first if that is easier.

**Comment by rhc54** [comment]
Best I can determine, this is done. Please reopen if necessary.
