### ISSUE TITLE
question on python packaging convention change

### ISSUE THREAD

**Issue by naughtont3** [openpmix/openpmix#2943]
## Background information

There was a change in the packaging for python bindings.  The change now requires an additional subdirectory be added, which seems extraneous.  I wonder if this is expected or maybe a mistake as the change is fairly recent and we do not do a lot of testing with the Python bindings.

Note testing was with a pmix/prte refreshed to latest but tested in context of openmpi build (so configure/install was done via openmpi top-level configure/make/make install).

### What version of the PMIx Reference Library are you using? 

 - pmix master after 214d5dff (24-dec-2022)
 - prte master
 - openmpi v5.0.x

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

Previously  after `make install` we only had to set `PYTHONPATH` to `site-packages`, but after the changes in 214d5dff a sub-directory  also had to be added to locate the pmix python module.

Example paths:

Past: `/sw/crusher/ums/ompix/DEVELOP/cce/14.0.2/install/openmpi-br-main.tjn/lib/python3.9/site-packages/`
Now: `/sw/crusher/ums/ompix/DEVELOP/cce/14.0.2/install/openmpi-br-main.tjn/lib/python3.9/site-packages/pypmix-5.0.0-py3.9-linux-x86_64.egg`

**Comment by rhc54** [comment]
Python changed their standard for packaging, moving away from the old "setup" method to one based on "pip install". Part of that was a move away from "eggs" to some other packaging format (I forget the name). Anyway, all that necessitated a change in the directory structure to make it work.

Annoying and rather painful to implement. Unsure why they chose to make the change, but I'm sure one could track it down somewhere.
