### ISSUE TITLE
VERSION of v4.2.3 still listed as rc2

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#2973]
## Background information

Debian test builds of 4.2.3

### What version of the PMIx Reference Library are you using? 

4.2.3 from latest tag

### Please describe the system on which you are running

Debian unstable on Arm64 
-----------------------------

## Details of the problem

The VERSION file for v4.2.3 still has
greek=rc2
set.

**Comment by rhc54** [comment]
Correct - we always post the official tarball built from the last release candidate, so the "greek" should point to that label.
