### ISSUE TITLE
config/oac missing

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#2974]
## Background information

4.2.3 tagged release

### Describe how PMIx was installed 

From github tarball.

### Please describe the system on which you are running

Debian unstable on arm64
-----------------------------

## Details of the problem

In debian re rerun `./autogen.pl` in the build process.

This runs the autoreconf line:
```
"autoreconf -ivf --warnings=all,no-obsolete,no-override -I config -I config/oac;"
```
But the `config/oac` is not present.

**Comment by rhc54** [comment]
Please don't use the GitHub tarball - it is _not_ the official one and will _not_ work. Use the official one we post.
