### ISSUE TITLE
v4.2.3: PMIX_BUILD_DOCS, PMIX_INSTALL_DOCS need to be AM_CONDITIONAL

### ISSUE THREAD

**Issue by amckinstry** [openpmix/openpmix#2975]
## Background information

4.2.3

### Describe how PMIx was installed 

From github tarball v4.2.3.tar.gz

### Please describe the system on which you are running

Debian unstable on arm64

-----------------------------

## Details of the problem

On running autoconf / configure it fails as `PMIX_BUILD_DOCS` and `PMIX_INSTALL_DOCS` are used in docs/Makefile.am but are not set in AM_CONDITIONAL clauses.

**Comment by rhc54** [comment]
Which tarball did you use? The official one we posted (pmix-4.2.3.tar.gz) of the one that GitHub posts? Note that the latter will definitely NOT work - sadly, GitHub doesn't provide a way for us to turn that off.

I just downloaded the official tarball and built it (both with Sphinx and without) and it worked fine.

**Comment by v1peractual** [comment]
Where are we supposed to download the official tarball?

I get the following when building from src rpm or from the tarball retrieved from:
https://github.com/openpmix/openpmix/releases/tag/v4.2.3
This https://openpmix.github.io/downloads has not been updated since February.


We are using RHEL 8.6 EUS:

rpmbuild --define '_prefix /usr/local' --rebuild /root/RPMBUILD/SRPMS/pmix-4.2.3-1.src.rpm

RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/README
    File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/INSTALL

**Comment by rhc54** [comment]
> https://github.com/openpmix/openpmix/releases/tag/v4.2.3

The site is correct - please ensure you use the `pmix-4.2.3...` assets and not the ones labeled `Source code`.

> This https://openpmix.github.io/downloads has not been updated since February.

Yeah, sorry about that - we are in the midst of trying to decide if we should maintain that location (deleting the release tags here on GitHub) or stick with the release tags. The hassle of the GitHub tarballs can sometimes get annoying, but it's more work going strictly with the web site. Should have a decision soon.

> RPM build errors:
> File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/README
> File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/INSTALL

Not sure what to make of that - I don't actually maintain the rpm spec myself, but rely on those who use it to do so. As far as I last heard, it was working for them. Any contributions to that file are appreciated! Meantime, I'll try to take a peek in case I see something obvious.

**Comment by rhc54** [comment]
> > RPM build errors:
> > File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/README
> > File not found: /root/rpmbuild/BUILDROOT/pmix-4.2.3-1.el8.x86_64/usr/local/share/doc/pmix/INSTALL
> 
> Not sure what to make of that - I don't actually maintain the rpm spec myself, but rely on those who use it to do so. As far as I last heard, it was working for them. Any contributions to that file are appreciated! Meantime, I'll try to take a peek in case I see something obvious.

Aha! I see what happened. A friendly contributor reworked the documentation for posting to ReadTheDocs, and those files basically were converted to the new restructured text format (and moved to the docs directory). Unfortunately, the `rpm.spec` file didn't get updated.

I'll take a shot at fixing it. PMIx v4.2.4 probably won't be out for another month, so it should be corrected by then. I'll poke here so someone can test a release candidate out prior to actual release.

**Comment by rhc54** [comment]
Okay, I fixed and updated the rpm spec and generated a new v4.2.3 src rpm. I checked it and it unpacked and built just fine, so I think it is good to go. I updated it on the release tag: https://github.com/openpmix/openpmix/releases/download/v4.2.3/pmix-4.2.3-1.src.rpm.

Please let me know if it works for you or you hit more problems with it.

**Comment by TimoRoth** [comment]
I'm having the exact same issue with the official release tarball from https://github.com/openpmix/openpmix/releases/download/v4.2.3/pmix-4.2.3.tar.bz2

Running autoreconf fails with:

```
docs/Makefile.am:85: error: PMIX_BUILD_DOCS does not appear in AM_CONDITIONAL
docs/Makefile.am:136: error: PMIX_INSTALL_DOCS does not appear in AM_CONDITIONAL
```

**Comment by rhc54** [comment]
Could you please detail the exact commands you are using?

**Comment by ggouaillardet** [comment]
@TimoRoth make sure you did not forget the `config/oac` directory e.g.

```
autoreconf -I config -I config/oac
```

**Comment by rhc54** [comment]
I'm going to close this as being resolved by adding the `config/oac` directory to an `autoreconf` cmd line. Please feel free to reopen if needed.

**Comment by mdidomenico4** [comment]
this error seems to have popped up for me with v4.2.9, i'm doing

git clone
git archive v4.2.9 | tar xvf - -C /mysrcdir/blah
cd /mysrcdir/blah
perl autogen.pl

the last line of the output shows

autoreconf -ivf --warnings=all,no-obsolete,no-override -I config -I config/oac

i do have sphinx installed, i'm not sure what's going on, thanks

**Comment by rhc54** [comment]
I'm afraid I don't understand what you are doing with those commands - I get that you clone the repo? I have no idea what "git archive" is supposed to accomplish. If you want to start with a tarball, then please download the official release: https://github.com/openpmix/openpmix/releases/download/v4.2.9/pmix-4.2.9.tar.bz2

Note that we do _not_ support use of the GitHub tarballs as they are not complete and will definitely fail to build.

**Comment by mdidomenico4** [comment]
ok, i'll have to figure something else out then.  unfortunately the only way i get a copy of the source is via github mirror onto a protected network.  being unable to build from the source tree is unfortunate

**Comment by rhc54** [comment]
Not sure I understand the problem - you can just "git clone" the repo, yes? If so, then you just:
```shell
$ git clone https://github.com/openpmix/openpmix
$ cd openpmix
$ git submodule update --init
$ ./autogen.pl
$ ./configure ...
$ make install
```
As far as I can tell, the "archive" does nothing for you. Am I missing something?

**Comment by mdidomenico4** [comment]
oh, there's a submodule.  i hadn't seen that in the documentation anywhere.  pulling in the submodule does allow me to run autogen.pl and build the source

the archive command just gives me a copy of the tag outside of the git tree without any of the git stuff.  unfortunately it doesn't pickup the submodule files, but rsync'ing them into the archive directory does seem to work and the build completed.  i'll give it some testing and see how everything is

thanks

**Comment by rhc54** [comment]
> oh, there's a submodule. i hadn't seen that in the documentation anywhere

**Comment by rhc54** [comment]
FWIW: Added some verbiage about the submodule in https://github.com/openpmix/openpmix/pull/3306. Hopefully that will help!
