### ISSUE TITLE
Test dstore and jobinfo

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#299]
During the course of solving https://github.com/pmix/master/issues/280 I modified our test suite to emulate a large system and pushing a tunable number of rank info's to the dstore.
I think it will be a good load test for the dstore in Jenkins, so we need to integrate this into our test suite.
My modification can be found here:
https://github.com/artpol84/master/tree/test_suite/master

**NOTE**: only the most recent commit is relevant and needs to be ported.

Here is how I want it to be activated:
`./pmix_test -n <actual-size> <other-options> --job-info <emulated-size>`

This will need to go to v1.2 so we will be able to test it. But not in v1.2.1 - after the release.

**Comment by jjhursey** [comment]
Any update on this? Can it slip to v1.2.4?

**Comment by artpol84** [comment]
Yes, definitely it can slip.

**Comment by jjhursey** [comment]
I just pushed this to v1.2.6, but the door is still open for v1.2.5 if a PR is coming. Otherwise this has been open for quite some time - should we close it?

**Comment by artpol84** [comment]
@jjhursey I'd like to keep it for the reference as I want this finally to be implemented.
I removed the target tag. Will it be ok?

**Comment by jjhursey** [comment]
Yeah that's fine. I'm hoping that v1.2.5 is the last release in the v1.2 series. The milestone is what I have been using to track outstanding work for a release. So I just wanted to see if this ticket has just gotten stale.

**Comment by jjhursey** [comment]
Any update on this issue?

**Comment by artpol84** [comment]
Give that dstore will be obsolete, I don't think we want to keep it.
Can close.
