### ISSUE TITLE
PMIx_Get with PMIX_RANK_UNDEF returned TIMEOUT

### ISSUE THREAD

**Issue by JiakunYan** [openpmix/openpmix#3006]
## Background information
I am trying to write a simple example using PMIx and run it on my laptop. The code is here: https://github.com/JiakunYan/pmix-example/blob/master/main.cpp

Specifically, I want to use PMIx_Get with PMIX_RANK_UNDEF, based on the following sentences of the standard.
> Both of the above methods are based on retrieval from a specific process - i.e., the proc argument to
PMIx_Get must include both the namespace and the rank of the process that posted the
information. However, in some cases, non-reserved keys are provided on a globally unique basis
and the retrieving process has no knowledge of the identity of the process posting the key. This is
typically found in legacy applications (where the originating process identifier is often embedded in
the key itself) and in unstructured applications that lack rank-related behavior. In these cases, the
key remains associated with the namespace of the process that posted it, but is retrieved by use of
the PMIX_RANK_UNDEF rank. In addition, the keys must be globally exchanged prior to retrieval
as there is no way for the host to otherwise locate the source for the information.

### What version of the PMIx Reference Library are you using? 
PMIx v4.2.2
prrte v3.0.0

### Describe how PMIx was installed 
I downloaded the tarball from github release, and run the following commands to install them.
```
cd pmix-4.2.2
mkdir build
cd build
../configure --prefix=~/opt/pmix
make
make install
```

```
cd prrte-3.0.0
mkdir build
cd build
../configure --prefix=~/opt/prrte --with-pmix=~/opt/pmix
make
```

I compiled my example using the following commands
```
cd pmix-example
mdkir build
cd build
PMIX_ROOT=~/opt/pmix cmake ..
make
```

### Please describe the system on which you are running

* Operating system/version: ubuntu 20.04
* Computer hardware: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

-----------------------------

## Details of the problem

I first start the server using `prte`, and then run my example using the following command.
```
prun -n 2 ./main
```

It outputted:
```
Client prte-xxxxxx-169417@24:1 universe size 4
Client prte-xxxxxx-169417@24:1 num procs 2
Client prte-xxxxxx-169417@24:0 universe size 4
Client prte-xxxxxx-169417@24:0 num procs 2
err -24 : TIMEOUT (/home/XXX/workspace/pmix-example/main.cpp:67)
err -24 : TIMEOUT (/home/XXX/workspace/pmix-example/main.cpp:67)
```

It appears the key is not ready when the program called `PMIx_Get`, but I did use `PMIx_Commit` and `PMIx_Fence` with `PMIX_COLLECT_DATA`. Could someone help me fix this example? Did I miss something?

**Comment by rhc54** [comment]
I can confirm it is a bug in the v4.2 series - works fine in the master branch. I'll provide a fix.

**Comment by JiakunYan** [comment]
I don't think the #3009 fixes the issue because I also tried replacing `&proc` with NULL in line 67 of my example and it didn't work.

I also test it again with openpmix v4.2 branch and prrte v3.0 branch. It doesn't work either.

**Comment by rhc54** [comment]
Well, for now I have confirmed again that it works fine on a single node using your unmodified test code and master branches of PMIx and PRRTE:
```shell
$ prun -n 2 ./testrig
Client prte-Ralphs-iMac-2-25511@1:1 universe size 10
Client prte-Ralphs-iMac-2-25511@1:1 num procs 2
Client prte-Ralphs-iMac-2-25511@1:0 universe size 10
Client prte-Ralphs-iMac-2-25511@1:0 num procs 2
Client ns prte-Ralphs-iMac-2-25511@1 rank 0: PMIx_Get prte-Ralphs-iMac-2-25511@1-0-global returned correct
Client ns prte-Ralphs-iMac-2-25511@1 rank 1: PMIx_Get prte-Ralphs-iMac-2-25511@1-0-global returned correct
Client ns prte-Ralphs-iMac-2-25511@1 rank 1: PMIx_Get prte-Ralphs-iMac-2-25511@1-1-global returned correct
Hello, World!
Client ns prte-Ralphs-iMac-2-25511@1 rank 0: PMIx_Get prte-Ralphs-iMac-2-25511@1-1-global returned correct
Hello, World!
$
```
I'll take another look at the v4.2 branch tomorrow. Are you running single node, or across multiple nodes?

**Comment by JiakunYan** [comment]
I am running a single node but using either v4.2.2 or the v4.2 branch. Thanks!

**Comment by rhc54** [comment]
I'm not finding a reasonable solution that won't break cross-version operations. Can you try starting `prte` with `--pmixmca gds hash` on the cmd line? I believe that will resolve the problem.

**Comment by JiakunYan** [comment]
Yeah `prte --pmixmca gds hash` can solve the problem. Thanks!

**Comment by rhc54** [comment]
Okay, I'm closing this then. I'll be releasing v5.0 soon, and that should resolve a lot of these problems.
