### ISSUE TITLE
Should the spec file include the BuildRequires as Requires too?

### ISSUE THREAD

**Issue by nerscchris** [openpmix/openpmix#3017]
## Background information

When replacing the PMIx v3 from SLES RPM with one built from the source RPM from here we found that users were missing things like libevent-devel from our OS image which we believe were previously `Required` in by the removed `pmix-devel` v3 RPM. I suspect the spec file here should `Require` them as well to avoid this problem (as it amalgamates the `pmix-devel` RPM from the distro).

### What version of the PMIx Reference Library are you using? 

v4.2.3, though it looks like the current head of git has the same issue.

### Describe how PMIx was installed 

From the source RPM on Github.

### Please describe the system on which you are running

* Operating system/version: HPE Cray COS 2.4 (SLES15 SP4 base)
* Computer hardware: HPE Cray EX
* Network type: Slingshot 11

-----------------------------

## Details of the problem

As above.

**Comment by rhc54** [comment]
> I suspect the spec file here should Require them as well to avoid this problem

Entirely possible. I don't maintain the spec file myself, but rather rely on those who use it to do so as I am no expert by far with rpm building. If you can post a PR with the required change, or just post it here, that would be most welcome.

**Comment by rhc54** [comment]
@nerscchris I took a look at the pmix.spec file and found these entries:
```text
BuildRequires: gcc
BuildRequires: make
BuildRequires: libevent-devel
BuildRequires: hwloc-devel
BuildRequires: python3-devel
BuildRequires: zlib-devel
```
Is that not what you were asking for?

**Comment by nerscchris** [comment]
Hi Ralph,

Those don't cause those packages to get installed via the package manager (in our case zypper) when installing the resulting RPM, they just provoke an error should they not be installed when trying to build from that spec file. So what was found here was that we had the pmix v4 RPM installed but things like libevent-devel were missing which prevented them building OpenMPI.

Interestingly for us we have `cray-hwloc` installed instead of `hwloc-devel`, but I believe it provides what PMIx needs (and in fact they've reported that OpenMPI v5 works on this test system with that in place).

```
alvarez:login02:~ # rpm -q --provides cray-hwloc
cray-hwloc = 2.8.0-2.4_20230227173106__gc5a6de97
cray-hwloc(x86-64) = 2.8.0-2.4_20230227173106__gc5a6de97
hwloc
hwloc-data
hwloc-devel
libhwloc.so.15()(64bit)
libhwloc15
libnetloc.so.0()(64bit)
libtool(/usr/lib64/hwloc/hwloc_rsmi.la)
libtool(/usr/lib64/libhwloc.la)
libtool(/usr/lib64/libnetloc.la)
pkgconfig(hwloc) = 2.8.0
```

All the best!
Chris

**Comment by rhc54** [comment]
@hppritcha  Do you have any ideas on how to solve this problem?

**Comment by rhc54** [comment]
@nerscchris I think I may have found an answer. However, I cannot seem to send an rpm file to you, nor will GitHub allow me to post it on a ticket or Gist - so I have posted it [here](https://openpmix.github.io/uploads/2022/pmix-4.2.4-1.src.rpm).

Please let me know if you can try it out, and if it solves your problem.

**Comment by bwbarrett** [comment]
Note that I don't think you want to `Requires: xxxx-devel`, but instead want to `Requires:` the packages that include the libraries (usually just the xxxx part).

**Comment by rhc54** [comment]
Yeah, that's what was bothering me. We have the `BuildRequires` entries for `libevent-devel` and friends, which I would have thought provided all you need for building the PMIx library. Yet @nerscchris is saying that they couldn't build PMIx because the rpm wasn't forcing download of the `libevent-devel` package - they had to manually install it.

I'm not sure I grok the problem - any guidance would be appreciated.

**Comment by jsquyres** [comment]
@nerscchris I don't quite grok your initial statement:

> When replacing the PMIx v3 from SLES RPM with one built from the source RPM from here we found that users were missing things like libevent-devel from our OS image which we believe were previously Required in by the removed pmix-devel v3 RPM.

If you are installing a binary RPM for PMIx, end users should not need `libevent-devel` installed.

Are you finding that that is incorrect?

**Comment by rhc54** [comment]
@nerscchris Can you please provide some further input per requests? If not, I'll just close this as I see nothing currently incorrect.

**Comment by rhc54** [comment]
Closing this as it appears what we have is correct, so far as I can tell.
