### ISSUE TITLE
Slurm/OpenMPI: Interoperability between PMI2/PMIx

### ISSUE THREAD

**Issue by vitduck** [openpmix/openpmix#3018]
Hello, 

I am trying to understand the interaction between Slurm and OpenMPI through PMI2/PMIx.
My understanding so far is: 
1. Slurm can support multiple interface: PMI2, PMIx v2, PMIx v3. Our cluster was not built against PMIx
```
$ srun --mpi=list
run: MPI types are...
srun: pmi2
srun: cray_shasta
srun: none
```
2. OpenMPI is always built against either its internal copy of PMIx or an external one. 
```
$ ./configure -h 
--with-pmix(=DIR)
....
                                                  Open MPI does not support --without-pmix.
```
So when we built OpenMPI against PMI2 the following was observed, even when ``--with-pmix``` was not used: 
```
$ ompi_info 
                MCA pmix: isolated (MCA v2.1.0, API v2.0.0, Component v4.1.1)
                MCA pmix: pmix3x (MCA v2.1.0, API v2.0.0, Component v4.1.1)
                MCA pmix: s1 (MCA v2.1.0, API v2.0.0, Component v4.1.1)
                MCA pmix: s2 (MCA v2.1.0, API v2.0.0, Component v4.1.1)
                 MCA ess: pmi (MCA v2.1.0, API v3.0.0, Component v4.1.1)
```
Due to lack of documentation, my guesses are: 
- ```isolated```: internal copy 
- ```pmix3x```: pmix v3 
- ```s1```: backward compatibility to PMI1
- ```s2```: backward compatibility to PMI2 
- When I launch an MPI application using ```mpirun```, and not ```srun```, PMIX will take precedence over PMI2 and communicate with Slurm via s2 (The latter is only built against PMI2) 
Is this understanding correct ? 

3. Measurement of impact of PMIx
Is there a way to to select PMI2 over PMIx at runtime, i.e by passing the s2 compatibility layer ? In theory, PMIx has better scalability than PMI2. But we would like to measure the difference for several HPC applications. 

4. The concept of key-value database: 
I tried to visualize the KV database using a simple 2-process-MPI_SEND and MPI_RECV. The key would process ID of each MPI rank. Then what would the values be pertaining to the information exchange between two ranks ? 

Regards.

**Comment by rhc54** [comment]
Just as an FYI: beginning with the upcoming OMPI v5 release, OMPI will _only_ support PMIx and will no longer support protocols such as PMI1 or PMI2.

> When I launch an MPI application using mpirun, and not srun, PMIX will take precedence over PMI2 and communicate with Slurm via s2 (The latter is only built against PMI2) Is this understanding correct ?

Not really. The application will interact with the mpirun daemons via PMIx, but mpirun and its daemons will not interact with Slurm at all. Slurm therefore has no visibility into the application itself.

> is there a way to to select PMI2 over PMIx at runtime, i.e by passing the s2 compatibility layer ? In theory, PMIx has better scalability than PMI2. But we would like to measure the difference for several HPC applications.

I haven't looked at the older versions of OMPI in a long time, but I believe you can build all the components in parallel. Then you use the `srun --mpi=s2` option to say you want to use the PMI2 support (OMPI will autoselect based on the Slurm envars). Note that this really doesn't test PMIx vs PMI2, but rather the efficiency of the inter-node data exchange method in the PMI2 Slurm plugin vs that in the PMIx plugin.

> I tried to visualize the KV database using a simple 2-process-MPI_SEND and MPI_RECV. The key would process ID of each MPI rank. Then what would the values be pertaining to the information exchange between two ranks ?

I'm not sure what you are looking at here. Are you talking about the PMIx/PMI2 key-value databases? They are very different. PMIx stores data by process ID, so two processes can "post" the same key and retrieve the data by specifying the key and source. PMI2 stores data solely by the key, and so each key has to be globally unique. The MPI library hides all this from the application so you'll never see it either way.

**Comment by vitduck** [comment]
Thank you for clarification. 
Open MPI is designed to 'just work' so we sometimes have difficult figuring out what is happening under the hood.
 
Regarding the output of ```ompi_info```, we see that ```s1``` and ```s2``` are present only when ```--with-pmi``` are used. As you mentioned in 'The ABCs of Open MPI, part 1' (https://www.youtube.com/watch?v=WpVbcYnFJmQ), PMIx is a framework by itself. We assume that ```s1```, ```s2``` are its sub components.

>Not really. The application will interact with the mpirun daemons via PMIx, but mpirun and its daemons will not interact with Slurm at all. Slurm therefore has no visibility into the application itself.

 ![image](https://user-images.githubusercontent.com/575950/225832492-61f7a2f1-a913-40f9-b702-041fc71d830c.png)
The is is from Dr. Polyakov (NVIDIA)'s presention[1]. If I understand your reply correctly, 

- Each MPI process has its own PMIx thread performing Put/Get to a node-level local KV database. 
- The database in each node is synchronized via ORTEd (with ```mpirun```), and Slurmd (with ```srun```)

Thus in the following case: 
- SLURM built with only PMI2 plugin. 
- Open MPI built with ```--without-pmi``` option 

```srun``` fails due the lack of ```s2``` with following message, which is expected 
```
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute.
```
>I haven't looked at the older versions of OMPI in a long time, but I believe you can build all the components in parallel. Then you use the srun --mpi=s2 option to say you want to use the PMI2 support (OMPI will autoselect based on the Slurm envars). Note that this really doesn't test PMIx vs PMI2, but rather the efficiency of the inter-node data exchange method in the PMI2 Slurm plugin vs that in the PMIx plugin.

I apologize for not phrasing the question clearly. I was looking for an ```mpirun``` option to switch from PMIx to PMI2. 
Now it is clear that the ```--with-pmi``` option actual means 'with SLURM's PMI'. It's clear that such option does not exist. 

![image](https://user-images.githubusercontent.com/575950/225842001-5c385bc8-48ce-4afa-b53f-3baeaf4751c5.png)
This is also from Dr. Polyakov's presentation[2]. 

If I understand your reply correctly, the benchmark between ```srun --mpi=pmix``` and ```srun --mpi=pmi2``` will only reflect the difference of RM OOB channel, i.e. black arrow . 

Is my understanding so far correct ? 

[1]  https://slurm.schedmd.com/SC17/Mellanox_Slurm_pmix_UCX_backend_v4.pdf
[2]  https://pmix.github.io/uploads/2019/09/2019_EMPI_Polyakov_PMIx_v5.pptx

**Comment by rhc54** [comment]
> Regarding the output of ompi_info, we see that s1 and s2 are present only when --with-pmi are used. As you mentioned in 'The ABCs of Open MPI, part 1' (https://www.youtube.com/watch?v=WpVbcYnFJmQ), PMIx is a framework by itself. We assume that s1, s2 are its sub components.

Yes, but keep in mind that this only impacts the MPI layer and not mpirun. As I said, mpirun only uses PMIx. The framework allows you to use `srun` in place of `mpirun` by enabling use of PMI1 or PMI2 to interact with Slurm when Slurm doesn't have PMIx support.

Also note that this is no longer supported in OMPI v5 and above - you'll have to include PMIx support in Slurm to use `srun`.

> srun fails due the lack of s2 with following message, which is expected

Correct

> If I understand your reply correctly, the benchmark between srun --mpi=pmix and srun --mpi=pmi2 will only reflect the difference of RM OOB channel, i.e. black arrow .

Correct - it has nothing to do with PMI2 vs PMIx.

**Comment by rhc54** [comment]
Please reopen if you have any further questions.
