### ISSUE TITLE
gds shmem component has issues on arm architecture

### ISSUE THREAD

**Issue by wckzhang** [openpmix/openpmix#3032]
On Open MPI v5.0.x branch, the Open PMIx submodule points to:
```
8e71cf0e6753192b075edffc46fe09de597dc7c1
```

When running on our c7gn instance types which runs on arm processors, we have seen issues with the new gds shmem component.

Logs:
```
/var/spool/slurmd/job00053/slurm_script: line 97: 22845 Segmentation fault      mpirun ${MPIRUN_FLAGS} redistributePar -parallel -overwrite &>./log/decomposePar2.log
.
.
.
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file gds_shmem.c at line 1909
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file gds_shmem.c at line 1917
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file base/gds_base_fns.c at line 238
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file base/gds_base_fns.c at line 255
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file server/pmix_server.c at line 3407
[compute-dy-nodes-1:22845] PMIX ERROR: NO-MEM in file gds_shmem.c at line 1886
```

I've seen a number of commits disabling/enabling the gds shmem component and that it doesn't run on mac. Running with ```--mca gds ^shmem``` gets rid of the error. Is arm unsupported for this component?

**Comment by rhc54** [comment]
You've got the wrong PMIx branch - the gds/shmem component does not exist in the PMIx v4.2 branch used by OMPI v5.0. Please correct it.

**Comment by wckzhang** [comment]
ACK, this must have happened on main branch - ``` 7d25bd021b57d4e3cea40d23bd3662180c269827 openpmix (v1.1.3-3825-g7d25bd02)```

Won't impact the 5.0.x release, but is arm unsupported for the component?

**Comment by wckzhang** [comment]
This is with slurm, so your explanation fits
