### ISSUE TITLE
PMIx group are not removed when PMIx_Group_destruct'ed

### ISSUE THREAD

**Issue by ggouaillardet** [openpmix/openpmix#3062]
This can be seen with the `PMIx` used by Open MPI `main` branch

Refs. open-mpi/ompi#11593

in `src/client/pmix_client_group.c`, newly created PMIx groups are appended to `pmix_client_globals.groups` but they are never removed from it. Consequently, when a new group is created with the same name, the first group with the same name is picked from the list in `PMIx_Group_destruct_nb`

The `PMIx` program below can be used in order to evidence the hang.
It has to be run with 2 ranks.

```c
#include <stdio.h>
#include <pmix.h>

int main(int argc, char *argv[]) {
    pmix_proc_t myproc;
    pmix_proc_t _procs[2], *procs;

    PMIx_Init(&myproc, NULL, 0);

    int i;
    size_t nprocs;
    for (i=0; i<2; i++) {
        memcpy(_procs+i, &myproc, sizeof(pmix_proc_t));
        _procs[i].rank = i;
    }

    pmix_info_t pinfo, *results = NULL;
    size_t nresults;

    PMIX_INFO_LOAD(&pinfo, PMIX_GROUP_ASSIGN_CONTEXT_ID, NULL, PMIX_BOOL);

    /* group "tag" contains ranks {0,1} */
    PMIx_Group_construct("tag", _procs, 2, &pinfo, 1, &results, &nresults);

    PMIx_Group_destruct("tag", NULL, 0);

    if (0 == myproc.rank) {
        /* group "tag" that was previously created with ranks {0,1} has been destructed
         * and is now re-created with the local rank */

        PMIX_INFO_LOAD(&pinfo, PMIX_GROUP_ASSIGN_CONTEXT_ID, NULL, PMIX_BOOL);
        PMIx_Group_construct("tag", _procs, 1, &pinfo, 1, &results, &nresults);

        /* this destruction will hang */
        PMIx_Group_destruct("tag", NULL, 0);
    }

    pmix_proc_t proc;
    PMIX_PROC_CONSTRUCT(&proc);
    PMIX_LOAD_PROCID(&proc, myproc.nspace, PMIX_RANK_WILDCARD);
    PMIx_Fence(&proc, 1, NULL, 0);

    PMIx_Finalize(NULL, 0);

    return 0;
}

```

**Comment by rhc54** [comment]
Thanks! IIRC, PRRTE is also tracking groups so we need to check that it is removing the destructed group. I can take a gander (hopefully later today).

**Comment by hppritcha** [comment]
Thanks @ggouaillardet this would have bitten us at some point as more codes made use of MPI functions that under the hood used PMIx group functionality.

**Comment by rhc54** [comment]
Actually, that patch isn't quite correct. You don't need the server to return the grpid as we already know what it is - we just need to use it. This also preserves cross-version compatibility with prior releases that won't know what to do with another data field in the passed message.

**Comment by rhc54** [comment]
See the combination of https://github.com/openpmix/openpmix/pull/3063 and https://github.com/openpmix/prrte/pull/1739 - should resolve the problem.

**Comment by rhc54** [comment]
Confirmed elsewhere as fixed
