### ISSUE TITLE
NVIDIA transport

### ISSUE THREAD

**Issue by dorrellmw** [openpmix/openpmix#3080]
While reviewing the `./configure` output, I noticed `NVIDIA: no` under "Transports". While attempting to trace the reasoning, I found that `src/mca/pnet/nvd/configure.m4` appears to use `test "yes" = "no"` to determine whether this component can be enabled. I'm not very familiar with M4, but won't this always test negative? Is the NVIDIA transport hardcoded to be disabled due to known problems with the implementation?

The more important questions are, is the NVIDIA transport documented anywhere, and what dependencies must be satisfied to enable it?

I was originally looking through the source tarball for pmix-4.2.3, but the same is true for git master (3b5ae530d34ae72848ce1d8b0b05cacbd8db61cd).

For context, I'm building an updated software stack for a Linux platform, including hwloc, UCX, PMIx, Open MPI, etc.

**Comment by ggouaillardet** [comment]
FWIW, the commit message of 2c2a7ce242bb5ab61600d16c6357b1ae561b2842 suggests the support for this component has not been implemented.

**Comment by rhc54** [comment]
@ggouaillardet is correct. The component is there to support NVIDIA (Mellanox) transports, providing security keys, forwarding related envars, etc. No one has chosen to implement it as of this time. I usually remove it from release branches since it hasn't been implemented, but it apparently slipped by me for v4.2. I'll scrub that branch prior to the v4.2.4 release.

**Comment by dorrellmw** [comment]
I see, thank you for the clarification. Am I to also understand that PMIx has no direct or indirect dependency on UCX, then, as well?

**Comment by rhc54** [comment]
Correct - I doubt there will ever be a UCX component, but one can never know!

**Comment by dorrellmw** [comment]
Ok, thank you!

**Comment by rhc54** [comment]
I have removed the NVIDIA component from the release branch. Thanks for bringing this to our attention!
