### ISSUE TITLE
contrib/pmix.spec packs libpmix.so into pmix-devel*.rpm instead of pmix*.rpm

### ISSUE THREAD

**Issue by jose-d** [openpmix/openpmix#3097]
### What version of the PMIx Reference Library are you using?

4.2.4 release

### Describe how PMIx was installed

not relevant.

### Please describe the system on which you are running

* RockyLinux8.8
* HW kvm VM / bare metal, I believe not relevant.
* eth, mellanox IB 100Gbit / I believe not relevant

-----------------------------

## Details of the problem

After pmix build using `rpmbuild` command:

```shell
apptainer exec ./build-pmix-rocky86.sif rpmbuild --define 'build_all_in_one_rpm 0' --define 'configure_options --disable-per-user-config-files' -ba ./tarballs/pmix-4.2.4/contrib/pmix.spec
```

pmix*.rpm contains:

```shell
jose@koios1:~/projects/slurm_build/build-slurm-rocky8$ rpm -qpl $HOME/rpmbuild/RPMS/x86_64/pmix-4.2.4-202306191253.el8.x86_64.rpm | grep "libpmix"
/usr/lib64/libpmix.so.2
/usr/lib64/libpmix.so.2.8.0
jose@koios1:~/projects/slurm_build/build-slurm-rocky8$
```

pmix-devel*.rpm contains

```shell
jose@koios1:~/projects/slurm_build/build-slurm-rocky8$ rpm -qpl $HOME/rpmbuild/RPMS/x86_64/pmix-devel-4.2.4-202306191253.el8.x86_64.rpm | grep "libpmix"
/usr/lib64/libpmix.la
/usr/lib64/libpmix.so
jose@koios1:~/projects/slurm_build/build-slurm-rocky8$
```

I believe the `libpmix.so` should be actually included in libpmix*.rpm, not in devel one. 
Or is there good reason for this?

<!--**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ prun -np 2 ./hello_world
```

**Comment by rhc54** [comment]
No idea, though I would have thought it wouldn't belong in either one. The versioned `libpmix` is the one that should always be installed. However, I know nothing about rpm's and others contribute the spec file, so I'll have to defer to them.

**Comment by rhc54** [comment]
Closing this for now as it seems nobody is prepared to pick it up, so we'll just have to let it ride.
