### ISSUE TITLE
 PMix3 Plugin+ openMPI 4.1.5 broken for heterogenous jobs with SLURM v 21.08.8

### ISSUE THREAD

**Issue by denisbertini** [openpmix/openpmix#3098]
## Problem in short
When running SLURM heterogeneous MPI job, the connection on the level of slurm step deamons (SLURM PMIx plugin) sporadically timeout.

### What version of the PMIx Reference Library are you using? 
- openMPI 4.1.5 (with external PMIx v 4.2.3  +  UCX 1.14 )
- SLURM v 21.08.8-2
with
```
dbertini@lxbk1130 /lustre/rz/dbertini/containers/theory]$ srun --mpi=list
srun: MPI types are...
srun: none
srun: pmi2
srun: pmix
srun: pmix_v2
```
### Describe how PMIx was installed 
openMPI PMIx v 4.1.5 build from source, SLURM PMIx_v2 comes with RPMs.

### Please describe the system on which you are running

* Operating system/version:
 Rocky Linux 8
* Computer hardware:
AMD Epyc Cpus
* Network type:
IB  fabric (HDR )

-----------------------------

## Details of the problem
 When running SLURM heterogeneous MPI job, the connection on the level of slurm step deamons sporadically timeout
 with such an error:
```
slurmstepd: error:  mpi/pmix_v2: _tcp_connect: lxbk1177 [0]: pmixp_dconn_tcp.c:139: Cannot establish the connection
slurmstepd: error:  mpi/pmix_v2: pmixp_dconn_connect: lxbk1177 [0]: pmixp_dconn.h:246: Cannot establish direct connection to lxbk1177 (0)
slurmstepd: error:  mpi/pmix_v2: _process_extended_hdr: lxbk1177 [0]: pmixp_server.c:738: Unable to connect to 0
slurmstepd: error:  mpi/pmix_v2: pmixp_coll_ring_check: lxbk1177 [0]: pmixp_coll_ring.c:618: 0x14cd84047ab0: unexpected contrib from lxbk1177:0, expected is 1
slurmstepd: error:  mpi/pmix_v2: _process_server_request: lxbk1177 [0]: pmixp_server.c:942: 0x14cd84047ab0: unexpected contrib from lxbk1177:0, coll->seq=0, seq=0
```
Disabling tcp-based direct communication expicitely from SLURM PMix plugin seems to solve the issue:

```
export SLURM_PMIX_DIRECT_CONN=false
```

**Comment by rhc54** [comment]
I'm afraid you need to take that to the Slurm folks - it's an issue in their plugin, not anything to do with us.
