### ISSUE TITLE
Allowed to call `cbfunc` in `pmix_server_log_fn_t` before return?

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#3107]
### What version of the PMIx Reference Library are you using?
v4.2.4

### Describe how PMIx was installed
source tarball

-----------------------------

## Details of the problem

Perhaps this is more a question for the standard, but I'd like to ask it here, since I am currently more interested in how this is implemented in openpmix than how we can clarify this in the standard (which should be done nonetheless).

The server callback function type for server_log `pmix_server_log_fn_t` does not have a return value. Thus the usual mechanism of returning `PMIX_OPERATION_SUCCEEDED` without later call of `cbfunc`, or returning `PMIX_SUCCESS` with later call of `cbfunc`, or directly indicate a not supported request by `PMIX_ERR_NOT_SUPPORTED` can not be used.

I now wonder how to handle the different cases here.

Is it allowed to just call `cbfunc` with error status before returning from the function or is it necessary to postpone that and do it asynchronously?

In the standard this is not clearly stated. From my point of view it would be best to remove the special role here and add a return value as for almost all other functions (all but `pmix_server_tool_connection_fn_t`) of the server interface, but this might be complicated due to compatibility reasons and it would not help me today to implement this interface.

**Comment by rhc54** [comment]
> Is it allowed to just call cbfunc with error status before returning from the function or is it necessary to postpone that and do it asynchronously?

No, calling the cbfunc prior to return is never allowed.

> Thus the usual mechanism of returning PMIX_OPERATION_SUCCEEDED without later call of cbfunc, or returning PMIX_SUCCESS with later call of cbfunc, or directly indicate a not supported request by PMIX_ERR_NOT_SUPPORTED can not be used.

Correct - the way the log function is implemented in the library, it cannot support a blocking host function module entry. It needs to always be non-blocking, which made the return of a status of questionable value. Could we find a way to work around that problem? Maybe - but it didn't seem particularly important and so we haven't bothered with it.

**Comment by krempel-pt** [comment]
Ok, fine for me, I will propose a clarification for the standard, thanks.

**Comment by krempel-pt** [comment]
I must have been blind, it is already stated there very clearly for 4 years, my apologies. :see_no_evil:

**Comment by rhc54** [comment]
No worries - I cannot tell you how many times that has happened to me!
