### ISSUE TITLE
PMIx_Log() falsely returns PMIX_SUCCESS

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#3109]
### What version of the PMIx Reference Library are you using?
4.2.4

### Describe how PMIx was installed
Self-generated RPM from release tarball

### Please describe the system on which you are running

* Operating system/version: Fedora 37
* Computer hardware: x86
* Network type: virtual ethernet

-----------------------------

## Details of the problem

I accidently executed a program containing this snippet:
```c
    size_t ndata = 1;
    pmix_info_t data[ndata];
    PMIX_INFO_LOAD(&data[0], PMIX_LOG_SYSLOG, "Test output for syslog", PMIX_STRING);

    size_t ndirs = 1;
    pmix_info_t dirs[ndirs];

    if (PMIX_SUCCESS != (rc = PMIx_Log(data, ndata, dirs, ndirs))) {
	printf("[%s:%u]: PMIx_Log failed: %s\n", proc.nspace, proc.rank,
	       PMIx_Error_string(rc));
	exit(1);
    }
```

It resulted in no call of `pmix_server_log_fn()`, no output to syslog, and PMIX_SUCCESS is returned.

Of course it is an error not to load the directive, but I think the function should never return `PMIX_SUCCESS` if the included commands cannot be executed.

The standard says
> Note that a return of PMIX_SUCCESS only denotes that the data
was successfully handed to the appropriate system call (for local channels) or the host environment
and does not indicate receipt at the final destination.

I would say this is not fulfilled.

**Comment by rhc54** [comment]
Hmmm...I'm guessing that the presence of the uninitialized directive is the cause of the problem, but I'm not sure what I can do about it - I can't reliably detect that it is uninitialized since it could have garbage in it.

If you remove the uninitialized directive, do things work as expected?

**Comment by krempel-pt** [comment]
> If you remove the uninitialized directive, do things work as expected?

Yes, it's all fine then.

The problem that I see is not, to detect that the directive is uninitialized, but somehow it comes to a `PMIX_SUCCESS` return without `pmix_server_log_fn()` ever being called. So either it can be detected, that the directive is garbage (since it contains no valid key) and an error should be returned, or the valid `data` entry should be executed by passing it to the host server via a call to `pmix_server_log_fn()` together with the garbage directive and if the host server acknowledges it, you can return success. Am I missing something?

**Comment by rhc54** [comment]
Not sure - I'd have to explore it a bit. Could be that the bad directive causes all the `plog` components to ignore it. Still, so long as the bad directive doesn't cause the library to crash/hang (e.g., by having an infinitely long string in its key or value), one would like it to at least return an error.

Difficulty, of course, lies in testing such a case as it's not easy to replicate - what your environment does with an uninitialized variable may be vastly different from mine. I'll see what can be done.

**Comment by rhc54** [comment]
Hmmm...like I said, difficult to replicate. On my machine, the data type in that uninitialized directive is garbage and generates an immediate error:
```shell
[Ralphs-iMac-2.local:99523] PACK-PMIX-VALUE[base/bfrop_base_pack.c:997]: UNSUPPORTED TYPE 24207
[Ralphs-iMac-2.local:99523] PMIX ERROR: PMIX_ERROR in file common/pmix_log.c at line 255
[foobar:0]: PMIx_Log failed: PMIX_ERROR
```
The offending type varies by execution as the value is random garbage. I'll try at least putting something valid there to get it to go a little further.

**Comment by rhc54** [comment]
If I use `memset` to zero out the `pmix_info_t` of that directive (so it is initialized to have no key or anything else), then it works fine:
```shell
[Ralphs-iMac-2.local:04085] [foobar,0] pmix:log
[Ralphs-iMac-2.local:04085] pmix:log sending to server
[Ralphs-iMac-2.local:04071] plog:log called
SIMPTEST LOG WITH 1 DATA and 2 DIRECTIVES
[foobar,0]LOG: Test output for syslog
[Ralphs-iMac-2.local:04085] pmix:log completed
```
This is with `PMIX_MCA_plog_base_verbose=100` in the environment. You can see that my test server was called with the data and directives, and it did output the string (NOTE: I changed it to output to stdout instead of syslog as my Mac doesn't appreciate users writing into syslog).

**Comment by rhc54** [comment]
Yeah, I cannot replicate the problem. I've tried giving a valid value with a zero key, and a garbage key for the directive - neither had any impact on it. The log is correctly printed and reports success.

I'm afraid I simply cannot replicate this. Of course, I'm using the head of the `master` branch - but I'm unaware of any changes in this code path. Still, you might want to try it and verify that it still fails for you.

Only thing I can suggest is that you try to run with that verbose setting in the environment and see if it tells us anything useful. Not a ton of debug output in that code path, but might be worth a try?

**Comment by krempel-pt** [comment]
I'll try to reproduce this again when I find the time.

**Comment by rhc54** [comment]
Please reopen if you find time and want to continue pursing this.
