### ISSUE TITLE
5.0.1: Incorrect release assets

### ISSUE THREAD

**Issue by kloczek** [openpmix/openpmix#3151]
Looks like in 5.0.1 release assets have been uploaded 5.0.0 tar balls 😋 
![image](https://github.com/openpmix/openpmix/assets/31284574/2e52d935-b55f-457b-93a7-65a2b761de72)

**Comment by rhc54** [comment]
Sigh - fat fingered it. Thx for pointing it out!

**Comment by kloczek** [comment]
Thank you 👍
