### ISSUE TITLE
Failed to build python bindings on Ubuntu 22.04

### ISSUE THREAD

**Issue by lukeyeager** [openpmix/openpmix#3152]
## Background information
I was tasked this week with upgrading our debian packages from jammy's v4.1.2 to v4.2.6.

### What version of the PMIx Reference Library are you using? 
v4.2.6

### Describe how PMIx was installed 
This is a build-time bug, not a run-time one, so it wasn't "installed". I was building on Ubuntu 22.04 using the following list of build dependencies (plus python-setuptools): https://salsa.debian.org/science-team/pmix/-/blob/debian/4.2.3_rc1-1/debian/control. I expect the most important specific versions for this bug report are `python3-all-dev=3.10.6-1~22.04` and `cython=0.29.28-1ubuntu3`.

### Please describe the system on which you are running

* Operating system/version: Ubuntu 22.04 (technically it's a container with Arch linux as the host OS, though it shouldn't matter)
* Computer hardware: `Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz`
* Network type: none (build-time bug)

-----------------------------

## Details of the problem

 I had to revert this commit in order to get the build to complete: 0df40d454b457dba4b73890d59148030cd3668c7 (from https://github.com/openpmix/openpmix/pull/3141). I got the following error message, checked `git blame`, tried reverting the commit, and it worked. I didn't dig any further. I don't even know whether the python bindings are still functional since we don't use them (but I expect they would be from looking at the reverted code).
 ```
 make[5]: Entering directory '/usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python'
PMIX_BINDINGS_TOP_SRCDIR=/usr/local/src/pmix/pmix-4.2.6 PMIX_BINDINGS_TOP_BUILDDIR=/usr/local/src/pmix/pmix-4.2.6/debian/static-build \
        /usr/bin/python3 ../../../../bindings/python/setup.py build_ext --library-dirs="/usr/local/src/pmix/pmix-4.2.6/debian/static-build/src/.libs" --user

Error compiling Cython file:
------------------------------------------------------------
...
# if we should terminate without finalizing
progressThread = threading.Thread(target = pyevhdlr, daemon = True, args =(lambda : stop_progress, ))

cdef void dmodx_cbfunc(pmix_status_t status,
                       char *data, size_t sz,
                       void *cbdata) noexcept:
                                    ^
------------------------------------------------------------

pmix.pyx:104:37: Syntax error in C variable declaration
Compiling /usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/pmix.pyx because it changed.
[1/1] Cythonizing /usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/pmix.pyx
Traceback (most recent call last):
  File "/usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/../../../../bindings/python/setup.py", line 135, in <module>
    sys.exit(main())
  File "/usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/../../../../bindings/python/setup.py", line 129, in main
    package_setup(package_name, package_vers)
  File "/usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/../../../../bindings/python/setup.py", line 114, in package_setup
    ext_modules = cythonize([Extension("pmix",
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /usr/local/src/pmix/pmix-4.2.6/debian/static-build/bindings/python/pmix.pyx
```

**Comment by lukeyeager** [comment]
```
$ cython3 --version
Cython version 0.29.28
```

**Comment by lukeyeager** [comment]
I can't really do that as part of a [clean] debian packaging script. I'll leave my `git revert` in-place for now since you're not saying that's likely to cause any issues. If you don't feel you need to support building from standard ubuntu 22.04 package versions (a reasonable stance), then you can close this.

**Comment by rhc54** [comment]
Well, I'm sure there are people who won't be happy with that situation, but it is really beyond my ability to support odd Cython installations. Might be worth on your end to ask the Cython maintainer why the package is reporting such an odd version.

I've asked some PMIx community folks to look at the bindings given the need to change things for newer Cython versions. Perhaps they will come up with appropriate protections to handle older versions.

Leaving the bindings as they were may cause some broken behavior - probably depends what version of Python is used to execute the script. 🤷‍♂️ For now, I'll just close this and we can worry about it if/when someone is broken.

**Comment by lukeyeager** [comment]
I checked PyPI. Looks like version prior to 3.0.0 was 0.29.36 (weird choice, guys). So the version I'm testing with is actually only about 18 months old.

**Comment by rhc54** [comment]
Good to know - sadly, looks like they made a significant (for us) change in the interim.

**Comment by lukeyeager** [comment]
Makes sense. Thanks for the quick responses today!
