### ISSUE TITLE
https://github.com/advisories/GHSA-m8fg-c37h-w29q

### ISSUE THREAD

**Issue by kc9qey** [openpmix/openpmix#3153]
## Background information

We are running a production system and are not able to quickly rebuild all MPI software libs and apps to address the current vulnerability in the title.  

### What version of the PMIx Reference Library are you using? 
3.2.3

### Describe how PMIx was installed 
3.2.3 was from an rpm 
### Please describe the system on which you are running

* Operating system/version: RH 8.8
* Computer hardware: https://wiki.ncsa.illinois.edu/display/DSC/Delta+User+Guide#DeltaUserGuide-SystemArchitecture
* Network type: slingshot 10

-----------------------------

## Details of the problem

We wanted a patched version of 3.2.x .

**Comment by kc9qey** [comment]
#!/bin/bash
# our patch for 3.2.3
for source_path in  `find . -exec grep -l chown {} \; 2>/dev/null`
do
        #echo $source_path
        source_file=`basename $source_path`
        source_dir=`dirname $source_path`
        echo repairing:  $source_dir   $source_file
        cat $source_path | sed -e s/chown/lchown/g > /tmp/$source_file
        grep chown /tmp/$source_file
        cp /tmp/$source_file $source_dir
done

**Comment by rhc54** [comment]
You don't need to upgrade anything - this is purely a Slurm problem as it uses PMIx at root levels, and only if you launch something using `srun` (instead of `mpirun`, for example). So if you are using Slurm, then you only need to update the PMIx being used by Slurm itself.

Everything else is just fine.

**Comment by rhc54** [comment]
Which is, FWIW, the reason why we aren't backporting this to out-of-support versions 😄
