### ISSUE TITLE
Is `#define MASK 0x80000057U` endian- and bitness-agnostic?

### ISSUE THREAD

**Issue by barracuda156** [openpmix/openpmix#3186]
Not sure if this is correct on PowerPC:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/openpmix/src/util/pmix_alfg.c:28: warning: "MASK" redefined
   28 | #define MASK 0x80000057U
      | 
In file included from /usr/include/machine/param.h:35,
                 from /usr/include/sys/param.h:110,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/openpmix/src/include/pmix_config_bottom.h:390,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/build/3rd-party/openpmix/src/include/pmix_config.h:893,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/openpmix/src/util/pmix_alfg.c:15:
/usr/include/ppc/param.h:123: note: this is the location of the previous definition
  123 | #define MASK(PART)      ENDIAN_MASK(PART ## _BIT, 32)
      |
```

**Comment by rhc54** [comment]
Odd, given IBM regularly tested this code without complaint. @awlauria ?

Is this a 32-bit build? As noted on a different issue you filed, I'm pretty sure we no longer support 32-bit builds.

**Comment by barracuda156** [comment]
@rhc54 I am not making a claim it is wrong, just inquiring. It does not break the build. If the code is okay for BE and 32-bit as such, we can avoid the warning by adding a simple macro, like `#ifdef MASK #undef MASK #endif`.

**Comment by rhc54** [comment]
I'm going to close this as "will not fix". To the best of my knowledge, PMIx has never supported 32-bit environments. Should you decide to pursue it and offer, you are welcome to include this fix in your eventual patch

**Comment by barracuda156** [comment]
@rhc54 Maybe it will be acceptable to have a single topic about 32-bit support (low-priority issue or a discussion topic)? There are people around interested to support those, and they may join in, if they bump into it.

**Comment by rhc54** [comment]
Frankly, I've never encountered anyone up until now. Let's see if anything comes of it and/or if anyone else cares to raise it.
