### ISSUE TITLE
dstore: keep track of the proc data stored in the dstore.

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#320]
Analysis of the direct-modex performance of the dstore (https://github.com/pmix/master/issues/207, in particular https://github.com/pmix/master/issues/207#issuecomment-282433672) shows that there is some inefficiency there.

Looking through the server-side get logic I've noticed that the following race condition is possible:
* client1 searches dstore and doesn't found info about the procX.
* client1 sends request to the server to get the data.
* client2 searches dstore and doesn't found info about the procX.
* server retrieves procX data and stores them in the dstore and responds to client1 cleaning up this request history.
* client2 requests procX info from the server.
* server will find the procX blob in it's hash table and will publish it second time which will introduce multiple undesired effects, like key overwriting and extra dstore locking.

What needs to be done:
1. I think we don't need to store procX data in the server hash if we use dstore.
2. We need to implement dstore callback to query presence of the procX data in the dstore.

**Comment by rhc54** [comment]
I believe this may now be out-of-date and somewhat overlaps #586 - can you please confirm and close if true?

**Comment by artpol84** [comment]
I am sure that nothing has been done to fix that so far, so this is still relevant.
I think that #586 describes the functionality issue (that we are going to address ASAP), while this issue describes a performance problem.
Currently server will always publish the data in the dstore if he got the message from the client. But sometimes because of the concurrent dstore access server will receive multiple requests and thus publish same data twice doing useless work and introducing extra locking contention.

I would like to keep this Issue and we will address this along with #586 but with less urgency as its not a functionality bug.

**Comment by artpol84** [comment]
@karasevb lets see what's happening in #586 and keep this issue in mind. Probably we will be able to solve both of this at once.

**Comment by jjhursey** [comment]
@artpol84 Is this ticket ok to close? Given the #586 was resolved and the dstore enhancements that went into master?

**Comment by artpol84** [comment]
I believe this is still relevant. Though not a high prio. Can discuss on the telecon next week (I'm not available this week)

**Comment by rhc54** [comment]
No longer relevant
