### ISSUE TITLE
Overwriting value in KVS conflicts with PMIx Process Group

### ISSUE THREAD

**Issue by sonjahapp** [openpmix/openpmix#3201]
## Background information

Hello

at ParTec AG we are exploring PMIx Process Groups in our MPI implementation. In this context, we have come across a strange behaviour and would appreciate an expert opinion.

Many thanks in advance!

CC  @krempel-pt 

### What version of the PMIx Reference Library are you using? 
OpenPMIx 4.2.7

PRRTE 3.0.2 for testing

### Describe how PMIx was installed 
from source via git clone

### Please describe the system on which you are running

* Operating system/version: docker cluster: host uses Fedora 36, containers use Rocky 9 based image
* Computer hardware: x86
* Network type: host: ethernet; within docker cluster an overlay network is used

-----------------------------

## Details of the problem

In a nutshell, this is the sequence that we used:
- `PMIx_Init`
- `PMIx_Put/Commit/Fence/Get` for a unique key-value pair per client
- `PMIx_Group_construct`
- `PMIx_Put/Commit/Fence/Get` for the same key as before but for updated values in each client
- `PMIx_Group_destruct`
- `PMIx_Finalize`

[Here is a reproducer](https://github.com/openpmix/openpmix/files/13449946/group-put-get.zip) for this sequence (inspired by and based on the `double-get.c` test). Use the `--group` option to run the above sequence.

**Expected behaviour:**
- The second `PMIx_Put/Commit/Fence/Get` provides the updated values in all clients.

**Observed behaviour:**
- In a single node run of the above sequence with `prterun` we observe the expected behaviour.
- However, in a multi-node run with `prterun`, the second `PMIx_Put/Commit/Fence/Get` sequence provides the original values in the clients. The overwriting of values does not work across nodes - despite using the `PMIX_COLLECT_DATA`attribute on `PMIx_Fence` and `PMIX_GET_REFRESH_CACHE` on `PMIx_Get` and the `PMIX_GLOBAL` scope on `PMIx_Put` in all cases.

**Questions:**
- Is the observed behaviour a bug or is this expected?
- Is there a problem in the multi-node case if a value in the KVS shall be overwritten, which has been put by a process that (at the point of the put) was not part of the group (or part of a different - previously existing - group)?
    - Could this be an issue with the "scope" of values in the KVS?

**Comment by rhc54** [comment]
Hmmm...well, that would be a bug and I'll have to look into it. Note that the overwrite behavior has nothing to do with group operations. If you update a value with Put/Commit/Fence, then it should be updated everywhere that participated in the Fence. Or are you saying that it works, except when you do a group construct in between the two Put/Commit/Fence operations? That would be strange.

Might be problematic to insist it be updated _everywhere_, even for procs that don't participate in the Fence. Guess it begs the question of whether procs that don't participate in a Fence should have access to data that was shared during the Fence. Probably not? Would be challenging to implement, I imagine, as it would require global distribution of the values, including nodes that had no participation in the Fence. I don't think PRRTE supports it -- now I'll have to check!

**Comment by sonjahapp** [comment]
> Or are you saying that it works, except when you do a group construct in between the two Put/Commit/Fence operations? 

Yes, that's what I'm saying. You can reproduce the behaviour without the group with the attached reproducer program using the `--refresh` option instead of the `--group` option. This will not create/ destroy the group but anything else remains the same. Then the overwrite behaviour is as expected. So somehow the existence of the group seems to cause an issue here...

>Guess it begs the question of whether procs that don't participate in a Fence should have access to data that was shared during the Fence. Probably not? 
In our use case all processes that participate in the Fence should have access to the data - independent of any process group that any process belongs to. That would be sufficient.

**Comment by rhc54** [comment]
Huh - okay, that is indeed strange. I'll have to take a look at it.

**Comment by rhc54** [comment]
Haven't forgotten this - just tied up with some other things. Was able to reproduce it, but probably won't get to it before mid-to-late next week.
