### ISSUE TITLE
Missing src/mca/common/Makefile.am at ./autogen.pl line 96, <IN> line 1

### ISSUE THREAD

**Issue by albandil** [openpmix/openpmix#3308]
I am trying to compile the git version of OpenPMIX on openSUSE Tumbleweed 20240305 with Automake 1.16.5 and Autoconf 2.71. If I check out the tag `v4.2.9`, everything works fine. However, if I check out the tag `v5.0.0` (or any later including the tip of the master branch) and update git submodules, running of *autogen.pl* fails:
```
(...)

=== Found pmix framework: src/mca/pstat
    Found framework configure.m4 file
--- Found pmix / pstat / linux component: src/mca/pstat/linux
    Found configure.m4 file
--- Found pmix / pstat / test component: src/mca/pstat/test
    Found configure.m4 file

=== Found pmix framework: src/mca/pstrg
--- Found pmix / pstrg / lustre component: src/mca/pstrg/lustre
    Found configure.m4 file
--- Found pmix / pstrg / vfs component: src/mca/pstrg/vfs

=== Found pmix framework: src/mca/ptl
--- Found pmix / ptl / client component: src/mca/ptl/client
--- Found pmix / ptl / server component: src/mca/ptl/server
--- Found pmix / ptl / tool component: src/mca/ptl/tool
Missing src/mca/common/Makefile.am at ./autogen.pl line 96, <IN> line 1.
```

**Comment by ggouaillardet** [comment]
after you update the modules, run `git clean -df` in `3rd-party/openpmix` and `3rd-party/prrte` and see if it helps

**Comment by albandil** [comment]
> run `git clean -df` in `3rd-party/openpmix` and `3rd-party/prrte` and see if it helps

This is Open PMIx, not Open MPI repository, so there are no 3rd-party sumodules, only the `oac` one. But even though `git clean -df` in the main tree did not solve the issue, cloning the repository anew did. I should have tried that before, I am closing this issue.
