### ISSUE TITLE
zlib-ng not used on fedora 40

### ISSUE THREAD

**Issue by PhilipDeegan** [openpmix/openpmix#3351]
### What version of the PMIx Reference Library are you using? 

```
major=5
minor=0
release=2
```

### Describe how PMIx was installed 

indirectly via openmpi v5.0.3

### Please describe the system on which you are running

* Operating system/version: fedora 40
* Computer hardware: amd cpu (not relevant)
* Network type: N/A

-----------------------------

## Details of the problem

Trying to use `mpirun` results in 

```
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
```

zlib-ng is installed as zlib is deprecated in fedora 40

```
/usr/include/zlib-ng.h
/usr/include/zlib_name_mangling-ng.h
/usr/lib64/libz.so.1.3.0.zlib-ng
/usr/lib64/cmake/zlib-ng
```

**Comment by rhc54** [comment]
No idea what `zlib-ng` is nor why someone deprecated `zlib`, but the message explains how to suppress the warning. I will put looking into this other library on the list of things to consider down the road - not likely until end of year or probably sometime next year.

**Comment by PhilipDeegan** [comment]
> No idea what zlib-ng

https://github.com/zlib-ng/zlib-ng

> why someone deprecated zlib

https://fedoraproject.org/wiki/Changes/ZlibNGTransition

**Comment by rhc54** [comment]
Okay, nice to know - looks like something only relevant to Fedora 40 and above, so would need some special configure logic changes. As I said, low priority but will eventually get to it.

Or if someone wants it faster, then please post a PR and I'm happy to consider it!

**Comment by ggouaillardet** [comment]
For the time being, can't you simply install the `zlib-ng-compat-devel` package and rebuild `openpmix`?

**Comment by PhilipDeegan** [comment]
I would expect that should work yes
