### ISSUE TITLE
Segfault in KVS for PMIX_DATA_ARRAY that contains PMIX_PROC_INFO

### ISSUE THREAD

**Issue by sonjahapp** [openpmix/openpmix#3358]
## Background information

Hello Ralph

I hope you are doing fine!

I stumbled over a segfault related to the KVS while I did some experiments exchanging data from a parent process to spawned child processes via `PMIx_Put`/`PMIx_Get`.

### What version of the PMIx Reference Library are you using? 
- Tested with OpenPMIx v5.0.2 and master (85a7626d)
- Used PRRTE 3.0.5

### Describe how PMIx was installed 
from a git clone

### Please describe the system on which you are running

* Operating system/version: Rocky Linux release 9.4
* Computer hardware: docker swarm cluster
* Network type:

-----------------------------

## Details of the problem

Here is what I tried:
1. Parent process uses `PMIx_Put` to place a `PMIX_DATA_ARRAY` of `PMIX_PROC_INFO` data into the KVS and then calls `PMIx_Commit`
2. Parent process spawns new processes
3. Parent and all spawend processes call `PMIx_Fence` with `PMIX_COLLECT_DATA`
4. Spawned processes use `PMIx_Get` to retrieve the `PMIX_DATA_ARRAY` that was previously put into the KVS by the parent

Steps 1.-3. work fine, independent of the amount of used nodes.
For step 4. I observed the following:
- Segfault in spawned processes if all processes (original and spawned) run on a single node; as far as I can tell, the segfault appears when spawned processes attempt to store something in their KVS
- Works if multiple nodes are used

I have tried also with other data types for the `PMIX_DATA_ARRAY`, for example `PMIX_BOOL` or `PMIX_INT`, without any problem. For now, I only observed the segfault when `PMIX_PROC_INFO` was stored in the `PMIX_DATA_ARRAY`.

Do you have any ideas about the cause of this? Am I doing something that is not supported?

Thanks a lot for your help!

**Comment by sonjahapp** [comment]
I will add a reproducer and try to get a stack trace asap.

**Comment by sonjahapp** [comment]
Here comes the reproducer: [spawn_kvs_test.zip](https://github.com/user-attachments/files/15973492/spawn_kvs_test.zip)

**Comment by rhc54** [comment]
I see the problem - you have set hostname and executable fields to `NULL` and the code isn't protected against that...wasn't expecting it 😄 . I'll harden the code so that doesn't trip us up.
