### ISSUE TITLE
Problems with PMIx_Resolve_peers and spawned processes

### ISSUE THREAD

**Issue by sonjahapp** [openpmix/openpmix#3359]
## Background information

Hello again!

I found a few problems with the use of `PMIx_Resolve_peers` and spawned processes for different versions of OpenPMIx. I'm not sure if all these "problems" are actually bugs. Perhaps I am doing something wrong or something that is not supported by the PMIx standard. Any insights would be highly appreciated!

### What version of the PMIx Reference Library are you using? 
- Tested with OpenPMIx 4.2.9, 5.0.2 and master (85a7626d)
- Used PRRTE 3.0.5

### Describe how PMIx was installed 
from a git clone

### Please describe the system on which you are running

* Operating system/version: Rocky Linux release 9.4
* Computer hardware: docker swarm cluster
* Network type:

-----------------------------

#### General observations (independent of OpenPMIx version):
- According to the PMIx standard (see PMIx 5.0, Section 7.2), the returned process array should be `NULL` and `nprocs == 0` if there are zero processes of a namespace running on a given node. However, currently `PMIX_ERR_NOT_FOUND` is returned in this case which is somewhat confusing because this indicates (at least to me) that something went wrong 
- Setting the `nspace` argument of this function to `NULL` should return all processes running on a node independent of their namespace; this does not work for cases where multiple nspaces are running on the same node

#### Observations for different OpenPMIx versions:

- Test cases
    - 1 All procs (original and spawned) on single node
    - 2 Spawned processes on node that has not been used previously by any processes
    - 3 Spawned processes are on same node as at least one of the original processes
- docker swarm cluster was used for testing
    - Start 2 procs, `testapp` spawns 2 processes
    - 1 `prterun -np 2 --host=n01:4 ./testapp`
    - 2 `prterun -np 2 --host=n01:2,n02:2 ./testapp`
    - 3 `prterun -np 2 --host=n01:1,n02:3 ./testapp`

Case/Version |  4.2.9 | 5.0.2 and master (85a7626d)
 -----|----------------|-----------
 1 |  works | works with PMIx process group over *all* procs<br><br> without PMIx process group: `PMIX_ERR_NOT_FOUND` returned for spawned nspace in original procs<br><br>Works for spawned procs
2 | `PMIX_ERR_NOT_FOUND` for spawned nspace on original nodes<br><br> `PRTE ERROR: Not found in file <...>/src/prted/pmix/pmix_server_fence.c at line 248` for spawned procs <br><br> *might be partly a PRRTE issue?* |  `PMIX_ERR_NOT_FOUND` for<br>- spawned nspace in original procs on node with spawned procs and on own node<br>- original nspace in spawned procs on node with original procs and on own node<br><br>*In essence: nspaces can't resolve each others peers*<br><br> PMIx Process group makes no difference
3 |hangs in original procs when resolving for spawned nspace (`PMIX_ERR_TIMEOUT`)<br><br>`PRTE ERROR: Not found in file <...>/src/prted/pmix/pmix_server_fence.c at line 248` for spawned procs | See 5.0.2, case 2 

I will add a reproducer for this asap (need to strip down my test program first to make it focus on this aspect ;-) )

Thanks a lot for the help!

**Comment by rhc54** [comment]
Hmmm...we may have a problem with the standard here - you cannot pass a `NULL` for the nspace argument as it is a `pmix_nspace_t` (at least, in the current library), which is a fixed-size array. The compiler should have complained about it. We should probably change it to a `const char*` so we can support a `NULL` argument.

I'll take a peek at this shortly.

**Comment by sonjahapp** [comment]
Here comes a reproducer: [node_map_test.zip](https://github.com/user-attachments/files/15986842/node_map_test.zip)

**Comment by rhc54** [comment]
Hmmm...something isn't quite right with your list code - I'm getting strange behavior when accessing the length of the list. Looks like there is some memory corruption going on when running your case 1.

When I add a simple print to `get_node_list`:
```c
    utarray_new(list, &ut_str_icd);
    list->i = 0;
    printf("[%u] LEN: %ld %ld\n", own_proc.rank, list->i, utarray_len(list));
```
I get this output:
```shell
[1] LEN: 105553116266496 0
[prterun-Ralphs-iMac-38140@1:0]: Init (round 1, pid = 38141)
[0] LEN: 105553116266496 0
```
I added it because I keep seeing output like this from your print statement:
```shell
[prterun-Ralphs-iMac-38140@2:0]: nodes: 30064771073, node list: Ralphs-iMac
```
which looks like `i` is not being initialized or is being overwritten.

Still, I can see the behavior of not finding an nspace that shares the node, so I'll look into it.

**Comment by sonjahapp** [comment]
That's strange. The `UT_array` code is a slightly adapted version from the [MPICH code base](https://github.com/pmodels/mpich/blob/main/src/mpl/include/utarray.h). I tried on different systems and I was not able to reproduce the memory issue anywhere... :thinking:

Even more strange is that you access the value `list->i` twice in the same `printf`, the first time it gives you garbage and the second time via `utarray_len` it works? Is this the same when you flip first and second, so put `utarray_len` at first and then access `list->i` directly?

**Comment by sonjahapp** [comment]
Have you tried with `%u` as output formatter for the list length instead of `%ld` to exclude the possibility that this is an output formatting issue? The datatype of `list->i` is `unsigned` after all. An in your example above, both ranks give the exact same garbage...

**Comment by rhc54** [comment]
I can look later - it isn't really impacting me right now. I have an example in the PRRTE repo (dynamic.c) that executes the same logic, so I can just use it for now. It appears that the problem (at least for me) is that the hostname aliases for the spawned procs aren't being passed down to the parent procs, and so we aren't matching the node names (one is fully qualified and the other isn't). Will take a bit to track that down.

**Comment by sonjahapp** [comment]
>  It appears that the problem (at least for me) is that the hostname aliases for the spawned procs aren't being passed down to the parent procs, and so we aren't matching the node names (one is fully qualified and the other isn't). Will take a bit to track that down.

Let me know if there is something that I can do to help solving this issue.

> Have you looked at the `PMIx_Argv_xxx` functions?

Thanks for the hint, I will have a look!

**Comment by rhc54** [comment]
> Let me know if there is something that I can do to help solving this issue.

I appreciate the offer, but I hesitate to point you at anything just yet. The hostname alias issue might just be something local to me and not the core problem. Just something I have to resolve (pardon the pun) before I can move forward, and I'm somewhat swamped at the moment.

**Comment by rhc54** [comment]
@sonjahapp Sorry for the very long delay. Just in case you are still interested, figured I should let you know that I've started working on this again and am making a little progress. I found an error in your provided reproducer that I figured I should mention. In your "do_spawn" function, the process doing the spawn publishes the namespace of the spawned job and calls "commit". However, you never did a "fence" to share that value with the other procs in the parent job.

So when any of those other procs attempts to "get" the namespace of the child job (so they can attempt to "resolve" things about them), the "get" operation fails. I added a "fence" to fix the problem:
```c
        /* spawn new procs */
        rc = PMIx_Spawn(NULL, 0, apps, 1, child_nspace);
        CHECK_PMIX_ERR(rc, "PMIx_Spawn", own_proc);
        PMIX_APP_FREE(apps, 1);

        /* parent puts new child nspace into KVS */
        pmix_value_t val;
        PMIX_VALUE_LOAD(&val, child_nspace, PMIX_STRING);
        rc = PMIx_Put(PMIX_GLOBAL, SPAWN_NSPACE, &val);
        CHECK_PMIX_ERR(rc, "PMIx_Put child namespace (parent)", own_proc);
        rc = PMIx_Commit();
        CHECK_PMIX_ERR(rc, "PMIx_Commit", own_proc);
    }

    /**********   NEW CODE   *************/
    // circulate the name of the child nspace
    PMIX_PROC_LOAD(&jobproc, own_proc.nspace, PMIX_RANK_WILDCARD);
    err = PMIx_Fence(&jobproc, 1, NULL, 0);
    CHECK_ERR(err);
   /*****************************************/
```

Doesn't resolve the issues mentioned above - just necessary for fixing one source of error.

I also noticed you didn't call `PMIx_Connect` between the spawning proc and the child processes, instead opting for a "fence" op between them. I added the option to use "connect" so we can see if there is a difference in behavior.

Let me know if you are still interested. I'll be working on it anyway, but won't bother you further if you are not.

**Comment by rhc54** [comment]
Okay, I dug through this and found that the remaining problems are due to errors in the example program.  I explained the most critical one in the referenced PR, but will copy it here:

> IMPORTANT NOTE: when you spawn a child job and want to collect job-level info on it, you MUST use PMIx_Connect to share the info across parent and child jobs. Using PMIx_Fence - even with the "collect data" flag - only shares the data that each process "put" - it does not include job-level data.

So if you just do a fence between the parent and child jobs, you will not get the job-level data shared across them - which means that "resolve peers" will fail when asking about the other job. This is why `PMIx_Connect` was created. 😄 

I included a corrected version of the example program in the PR and it will now appear in the PMIx code base as "examples/resolve.c".

**Comment by rhc54** [comment]
@krempel-pt Just wanted to make sure you folks were aware of the resolution to this problem (haven't heard back from @sonjahapp) - please see #3438 and #3439 for the full explanation.

**Comment by sonjahapp** [comment]
Hi @rhc54 

Thanks for looking into this. I was out out office the last couple of days so I couldn't get back to you earlier, sorry.

I'm currently looking into the solution that you have proposed (using `PMIx_Connect` instead of `PMIx_Fence` to properly share the job-level data between original and spawned procs).

Even with `PMIx_Connect` I'm still getting erroneous results for `PMIx_Resolve_peers`, for example if the original and the spawned processes are running on distinct nodes (let say n01 + n02 for the original and n03 + n04 for the spawned procs) some namespaces still get reported as not found, e.g. a spawned proc on n03 cannot find/resolve the parent's namespace on n01.  My investigation is still ongoing at this point, just wanted to give you a first feedback.

I also need to check if there is an issue with my testing setup.

I'll put an update here once I have a more structured view on the status.

**Comment by rhc54** [comment]
Good to hear from you! Keep in mind that you will get "not found" if the nspace in question doesn't have any procs running on the specified node. This is actually the correct response in that situation.

**Comment by sonjahapp** [comment]
> you will get "not found" if the nspace in question doesn't have any procs running on the specified node

I noticed that as well. Shouldn't `procs` be `NULL` and `nprocs` equal to `0` in this case and the return value of `PMIx_Resolve_peers` be `PMIX_SUCCESS`? Is it really erroneous to call this function with a combination of node/ namespace that yields zero processes as output when there *are* zero processes of the specified namespace running on the specified node? I think only the case of an unknown node should actually return a "not found" error.

Unfortunately, the standard stays relatively vague on this... :thinking:

**Comment by rhc54** [comment]
I fear the section I wrote for the standard is somewhat vague because the right answer isn't entirely clear to me. I could argue it in multiple ways - e.g., there are no peers for that nspace "found" on the specified node, so returning "not found" makes some sense. On the other hand, that could get confused with another error - e.g., if we cannot find the specified nspace, or we cannot find the specified node. All of which leaves the caller somewhat uncertain as to the meaning of the result.

I suppose we could create additional error codes (e.g., `PMIX_ERR_NSPACE_NOT_FOUND` and `PMIX_ERR_NODE_NOT_FOUND`) to help be more specific as to the problem. I could then (I think?) argue convincingly that returning "success" even if no peers exist on the specified node would make the most sense - it would indicate that we were indeed able to fully process the request.

However, all `PMIx_Resolve_peers` does under-the-covers is call `PMIx_Get` for the `PMIX_LOCAL_PEERS` key, including the required qualifiers to identify the node in question. The "not found" error is simply being returned from `PMIx_Get`, which is the correct response for it if the node or the proc/nspace or the key cannot be found. So I'm not sure how we determine (without adding a bunch of code) that it is the nspace or node that wasn't found.

Would have to scratch my head awhile over this one - I don't see an immediate good answer, which usually means it is best to just leave it alone since that is compatible with what has been there for quite some time.

**Comment by rhc54** [comment]
Please see https://github.com/openpmix/openpmix/pull/3497 and the doc page it added for a more detailed explanation.
