### ISSUE TITLE
PMIx_Lookup results not returned to user on PMIX_ERR_PARTIAL_SUCCESS

### ISSUE THREAD

**Issue by dgloe-hpe** [openpmix/openpmix#3364]
### What version of the PMIx Reference Library are you using?
4.2.9

### Describe how PMIx was installed
Built from source into RPMs

### Please describe the system on which you are running

* Operating system/version: SLES 15 SP5
* Computer hardware: Virtual Machine
* Network type: Virtual machine network

-----------------------------

## Details of the problem

If a PMIx server handling a PMIx_Lookup returns PMIX_ERR_PARTIAL_SUCCESS along with a partial pdata array, the results don't get copied back to the user's pdata array. I believe this is because the `lookup_cbfunc` function in `src/client/pmix_client_pub.c` only fills in the output if the status is PMIX_SUCCESS, not on PMIX_ERR_PARTIAL_SUCCESS.

**Comment by rhc54** [comment]
Thanks for the triage! Made it very easy to fix.
