### ISSUE TITLE
PMIx_Spawn prefix handling issue on 5.0.2

### ISSUE THREAD

**Issue by dgloe-hpe** [openpmix/openpmix#3370]
### What version of the PMIx Reference Library are you using?

5.0.2

### Describe how PMIx was installed

RPMs built from source

### Please describe the system on which you are running

* Operating system/version: SLES 15 SP5
* Computer hardware: VM
* Network type: VM network

-----------------------------

## Details of the problem

We have a PMIx spawn test program that worked fine with PMIx 4.2.9 but fails on PMIx 5.0.2. I've found two issues:

1. The app.cmd passed in by the client must be dynamically allocated, otherwise there's a invalid free().
2. The PMIX_PREFIX isn't applied to the app.cmd or app.argv passed into the PMIx server.

I think this is related to https://github.com/openpmix/openpmix/pull/3330.

It seems to me that this section of code in `src/client/pmix_client_spawn.c` should be modifying `appsptr[n]` rather than `aptr`:

```
319         // adjust the cmd prefix if required
320         if (NULL != prefix) {
321             // prefix the command
322             pmix_asprintf(&tmp, "%s/%s", prefix, aptr->cmd);
323             free(aptr->cmd);
324             aptr->cmd = tmp;
325         } else if (NULL != defprefix) {
326             // prefix the command
327             pmix_asprintf(&tmp, "%s/%s", defprefix, aptr->cmd);
328             free(aptr->cmd);
329             aptr->cmd = tmp;
330         }
```

**Comment by rhc54** [comment]
Hmmm...nerts! Thought I had caught all of those. Sigh. Thanks for catching it.

I'm not sure about your comment regarding app.argv - we wouldn't prefix `argv[0]` as that is supposed to be just the basename. So I don't believe the prefix ever gets applied to the argv array - just to the cmd.
