### ISSUE TITLE
mpirun -xml option has no effect when run under indirect debugger example

### ISSUE THREAD

**Issue by david-edwards-linaro** [openpmix/openpmix#3405]
### What version of the PMIx Reference Library are you using? 
Open MPI 5.0.0

### Describe how PMIx was installed 
tarball

### Please describe the system on which you are running

* Operating system/version: Ubuntu 22.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

Running `./indirect mpirun -xml -n 1 ../../../../examples/hello_c` from the `openmpi-5.0.0/3rd-party/prrte/examples/debugger` directory gives the output of hello_c _not_ in xml format, whereas running `mpirun -xml -n 1 ../../../../examples/hello_c` does give output in xml format.
Expected behaviour is that running under indirect does not affect the output format.

**Comment by rhc54** [comment]
Almost have this fixed - a little more involved as the problem stems from the `indirect` app directly spawning `mpirun` via the internal fork/exec support. Need to include the IOF directives in that code path. Should have it soon.
