### ISSUE TITLE
no shared object created after compilation

### ISSUE THREAD

**Issue by asfbar** [openpmix/openpmix#3454]
### What version of the PMIx Reference Library are you using? 

installed from **pmix-3.2.2.tar.bz2**

### Please describe the system on which you are running

* Operating system/version: **Rocky Linux release 8.10**
-----------------------------

**The problem:**
After sucessfull compilation the shared object **libpmix_v3.so is not beeing created**
i would like to add it to already installed slurm work manage.

Thank you.
assaf

**Comment by asfbar** [comment]
@rhc54 so i need to point slurm config file to in order to make it use pmix_v3?
and see it in the mpi list?

**Comment by rhc54** [comment]
Slurm does some weird naming in their mpi list that has nothing to do with the PMIx library. They do it for their own debugging purposes so they know what version of PMIx they are utilizing (in this case, PMIx v3.x). I've pointed out multiple times how this confuses users, to no avail.

I have no idea how Slurm points to the actual PMIx library. Pretty sure it has to be at configure time and not in the "slurm.conf" file, but you'd need to check their documentation.

> BTW i'm seeing libpmix.so.2.2.35 is that you meaning?

Are you installing it via rpm?? If so, then the added numbers are coming from the packager - and I have no control over what they do. However, that is almost certainly the library you are looking for.

**Comment by asfbar** [comment]
@rhc54 i'm installing from source 
```
./configure --prefix=...
make all install 
```

**Comment by rhc54** [comment]
Huh - well, your toolchain must be adding them. Doesn't matter.
