### ISSUE TITLE
Checksum of PMIx assets for v5.0.3 changed

### ISSUE THREAD

**Issue by enrico-usai** [openpmix/openpmix#3472]
## Details of the problem

Version 5.0.3 has been released on Jul 9, but the checksum of the assets changed today.
https://github.com/openpmix/openpmix/releases/tag/v5.0.3
```
Assets 
pmix-5.0.3-1.src.rpm 9.47 MB 11 hours ago
pmix-5.0.3.tar.bz2 9.5 MB 11 hours ago
pmix-5.0.3.tar.gz 10.8 MB 11 hours ago
```

Previous checksum for the tar.gz package was: `d9b0b81ba45f58f44573796eb05858061ed7f47ea6b29af8058090023e35dfa9`
now is: `8bd6c3918f081bef92f6772cad4c0f0debfdb098136c2ca04da15d1a620819c9`

Could you please clarify what happened to 5.0.3 artifacts?

Thanks

**Comment by enrico-usai** [comment]
I just found this issue that should be related: https://github.com/openpmix/openpmix/issues/3470

**Comment by rhc54** [comment]
Yes - the assets were updated as explained in the referenced issue. Nothing changed so far as the code.

**Comment by enrico-usai** [comment]
@rhc54 should we expect further changes?

**Comment by enrico-usai** [comment]
@rhc54 should we expect further changes in the packages? 

I'm asking because I saw your comment 1 hour ago in the original issue: https://github.com/openpmix/openpmix/issues/3470#issuecomment-2548445450

Thanks for helping.

**Comment by rhc54** [comment]
> @rhc54 should we expect further changes in the packages?
> 
> I'm asking because I saw your comment 1 hour ago in the original issue: [#3470 (comment)](https://github.com/openpmix/openpmix/issues/3470#issuecomment-2548445450)
> 
> Thanks for helping.

Heck if I know - I have no idea how/why the assets reverted to their original (incorrect) versions. I sure didn't change them back!

Still, there was nothing actually wrong with those originals. They just contained some Apple cruft that the build system ignored anyway. So no harm, just a little confusing to look at.

**Comment by enrico-usai** [comment]
Thank you. I appreciate your prompt response.
