### ISSUE TITLE
PGI Compiler libevent pthread check

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#453]
If libevent is built with a non-PGI compiler then PMix can error out during a build looking for the `-pthread` option instead of `-lpthread`. The work around is to build PMIx against a version of libevent that was built with PGI.

We should investigate if we can add an easy configure check to error out in configure with a helpful error message. Note that Open MPI might also need a similar check in their external PMIx component configure.m4 logic.

 * Refer to comment [here](https://github.com/pmix/pmix/pull/449#issuecomment-321620751)

**Comment by ggouaillardet** [comment]
a similar issue was reported but with ```libpmi.so``` provided by slurm.
should we simply hack the generated configure and remove the ```-pthread``` flag if ```PGI``` compiler is used ? (i do not have a clear recollection, but i might have implemented a similar trick for ```NAG``` fortran compiler)

**Comment by rhc54** [comment]
@jjhursey Is this still an issue?

**Comment by jjhursey** [comment]
Yeah, I think so. We have two different libevent installs for pgi and everyone else. I've not had the cycles to get back to it. It might be good if some of our Nvidia friends took a look.

**Comment by jjhursey** [comment]
Reference:
 * https://github.com/open-mpi/ompi/issues/2331
 * Apparently `nvcc` is also impacted: https://github.com/open-mpi/ompi/issues/2331#issuecomment-632291997

**Comment by jjhursey** [comment]
We should have someone from NVIDIA take a look at this since they own PGI and nvcc. They might be able to come up with a common solution.

**Comment by rhc54** [comment]
@artpol84 Any thoughts on who over there could do this?

**Comment by rhc54** [comment]
Pretty clear nobody cares 🤷‍♂️
