### ISSUE TITLE
consider file descriptor passing from RM to client instead of accept()

### ISSUE THREAD

**Issue by garlick** [openpmix/openpmix#90]
PMIx currently creates a UNIX domain socket and accepts connections from clients on it.

Is there a reason there shouldn't _also_ be an optional mode where the RM calls `socketpair()` to create both client and server fds in one go, and passes them to PMIx RM interfaces, then ensures the client fd remains open across fork when the client is started?

PMIx would construct `PMIX_SERVER_URI` to contain the client fd number, so that the client can get hold of the server socket.  The server would use the other fd instead of one returned from `accept()`.

This way PMIx doesn't need to manage the socket in the file system namespace, worry about listen queues and acceptor threads, authenticate connections, etc., and thus be a bit more efficient.

**Comment by rhc54** [comment]
I believe this is doable as an optional mode - for simplicity, we could just pass a ```PMIX_SERVER_FD``` in this case so the URI isn't confusing. The only limitation you should be aware of is that a client process won't be able to fork/exec and have its child connect to the PMIx server. We'll also need to protect the server against such connection attempts so we don't lose the original connection or other bad things.

Please feel free to provide a patch for it 😄

**Comment by garlick** [comment]
> The only limitation you should be aware of is that a client process won't be able to fork/exec and have its child connect to the PMIx server.

Hmm, I hadn't thought about that one.  Did you have a specific use case in mind for that?

**Comment by rhc54** [comment]
We ran into it with some applications running under SLURM, but it could become more prevalent given the broader use-cases from the extended PMIx APIs. For example, a client might fork/exec a child that wants to receive event notifications.

**Comment by garlick** [comment]
I did get this working, nominally  - here are a few notes.

There are some client mods to skip the socket connect if `PMIX_SERVER_FD` is set in `PMIx_Init()` on this [socketpair](https://github.com/garlick/pmix/tree/socketpair) branch, in commit 625ccac97017a3e715d6f6824f89a31aa1b98c51.  This included a little refactoring to avoid code duplication.

I didn't have change anything in the PMIx server code to get this working;  instead I registered a listener callback to capture the `pmix_connection_cbfunc_t`.  Then in my server, I manually set `PMIX_SERVER_FD` in the client environment, and hand the server fd to the connection cb.  This could be made easier on the RM implementer if 
* pmix_connection_cbfunc_t was exposed directly
* environment setting was incorporated into `PMIx_server_setup_fork()` (somehow),
* there were a way to disable creation of the UNIX domain socket. 

Other odds and ends:
* calling the above connection callback must happen after client fork (thus not at `PMIx_server_register_client()` time) because of the blocking I/O in the client handshake; o/w PMIx server thread hangs
* "native' security claims to succeed on the socketpair. I expected to have to disable that.  I looked for SO_PEERCRED but couldn't find it in the code.  How is it implemented?

Anyway that was just a throw away attempt to find out what's involved.  Success I think!

**Comment by rhc54** [comment]
Native security is just a trivial thing that passes the UID and GID of the client in string form (you can find it in src/sec/pmix_native.c) - nothing like SO_PEERCRED involved. I believe SO_PEERCRED has been deprecated in favor of SCM_CREDENTIALS, but I can't swear to it - regardless, we took the low road.

**Comment by garlick** [comment]
Ah thanks.  That would seem fairly easy to add and would be better security than chowning the socket which is non-portable and inherently racy.  Would you be open to an issue/patch on modifying "native" to do that?

**Comment by rhc54** [comment]
Sure - thanks!

**Comment by garlick** [comment]
@rhc54 when you have a free moment, I have couple questions about this from pmix_server_listener.c:
```C
static void listener_cb(int incoming_sd)
{
    pmix_pending_connection_t *pending_connection;

    /* throw it into our event library for processing */
    pmix_output_verbose(8, pmix_globals.debug_output,
                        "listen_cb: pushing new connection %d into evbase",
                        incoming_sd);
    pending_connection = PMIX_NEW(pmix_pending_connection_t);
    pending_connection->sd = incoming_sd;
    event_assign(&pending_connection->ev, pmix_globals.evbase, -1,
                 EV_WRITE, connection_handler, pending_connection);
    event_active(&pending_connection->ev, EV_WRITE, 1);
}
```
Why is `connection_handler()` assigned an EV_WRITE event when the client will send data first?

How come `event_active()` call is needed?

What prevents races on libevent state when this function is called from the listener thread or the RM and makes libevent calls that modify pmix_globals.evbase which (as I understand it) is owned by the main `progress_engine()`  thread?

Thanks in advance for any hints that will aid my spelunking efforts :-)

**Comment by rhc54** [comment]
The assign/active method used here is a little libevent "trick" for pushing code paths into an event base. It creates an event and then immediately "flags" it as active, thus ensuring it gets serviced on the next event loop. There is no file descriptor involved (demarked by the -1 in the assign call) - the EV_WRITE in both calls simply matches the pairing (could have used EV_READ in both places, or any EV state).

Libevent takes care of all the thread lock/unlock actions required for putting things on its event lists, so we don't need anything here.

**Comment by garlick** [comment]
Ah that makes sense now! I hadn't noticed the -1 fd. Thanks,

**Comment by rhc54** [comment]
Closing this for now - we can revisit it if needed some day.
